apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: justice-person-platform-dev-cert
  namespace: justice-person-platform-dev
spec:
  secretName: tls-certificate
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames:
  - jpp-dev.service.justice.gov.uk
