---
apiVersion: v1
kind: LimitRange
metadata:
  name: limitrange
  namespace: hmpps-x-ray-body-scans-ui-dev
spec:
  limits:
    - default:
        cpu: 2000m
        memory: 1024Mi
      defaultRequest:
        cpu: 10m
        memory: 512Mi
      type: Container
