apiVersion: v1
kind: Namespace
metadata:
  name: "probationchatbot-dev"
  labels:
    cloud-platform.justice.gov.uk/is-production: "false"
    cloud-platform.justice.gov.uk/environment-name: "development"
    pod-security.kubernetes.io/enforce: restricted
  annotations:
    cloud-platform.justice.gov.uk/business-unit: "HQ"
    cloud-platform.justice.gov.uk/slack-channel: "probation-chatbot-dev"
    cloud-platform.justice.gov.uk/application: "Probation Chatbot"
    cloud-platform.justice.gov.uk/owner: "Justice AI Unit: jaiuteam@justice.gov.uk"
    cloud-platform.justice.gov.uk/source-code: "https://github.com/ministryofjustice/ai-unit-probation-chatbot"
    cloud-platform.justice.gov.uk/team-name: "probation-chatbot"
    cloud-platform.justice.gov.uk/review-after: ""
