kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: justice-redact-staging-admin
  namespace: justice-redact-staging
subjects:
  - kind: Group
    name: "github:justice-redact"
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
