---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: api-ui-certificate
  namespace: hmpps-dpr-tools-probation-prod
spec:
  secretName: dpr-tools-cert
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames:
    - dpr-tools-api.probation.service.justice.gov.uk
    - dpr-tools.probation.service.justice.gov.uk
