apiVersion: v1
kind: Namespace
metadata:
  name: "jatestapp-dev"
  labels:
    cloud-platform.justice.gov.uk/is-production: "false"
    cloud-platform.justice.gov.uk/environment-name: "development"
    pod-security.kubernetes.io/enforce: restricted
  annotations:
    cloud-platform.justice.gov.uk/business-unit: "Platforms"
    cloud-platform.justice.gov.uk/slack-channel: "cloud-platform"
    cloud-platform.justice.gov.uk/application: "Create environment tutorial by JA"
    cloud-platform.justice.gov.uk/owner: "cloud-plaform-engineers: cloudplatform@justice.gov.uk"
    cloud-platform.justice.gov.uk/source-code: "https://github.com/ministryofjustice/jagbai-dev"
    cloud-platform.justice.gov.uk/team-name: "cloud-platform-engineers"
    cloud-platform.justice.gov.uk/review-after: "2026-07-07"
