{
 "title": "Probation in Court - Pods",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "\"court-probation-prod\",\"court-probation-preprod\",\"court-probation-dev\""
   },
   {
    "name": "service",
    "label": "Service",
    "query": "\"prepare-a-case\",\"court-case-service\",\"crime-portal-gateway\",\"court-case-matcher\",\"court-list-splitter\",\"court-hearing-event-receiver\",\"pre-sentence-service\",\"pre-sentence-service-gotenberg\",\"pre-sentence-service-wproofreader\""
   }
  ]
 },
 "panels": [
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  { "type": "text", "gridPos": { "h": 3, "w": 12, "x": 0, "y": 1 }, "content": "# Probation in Court - Pods" },
  { "title": "$service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 }, "repeat": "service" },
  {
   "title": "$service",
   "type": "graph",
   "gridPos": { "h": 5, "w": 16, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (deployment) (kube_deployment_spec_replicas{namespace=$namespace, job=\"kube-state-metrics\", deployment=$service}) ",
     "legendFormat": "Expected"
    },
    {
     "expr": "sum by (deployment) (kube_deployment_status_replicas_available{namespace=$namespace, job=\"kube-state-metrics\", deployment=$service})",
     "legendFormat": "Available"
    },
    {
     "expr": "sum by (deployment) (kube_deployment_status_replicas_unavailable{namespace=$namespace, job=\"kube-state-metrics\", deployment=$service})",
     "legendFormat": "Unavailable"
    }
   ]
  },
  {
   "title": "Expected",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 16, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum by (deployment) (kube_deployment_spec_replicas{namespace=$namespace, job=\"kube-state-metrics\", deployment=$service}) ",
     "legendFormat": "Expected"
    }
   ]
  },
  {
   "title": "Available",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 18, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum by (deployment) (kube_deployment_status_replicas_available{namespace=$namespace, job=\"kube-state-metrics\", deployment=$service})",
     "legendFormat": "Available"
    }
   ]
  },
  {
   "title": "Unavailable",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 20, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum by (deployment) (kube_deployment_status_replicas_unavailable{namespace=$namespace, job=\"kube-state-metrics\", deployment=$service})",
     "legendFormat": "Unavailable"
    }
   ]
  },
  { "title": "$service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "$service",
   "type": "graph",
   "gridPos": { "h": 5, "w": 16, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (deployment) (kube_deployment_spec_replicas{namespace=$namespace, job=\"kube-state-metrics\", deployment=$service}) ",
     "legendFormat": "Expected"
    },
    {
     "expr": "sum by (deployment) (kube_deployment_status_replicas_available{namespace=$namespace, job=\"kube-state-metrics\", deployment=$service})",
     "legendFormat": "Available"
    },
    {
     "expr": "sum by (deployment) (kube_deployment_status_replicas_unavailable{namespace=$namespace, job=\"kube-state-metrics\", deployment=$service})",
     "legendFormat": "Unavailable"
    }
   ]
  },
  {
   "title": "Expected",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 16, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum by (deployment) (kube_deployment_spec_replicas{namespace=$namespace, job=\"kube-state-metrics\", deployment=$service}) ",
     "legendFormat": "Expected"
    }
   ]
  },
  {
   "title": "Available",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 18, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum by (deployment) (kube_deployment_status_replicas_available{namespace=$namespace, job=\"kube-state-metrics\", deployment=$service})",
     "legendFormat": "Available"
    }
   ]
  },
  {
   "title": "Unavailable",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 20, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum by (deployment) (kube_deployment_status_replicas_unavailable{namespace=$namespace, job=\"kube-state-metrics\", deployment=$service})",
     "legendFormat": "Unavailable"
    }
   ]
  },
  { "title": "$service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "$service",
   "type": "graph",
   "gridPos": { "h": 5, "w": 16, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (deployment) (kube_deployment_spec_replicas{namespace=$namespace, job=\"kube-state-metrics\", deployment=$service}) ",
     "legendFormat": "Expected"
    },
    {
     "expr": "sum by (deployment) (kube_deployment_status_replicas_available{namespace=$namespace, job=\"kube-state-metrics\", deployment=$service})",
     "legendFormat": "Available"
    },
    {
     "expr": "sum by (deployment) (kube_deployment_status_replicas_unavailable{namespace=$namespace, job=\"kube-state-metrics\", deployment=$service})",
     "legendFormat": "Unavailable"
    }
   ]
  },
  {
   "title": "Expected",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 16, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum by (deployment) (kube_deployment_spec_replicas{namespace=$namespace, job=\"kube-state-metrics\", deployment=$service}) ",
     "legendFormat": "Expected"
    }
   ]
  },
  {
   "title": "Available",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 18, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum by (deployment) (kube_deployment_status_replicas_available{namespace=$namespace, job=\"kube-state-metrics\", deployment=$service})",
     "legendFormat": "Available"
    }
   ]
  },
  {
   "title": "Unavailable",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 20, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum by (deployment) (kube_deployment_status_replicas_unavailable{namespace=$namespace, job=\"kube-state-metrics\", deployment=$service})",
     "legendFormat": "Unavailable"
    }
   ]
  },
  { "title": "$service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "$service",
   "type": "graph",
   "gridPos": { "h": 5, "w": 16, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (deployment) (kube_deployment_spec_replicas{namespace=$namespace, job=\"kube-state-metrics\", deployment=$service}) ",
     "legendFormat": "Expected"
    },
    {
     "expr": "sum by (deployment) (kube_deployment_status_replicas_available{namespace=$namespace, job=\"kube-state-metrics\", deployment=$service})",
     "legendFormat": "Available"
    },
    {
     "expr": "sum by (deployment) (kube_deployment_status_replicas_unavailable{namespace=$namespace, job=\"kube-state-metrics\", deployment=$service})",
     "legendFormat": "Unavailable"
    }
   ]
  },
  {
   "title": "Expected",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 16, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum by (deployment) (kube_deployment_spec_replicas{namespace=$namespace, job=\"kube-state-metrics\", deployment=$service}) ",
     "legendFormat": "Expected"
    }
   ]
  },
  {
   "title": "Available",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 18, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum by (deployment) (kube_deployment_status_replicas_available{namespace=$namespace, job=\"kube-state-metrics\", deployment=$service})",
     "legendFormat": "Available"
    }
   ]
  },
  {
   "title": "Unavailable",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 20, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum by (deployment) (kube_deployment_status_replicas_unavailable{namespace=$namespace, job=\"kube-state-metrics\", deployment=$service})",
     "legendFormat": "Unavailable"
    }
   ]
  }
 ]
}