---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: hmpps-warrant-risk-assessment-api-cert
  namespace: hmpps-warrant-risk-assessment-dev
spec:
  secretName: hmpps-warrant-risk-assessment-api-cert
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames:
    - warrant-risk-assessment-api-dev.hmpps.service.justice.gov.uk
    - '*.warrant-risk-assessment-api-dev.hmpps.service.justice.gov.uk'

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: hmpps-warrant-risk-assessment-ui-cert
  namespace: hmpps-warrant-risk-assessment-dev
spec:
  secretName: hmpps-warrant-risk-assessment-ui-cert
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames:
    - warrant-risk-assessment-dev.hmpps.service.justice.gov.uk
    - '*.warrant-risk-assessment-dev.hmpps.service.justice.gov.uk'
