apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: laa-civil-manage-api-dev-service-monitor
spec:
  selector:
    matchLabels:
      app: laa-civil-manage-api
  endpoints:
    - port: http
      interval: 15s