apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: chaps-dotnet-production-cert
  namespace: chaps-dotnet-production
spec:
  secretName: chaps-dotnet-production-cert-secret
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames:
  - correspondence-handling-and-processing.service.justice.gov.uk