kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: jaiu-docket-dev-admin
  namespace: jaiu-docket-dev
subjects:
  - kind: Group
    name: "github:justice-ai-unit"
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
