---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: developerportal.service.justice.gov.uk
  namespace: developer-portal-prod
spec:
  secretName: developerportal-prod-cert
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames:
  - developerportal.service.justice.gov.uk
