{
 "title": "Peoplefinder Production Dashboard",
 "time": { "from": "now-2d", "to": "now" },
 "panels": [
  { "title": "Panel Title", "type": "table-old", "gridPos": { "h": 6, "w": 9, "x": 0, "y": 0 } },
  {
   "title": "Currently Active",
   "type": "table-old",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "max(kube_deployment_status_replicas_available{namespace=\"peoplefinder-production\"}) by (deployment)"
    },
    {
     "expr": "max(kube_deployment_spec_replicas{namespace=\"peoplefinder-production\"}) by (deployment)"
    }
   ]
  },
  { "title": "Kube Cluster (Pod/Container)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Restarts(2m) by container",
   "type": "graph",
   "gridPos": { "h": 8, "w": 22, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kube_pod_container_status_restarts_total{namespace=\"peoplefinder-production\", container=\"jobs\"}[2m]))",
     "legendFormat": "Jobs container"
    },
    {
     "expr": "sum(rate(kube_pod_container_status_restarts_total{namespace=\"peoplefinder-production\", container=\"webapp\"}[2m]))",
     "legendFormat": "Webapp container"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 22, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "avg by (container)(rate(container_cpu_usage_seconds_total{namespace=\"peoplefinder-production\"}[5m]))",
     "legendFormat": "{{ container }}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 22, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg by (container)(container_memory_usage_bytes{namespace=\"peoplefinder-production\"})",
     "legendFormat": "{{ container}}"
    },
    {
     "expr": "avg(kube_pod_container_resource_requests_memory_bytes{namespace=\"peoplefinder-production\"})",
     "legendFormat": "Request limit"
    },
    {
     "expr": "avg(kube_pod_container_resource_limits_memory_bytes{namespace=\"peoplefinder-production\"})",
     "legendFormat": "hard limit"
    }
   ]
  },
  {
   "title": "Ingress Controller Requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_requests{exported_namespace = \"peoplefinder-production\", ingress = \"peoplefinder-ingress\"}[5m])) by(status)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Average Request Duration",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 11, "y": 31 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(rate(nginx_ingress_controller_request_duration_seconds_sum{exported_namespace = \"peoplefinder-production\", ingress = \"peoplefinder-ingress\"}[5m]) / rate(nginx_ingress_controller_request_duration_seconds_count{exported_namespace = \"peoplefinder-production\", ingress = \"peoplefinder-ingress\"}[5m]) > 0)",
     "legendFormat": "Average Request Duration"
    }
   ]
  },
  { "title": "AWS RDS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "CPUUtilization/ReplicaLag",
   "type": "graph",
   "gridPos": { "h": 7, "w": 22, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "dimensions": {
      "DBInstanceIdentifier": "cloud-platform-0f0b5ea8e809e380"
     },
     "metricName": "CPUUtilization",
     "namespace": "AWS/RDS",
     "region": "default",
     "statistics": [ "Average" ]
    },
    {
     "dimensions": {
      "DBInstanceIdentifier": "cloud-platform-0f0b5ea8e809e380"
     },
     "metricName": "ReplicaLag",
     "namespace": "AWS/RDS",
     "region": "default",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "DatabaseConnections/DiskQueueDepth",
   "type": "graph",
   "gridPos": { "h": 8, "w": 22, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dimensions": {
      "DBInstanceIdentifier": "cloud-platform-0f0b5ea8e809e380"
     },
     "metricName": "DatabaseConnections",
     "namespace": "AWS/RDS",
     "region": "default",
     "statistics": [ "Average" ]
    },
    {
     "dimensions": {
      "DBInstanceIdentifier": "cloud-platform-0f0b5ea8e809e380"
     },
     "metricName": "DiskQueueDepth",
     "namespace": "AWS/RDS",
     "region": "default",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "ReadIOPS/WriteIOPS",
   "type": "graph",
   "gridPos": { "h": 9, "w": 22, "x": 0, "y": 55 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dimensions": {
      "DBInstanceIdentifier": "cloud-platform-0f0b5ea8e809e380"
     },
     "metricName": "ReadIOPS",
     "namespace": "AWS/RDS",
     "region": "default",
     "statistics": [ "Average" ]
    },
    {
     "dimensions": {
      "DBInstanceIdentifier": "cloud-platform-0f0b5ea8e809e380"
     },
     "metricName": "WriteIOPS",
     "namespace": "AWS/RDS",
     "region": "default",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "ReadLatency/WriteLatency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 22, "x": 0, "y": 64 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "dimensions": {
      "DBInstanceIdentifier": "cloud-platform-0f0b5ea8e809e380"
     },
     "metricName": "ReadLatency",
     "namespace": "AWS/RDS",
     "region": "default",
     "statistics": [ "Average" ]
    },
    {
     "dimensions": {
      "DBInstanceIdentifier": "cloud-platform-0f0b5ea8e809e380"
     },
     "metricName": "WriteLatency",
     "namespace": "AWS/RDS",
     "region": "default",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "ReadThroughput/WriteThroughput",
   "type": "graph",
   "gridPos": { "h": 8, "w": 22, "x": 0, "y": 71 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "dimensions": {
      "DBInstanceIdentifier": "cloud-platform-0f0b5ea8e809e380"
     },
     "metricName": "ReadThroughput",
     "namespace": "AWS/RDS",
     "region": "default",
     "statistics": [ "Average" ]
    },
    {
     "dimensions": {
      "DBInstanceIdentifier": "cloud-platform-0f0b5ea8e809e380"
     },
     "metricName": "WriteThroughput",
     "namespace": "AWS/RDS",
     "region": "default",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "NetworkReceiveThroughput/NetworkTransmitThroughput",
   "type": "graph",
   "gridPos": { "h": 9, "w": 22, "x": 0, "y": 79 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "dimensions": {
      "DBInstanceIdentifier": "cloud-platform-0f0b5ea8e809e380"
     },
     "metricName": "NetworkReceiveThroughput",
     "namespace": "AWS/RDS",
     "region": "default",
     "statistics": [ "Average" ]
    },
    {
     "dimensions": {
      "DBInstanceIdentifier": "cloud-platform-0f0b5ea8e809e380"
     },
     "metricName": "NetworkTransmitThroughput",
     "namespace": "AWS/RDS",
     "region": "default",
     "statistics": [ "Average" ]
    }
   ]
  }
 ]
}