{
 "title": "Peoplefinder Production Dashboard",
 "tags": [ "cdpt" ],
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "DBInstanceIdentifier",
    "query": "cloud-platform-0f0b5ea8e809e380"
   },
   {
    "name": "bucket",
    "query": "cloud-platform-df1338a7e64a4768a6cfac6c7cbeccde"
   },
   { "name": "namespace", "query": "peoplefinder-production" }
  ]
 },
 "panels": [
  { "title": "Pods & Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Currently Active Pods",
   "type": "table",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "max(kube_deployment_status_replicas_available{namespace=\"${namespace}\"}) by (deployment)"
    },
    {
     "expr": "max(kube_deployment_spec_replicas{namespace=\"${namespace}\"}) by (deployment)"
    }
   ]
  },
  {
   "title": "HTTP Status Codes",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(nginx_ingress_controller_requests{exported_namespace = \"${namespace}\"}[$__interval])) by (status)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Average Request Duration",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(rate(nginx_ingress_controller_request_duration_seconds_sum{exported_namespace = \"${namespace}\"}[$__interval]) / rate(nginx_ingress_controller_request_duration_seconds_count{exported_namespace = \"${namespace}\"}[$__interval]) > 0)",
     "legendFormat": "Requests"
    }
   ]
  },
  { "title": "Resource Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (pod)(rate(container_cpu_usage_seconds_total{namespace='${namespace}'}[$__interval]))",
     "legendFormat": "Pod: {{pod}}"
    },
    {
     "expr": "avg(kube_pod_container_resource_requests_cpu_cores{namespace='${namespace}'})  ",
     "legendFormat": "Requested (soft limit)"
    },
    {
     "expr": "avg(kube_pod_container_resource_limits_cpu_cores{namespace='${namespace}'})",
     "legendFormat": "Limit (Hard Limit)"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(pod)(container_memory_usage_bytes{namespace='${namespace}'})",
     "legendFormat": "Pod: {{pod}}"
    },
    {
     "expr": "avg(kube_pod_container_resource_requests_memory_bytes{namespace='${namespace}'})",
     "legendFormat": "Requested (soft limit)"
    },
    {
     "expr": "avg(kube_pod_container_resource_limits_memory_bytes{namespace='${namespace}n'})",
     "legendFormat": "Limit (Hard Limit)"
    }
   ]
  },
  { "title": "AWS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "RDS DatabaseConnections/DiskQueueDepth",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "application": { "filter": "" },
     "dimensions": { "DBInstanceIdentifier": "$DBInstanceIdentifier" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "DatabaseConnections",
     "namespace": "AWS/RDS",
     "options": {
      "showDisabledItems": false
     },
     "region": "default",
     "statistic": "Average"
    },
    {
     "application": { "filter": "" },
     "dimensions": { "DBInstanceIdentifier": "$DBInstanceIdentifier" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "DiskQueueDepth",
     "namespace": "AWS/RDS",
     "options": {
      "showDisabledItems": false
     },
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "BucketSizeBytes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "dimensions": { "BucketName": "$bucket", "StorageType": "StandardStorage" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "BucketSizeBytes",
     "namespace": "AWS/S3",
     "options": {
      "showDisabledItems": false
     },
     "region": "default",
     "statistic": "Average"
    }
   ]
  }
 ]
}