apiVersion: v1
kind: Namespace
metadata:
  name: vscode-marketplace
  labels:
    cloud-platform.justice.gov.uk/environment-name: "production"
    cloud-platform.justice.gov.uk/is-production: "true"
    pod-security.kubernetes.io/enforce: restricted
  annotations:
    cloud-platform.justice.gov.uk/application: "VS Code Private Marketplace"
    cloud-platform.justice.gov.uk/business-unit: "Platforms"
    cloud-platform.justice.gov.uk/owner: "Dean Longstaff: dean.longstaff@justice.gov.uk"
    cloud-platform.justice.gov.uk/source-code: "https://github.com/ministryofjustice/vscode-marketplace"
    cloud-platform.justice.gov.uk/team-name: "vscode-marketplace-admins"
    cloud-platform.justice.gov.uk/slack-channel: "#vscode-extensions"
    cloud-platform.justice.gov.uk/review-after: "2026-12-01"
