apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cwa-schedule-uploader-ui-cert
  namespace: laa-cwa-schedule-uploader-prod
spec:
  secretName: cwa-schedule-uploader-ui-cert
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames:
    - cwa-schedule-uploader-ui.apps.live.cloud-platform.service.justice.gov.uk