kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: mandatory-drug-testing-dev-admin
  namespace: mandatory-drug-testing-dev
subjects:
  - kind: Group
    name: "github:hmpps-mandatory-drug-testing"
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
