---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: hmpps-mandatory-drug-testing-api-cert
  namespace: mandatory-drug-testing-dev
spec:
  secretName: hmpps-mandatory-drug-testing-api-cert
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames:
    - mandatory-drug-testing-api-dev.hmpps.service.justice.gov.uk
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: hmpps-mandatory-drug-testing-ui-cert
  namespace: mandatory-drug-testing-dev
spec:
  secretName: hmpps-mandatory-drug-testing-ui-cert
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames:
    - mandatory-drug-testing-ui-dev.hmpps.service.justice.gov.uk
