# generated by https://github.com/ministryofjustice/money-to-prisoners-deploy
module "irsa-api" {
  source = "github.com/ministryofjustice/cloud-platform-terraform-irsa?ref=2.0.0"

  business_unit          = var.business_unit
  team_name              = var.team_name
  application            = var.application
  is_production          = var.is_production
  namespace              = var.namespace
  environment_name       = var.environment
  infrastructure_support = var.infrastructure_support

  eks_cluster_name     = var.eks_cluster_name
  service_account_name = "api"
  role_policy_arns = {
    policy = aws_iam_policy.api.arn,
  }
}

resource "aws_iam_policy" "api" {
  name   = "${var.namespace}-api"
  policy = data.aws_iam_policy_document.api.json
  # NB: IAM policy name must be unique within Cloud Platform

  tags = {
    business-unit          = var.business_unit
    team_name              = var.team_name
    application            = var.application
    is-production          = var.is_production
    namespace              = var.namespace
    environment-name       = var.environment
    owner                  = var.team_name
    infrastructure-support = var.infrastructure_support
  }
}

data "aws_iam_policy_document" "api" {
  source_policy_documents = [
    data.aws_iam_policy_document.s3-read.json,
  ]

  # Allows direct put access to subpath of terraformed S3 bucket for mimicking Analytical Platform
  statement {
    actions = [
      "s3:PutObject",
      "s3:PutObjectAcl",
    ]
    resources = [
      "${module.s3.bucket_arn}/faux-ap/*",
    ]
  }
}

resource "kubernetes_secret" "irsa-api" {
  metadata {
    name      = "irsa-api"
    namespace = var.namespace
  }

  data = {
    role            = module.irsa-api.role_name
    role_arn        = module.irsa-api.role_arn
    service_account = module.irsa-api.service_account.name
  }
}
