# generated by https://github.com/ministryofjustice/money-to-prisoners-deploy
variable "vpc_name" {}
variable "eks_cluster_name" {}
variable "kubernetes_cluster" {}

variable "business_unit" {
  default = "HMPPS"
}

variable "team_name" {
  default = "prisoner-money"
}

variable "infrastructure_support" {
  default = "money-to-prisoners@digital.justice.gov.uk"
}

variable "application" {
  default = "money-to-prisoners"
}

variable "environment" {
  default = "test"
}

variable "is_production" {
  default = "false"
}

variable "namespace" {
  default = "money-to-prisoners-test"
}

variable "github_owner" {
  default = "ministryofjustice"
}

variable "github_token" {
  default = ""
}
