---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: hmpps-prisoner-monies-send-money-cert
  namespace: hmpps-prisoner-monies-dev
spec:
  secretName: hmpps-prisoner-monies-send-money-cert
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames:
    - prisoner-monies-send-money-dev.hmpps.service.justice.gov.uk
    - prisoner-monies-email-service-api-dev.hmpps.service.justice.gov.uk
