apiVersion: v1
kind: ResourceQuota
metadata:
  name: namespace-quota
  namespace: pfl-analytics-prod
spec:
  hard:
    pods: "10"

# This ResourceQuota limits the number of pods that can be created in the namespace to 10.