{
 "title": "Prisoner Content Hub Production",
 "tags": [ "prisoner-content-hub" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Average Requests/s",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Requests" }
   ],
   "targets": [
    {
     "expr": "avg(sum by (ingress) (rate(nginx_ingress_controller_requests{exported_namespace=\"prisoner-content-hub-production\"}[5m]))) by (ingress)",
     "legendFormat": "{{ingress}}"
    }
   ]
  },
  {
   "title": "Replication Count",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "max(kube_deployment_status_replicas{namespace=\"prisoner-content-hub-production\"}) by (deployment)",
     "legendFormat": "{{deployment}}-actual"
    },
    {
     "expr": "max(kube_deployment_spec_replicas{namespace=\"prisoner-content-hub-production\"}) by (deployment)",
     "legendFormat": "{{deployment}}-desired"
    }
   ]
  },
  {
   "title": "Average Request Time (s)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(rate(nginx_ingress_controller_request_duration_seconds_sum{exported_namespace=\"prisoner-content-hub-production\"}[5m]) / rate(nginx_ingress_controller_request_duration_seconds_count{exported_namespace=\"prisoner-content-hub-production\"}[5m]) > 0) by (ingress)\n",
     "legendFormat": "{{ingress}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short", "label": "CPU Time (s)" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"prisoner-content-hub-production\",container!=\"POD\",container!=\"\"}[5m])) by (container)",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Average Bytes Sent",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short", "label": "Bytes" }
   ],
   "targets": [
    {
     "expr": "avg(sum by (ingress) (rate(nginx_ingress_controller_bytes_sent_sum{exported_namespace=\"prisoner-content-hub-production\"}[5m]))) by (ingress)",
     "legendFormat": "{{ingress}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short", "label": "Memory Usage (MB)" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_memory_usage_bytes{namespace=\"prisoner-content-hub-production\",container!=\"POD\",container!=\"\"}[5m]) / 1024 / 1024) by (container)",
     "legendFormat": "{{container}}"
    }
   ]
  }
 ]
}
{
 "title": "Prisoner Content Hub ElasticSearch",
 "tags": [ "prisoner-content-hub" ],
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Cluster status",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "aws_es_cluster_status_green_average{domain_name=\"pfs-production-hub-search\"}",
     "legendFormat": "{{domain_name}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Memory Usage" }
   ],
   "targets": [
    {
     "expr": "aws_es_jvmmemory_pressure_average{domain_name=\"pfs-production-hub-search\"}",
     "legendFormat": "{{domain_name}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short", "label": "CPU Usage" }
   ],
   "targets": [
    {
     "expr": "aws_es_cpuutilization_average{domain_name=\"pfs-production-hub-search\"}",
     "legendFormat": "{{domain_name}}"
    }
   ]
  },
  {
   "title": "Free storage space",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "decmbytes", "label": "Free storage space (MB)" }
   ],
   "targets": [
    {
     "expr": "aws_es_free_storage_space_average{domain_name=\"pfs-production-hub-search\"}",
     "legendFormat": "{{domain_name}}"
    }
   ]
  }
 ]
}