kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: address-matcher-api-admin
  namespace: address-matcher-api
subjects:
  - kind: Group
    name: "github:mlops"
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
