apiVersion: v1
kind: Namespace
metadata:
  name: "ims-assisted-sanitisation-monitoring-dev"
  labels:
    cloud-platform.justice.gov.uk/is-production: "false"
    cloud-platform.justice.gov.uk/environment-name: "development"
    pod-security.kubernetes.io/enforce: restricted
  annotations:
    cloud-platform.justice.gov.uk/business-unit: "HQ"
    cloud-platform.justice.gov.uk/slack-channel: "intel-digital-data-science"
    cloud-platform.justice.gov.uk/application: "IMS Assisted Sanitisation Monitoring Service"
    cloud-platform.justice.gov.uk/owner: "Prison Data Science and AI: intelappsupport-gg@justice.gov.uk"
    cloud-platform.justice.gov.uk/source-code: "https://github.com/ministryofjustice/ims-assisted-sanitisation-monitoring"
    cloud-platform.justice.gov.uk/team-name: "prisons-intel-ds"
    cloud-platform.justice.gov.uk/review-after: ""