apiVersion: v1
kind: Namespace
metadata:
  name: "find-a-technology-service-dev"
  labels:
    cloud-platform.justice.gov.uk/is-production: "false"
    cloud-platform.justice.gov.uk/environment-name: "development"
    pod-security.kubernetes.io/enforce: restricted
  annotations:
    cloud-platform.justice.gov.uk/business-unit: "Technology Services"
    cloud-platform.justice.gov.uk/slack-channel: "ask-find-a-technology-service"
    cloud-platform.justice.gov.uk/application: "Find a Technology Service"
    cloud-platform.justice.gov.uk/owner: "Technology Services: eucstechnicalarchitects@justice.gov.uk"
    cloud-platform.justice.gov.uk/source-code: "https://github.com/ministryofjustice/find-a-technology-service"
    cloud-platform.justice.gov.uk/team-name: "find-a-technology-service-maintainers"
    cloud-platform.justice.gov.uk/review-after: ""
