apiVersion: v1
kind: Namespace
metadata:
  name: "laa-record-controlled-work-datastore-uat"
  labels:
    cloud-platform.justice.gov.uk/is-production: "false"
    cloud-platform.justice.gov.uk/environment-name: "UAT"
    pod-security.kubernetes.io/enforce: restricted
  annotations:
    cloud-platform.justice.gov.uk/business-unit: "LAA"
    cloud-platform.justice.gov.uk/slack-channel: "meansandmatch-internal-team-chat"
    cloud-platform.justice.gov.uk/application: "Record Controlled Work Datastore"
    cloud-platform.justice.gov.uk/owner: "Means and Match: rcw-datastore-team@justice.gov.uk"
    cloud-platform.justice.gov.uk/source-code: "https://github.com/ministryofjustice/laa-record-controlled-work-datastore"
    cloud-platform.justice.gov.uk/team-name: "rcw-datastore"
    cloud-platform.justice.gov.uk/review-after: ""
