SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

CREATE SCHEMA public;

SET default_tablespace = '';

CREATE TABLE public.fees (
    id integer NOT NULL,
    startdate timestamp(0) without time zone,
    fees_paper character varying(50),
    fees_oral character varying(50)
);

ALTER TABLE public.fees ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.fees_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.formsdata (
    id integer NOT NULL,
    securitytoken character varying(50),
    submissionurn character varying(50),
    paymenturn character varying(50),
    aggregatedurn character varying(50),
    formname character varying(50),
    amount integer,
    formtitle character varying(50),
    transactionstatus character varying(50) DEFAULT 'Not Known'::character varying,
    count integer DEFAULT 0,
    status character varying(50) DEFAULT 'In Progress'::character varying
);

ALTER TABLE public.formsdata ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.formsdata_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.iaft1 (
    id integer NOT NULL,
    hearing_type character varying(50),
    qa_sponsor character varying(50),
    qa_rep character varying(50),
    qa_witness character varying(50),
    qb_lsc character varying(50),
    qb_lar character varying(50),
    family_member character varying(50),
    qc_name1 character varying(70),
    qc_relationship1 character varying(50),
    qc_prn1 character varying(50),
    qc_name2 character varying(70),
    qc_relationship2 character varying(50),
    qc_prn2 character varying(50),
    qc_name3 character varying(70),
    qc_relationship3 character varying(50),
    qc_prn3 character varying(50),
    qc_name4 character varying(70),
    qc_relationship4 character varying(50),
    qc_prn4 character varying(50),
    s1a character varying(50),
    s1b character varying(50),
    s1c character varying(50),
    s1d timestamp(3) without time zone,
    s1e character varying(50),
    s1f_addr1 character varying(50),
    s1f_addr2 character varying(50),
    s1f_addr3 character varying(50),
    s1f_addr4 character varying(50),
    s1f_postcode character varying(50),
    s1g character varying(50),
    s1h character varying(50),
    s1i_yourself character varying(50),
    s1i_witness character varying(50),
    s1i_representative character varying(50),
    s1j character varying(50),
    s1j_who character varying(70),
    s1j_language character varying(50),
    s1j_dialect character varying(50),
    s1k character varying(1000),
    s1l character varying(50),
    s1m character varying(50),
    s1n timestamp(3) without time zone,
    s1o character varying(50),
    s1p timestamp(3) without time zone,
    s1q character varying(50),
    s2a character varying(50),
    s2b character varying(50),
    s2c character varying(50),
    s2d_post character varying(50),
    s2d_fax character varying(50),
    s2d_courier character varying(50),
    s2d_other character varying(50),
    s2e timestamp(3) without time zone,
    s2f character varying(50),
    s3a character varying(8000),
    s3b character varying(8000),
    s3c character varying(8000),
    s3d_1 character varying(8000),
    s3d_2 character varying(8000),
    s3d_3 character varying(8000),
    s3d_4 character varying(8000),
    s3d_5 character varying(8000),
    s3d_6 character varying(8000),
    s3d_7 character varying(8000),
    s3d_8 character varying(8000),
    s3d_additional character varying(8000),
    s3e character varying(8000),
    s3e_date1 timestamp(3) without time zone,
    s3e_appealno1 character varying(50),
    s3e_date2 timestamp(3) without time zone,
    s3e_appealno2 character varying(50),
    s3e_date3 timestamp(3) without time zone,
    s3e_appealno3 character varying(50),
    s3f character varying(50),
    s4_signature character varying(50),
    s4_date timestamp(3) without time zone,
    s5a character varying(500),
    s5b character varying(500),
    s5c_addr1 character varying(50),
    s5c_addr2 character varying(50),
    s5c_addr3 character varying(50),
    s5c_addr4 character varying(50),
    s5c_postcode character varying(50),
    s5d character varying(50),
    s5e character varying(50),
    s5f character varying(50),
    s5g character varying(50),
    s5h character varying(50),
    s5i character varying(50),
    s5j character varying(50),
    securitytoken character varying(50),
    s5b_other character varying(50),
    rep_sign character varying(50),
    date_added timestamp(0) without time zone,
    s4_declaration character varying(50),
    s2i timestamp(3) without time zone,
    s1f_email character varying(250)
);

ALTER TABLE public.iaft1 ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.iaft1_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.iaft2 (
    id integer NOT NULL,
    hearing_type character varying(50),
    qa_sponsor character varying(50),
    qa_rep character varying(50),
    qa_witness character varying(50),
    qb_lsc character varying(50),
    qb_lar character varying(50),
    family_member character varying(50),
    qc_name1 character varying(70),
    qc_relationship1 character varying(50),
    qc_prn1 character varying(50),
    qc_name2 character varying(70),
    qc_relationship2 character varying(50),
    qc_prn2 character varying(50),
    qc_name3 character varying(70),
    qc_relationship3 character varying(50),
    qc_prn3 character varying(50),
    qc_name4 character varying(70),
    qc_relationship4 character varying(50),
    qc_prn4 character varying(50),
    s1a character varying(35),
    s1b character varying(35),
    s1c character varying(50),
    s1d timestamp(3) without time zone,
    s1e character varying(50),
    s1f_addr1 character varying(50),
    s1f_addr2 character varying(50),
    s1f_addr3 character varying(50),
    s1f_addr4 character varying(50),
    s1f_postcode character varying(50),
    s1g character varying(50),
    s1h character varying(50),
    s1i_yourself character varying(50),
    s1i_witness character varying(50),
    s1i_representative character varying(50),
    s1j character varying(50),
    s1j_who character varying(70),
    s1j_language character varying(50),
    s1j_dialect character varying(50),
    s1k character varying(1000),
    s1l character varying(50),
    s1m character varying(50),
    s1n timestamp(3) without time zone,
    s1o character varying(50),
    s1p timestamp(3) without time zone,
    s1q character varying(50),
    s2a character varying(50),
    s2b character varying(50),
    s2c character varying(50),
    s2d_post character varying(50),
    s2d_fax character varying(50),
    s2d_courier character varying(50),
    s2d_other character varying(50),
    s2e timestamp(3) without time zone,
    s2f character varying(50),
    s3a character varying(8000),
    s3b character varying(8000),
    s3c character varying(8000),
    s3d_1 character varying(8000),
    s3d_2 character varying(8000),
    s3d_3 character varying(8000),
    s3d_4 character varying(8000),
    s3d_5 character varying(8000),
    s3d_6 character varying(8000),
    s3d_7 character varying(8000),
    s3d_8 character varying(8000),
    s3d_additional character varying(8000),
    s3e character varying(8000),
    s3e_date1 timestamp(3) without time zone,
    s3e_appealno1 character varying(50),
    s3e_date2 timestamp(3) without time zone,
    s3e_appealno2 character varying(50),
    s3e_date3 timestamp(3) without time zone,
    s3e_appealno3 character varying(50),
    s3f character varying(50),
    s4_signature character varying(50),
    s4_date timestamp(3) without time zone,
    s5a character varying(500),
    s5b character varying(500),
    s5c_addr1 character varying(50),
    s5c_addr2 character varying(50),
    s5c_addr3 character varying(50),
    s5c_addr4 character varying(50),
    s5c_postcode character varying(50),
    s5d character varying(50),
    s5e character varying(50),
    s5f character varying(50),
    s5g character varying(50),
    s5h character varying(50),
    s5i character varying(50),
    s5j character varying(50),
    securitytoken character varying(50),
    s5b_other character varying(50),
    rep_sign character varying(50),
    s6a character varying(35),
    s6b character varying(35),
    s6c character varying(50),
    s6d_addr1 character varying(50),
    s6d_addr2 character varying(50),
    s6d_addr3 character varying(50),
    s6d_addr4 character varying(50),
    s6d_postcode character varying(50),
    s6e character varying(50),
    s6f character varying(50),
    s6_auth character varying(50),
    date_added timestamp(3) without time zone,
    have_rep character varying(50),
    have_sponsor character varying(50),
    other_rep character varying(100),
    s4_declaration character varying(50),
    s2i timestamp(3) without time zone,
    s1f_email character varying(250)
);

ALTER TABLE public.iaft2 ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.iaft2_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.iaft3 (
    id integer NOT NULL,
    hearing_type character varying(50),
    qa_sponsor character varying(50),
    qa_rep character varying(50),
    qa_witness character varying(50),
    qb_lsc character varying(50),
    qb_lar character varying(50),
    family_member character varying(50),
    qc_name1 character varying(70),
    qc_relationship1 character varying(50),
    qc_prn1 character varying(50),
    qc_name2 character varying(70),
    qc_relationship2 character varying(50),
    qc_prn2 character varying(50),
    qc_name3 character varying(70),
    qc_relationship3 character varying(50),
    qc_prn3 character varying(50),
    qc_name4 character varying(70),
    qc_relationship4 character varying(50),
    qc_prn4 character varying(50),
    s1a character varying(35),
    s1b character varying(35),
    s1c character varying(50),
    s1d timestamp(3) without time zone,
    s1e character varying(50),
    s1f_addr1 character varying(50),
    s1f_addr2 character varying(50),
    s1f_addr3 character varying(50),
    s1f_addr4 character varying(50),
    s1f_postcode character varying(50),
    s1g character varying(50),
    s1h character varying(50),
    s1i_yourself character varying(50),
    s1i_witness character varying(50),
    s1i_representative character varying(50),
    s1j character varying(50),
    s1j_who character varying(70),
    s1j_language character varying(50),
    s1j_dialect character varying(50),
    s1k character varying(1000),
    s1l character varying(50),
    s1m character varying(50),
    s1n timestamp(3) without time zone,
    s1o character varying(50),
    s1p timestamp(3) without time zone,
    s1q character varying(50),
    s2a character varying(50),
    s2b character varying(50),
    s2c character varying(50),
    s2d_post character varying(50),
    s2d_fax character varying(50),
    s2d_courier character varying(50),
    s2d_other character varying(50),
    s2e timestamp(3) without time zone,
    s2f timestamp(3) without time zone,
    s3a character varying(8000),
    s3b character varying(8000),
    s3c character varying(8000),
    s3d_1 character varying(8000),
    s3d_2 character varying(8000),
    s3d_3 character varying(8000),
    s3d_4 character varying(8000),
    s3d_5 character varying(8000),
    s3d_6 character varying(8000),
    s3d_7 character varying(8000),
    s3d_8 character varying(8000),
    s3d_additional character varying(8000),
    s3e character varying(8000),
    s3e_date1 timestamp(3) without time zone,
    s3e_appealno1 character varying(50),
    s3e_date2 timestamp(3) without time zone,
    s3e_appealno2 character varying(50),
    s3e_date3 timestamp(3) without time zone,
    s3e_appealno3 character varying(50),
    s3f character varying(50),
    s4_signature character varying(50),
    s4_date timestamp(3) without time zone,
    s5a character varying(500),
    s5b character varying(500),
    s5c_addr1 character varying(50),
    s5c_addr2 character varying(50),
    s5c_addr3 character varying(50),
    s5c_addr4 character varying(50),
    s5c_postcode character varying(50),
    s5d character varying(50),
    s5e character varying(50),
    s5f character varying(50),
    s5g character varying(50),
    s5h character varying(50),
    s5i character varying(50),
    s5j character varying(50),
    securitytoken character varying(50),
    s5b_other character varying(50),
    rep_sign character varying(50),
    date_added timestamp(0) without time zone,
    s4_declaration character varying(50),
    s2i timestamp(3) without time zone,
    s1f_email character varying(250)
);

ALTER TABLE public.iaft3 ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.iaft3_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


CREATE TABLE public.iaft5 (
    id integer NOT NULL,
    hearing_type character varying(50),
    qa_sponsor character varying(50),
    qa_rep character varying(50),
    qa_witness character varying(50),
    qb_lsc character varying(50),
    qb_lar character varying(50),
    family_member character varying(50),
    qc_name1 character varying(70),
    qc_relationship1 character varying(50),
    qc_prn1 character varying(50),
    qc_name2 character varying(70),
    qc_relationship2 character varying(50),
    qc_prn2 character varying(50),
    qc_name3 character varying(70),
    qc_relationship3 character varying(50),
    qc_prn3 character varying(50),
    qc_name4 character varying(70),
    qc_relationship4 character varying(50),
    qc_prn4 character varying(50),
    s1a character varying(50),
    s1b character varying(50),
    s1c character varying(50),
    s1d timestamp(3) without time zone,
    s1e character varying(50),
    s1f_addr1 character varying(50),
    s1f_addr2 character varying(50),
    s1f_addr3 character varying(50),
    s1f_addr4 character varying(50),
    s1f_postcode character varying(50),
    s1g character varying(50),
    s1h character varying(50),
    s1i_yourself character varying(50),
    s1i_witness character varying(50),
    s1i_representative character varying(50),
    s1j character varying(50),
    s1j_who character varying(70),
    s1j_language character varying(50),
    s1j_dialect character varying(50),
    s1k character varying(1000),
    s1l character varying(50),
    s1m character varying(50),
    s1n timestamp(3) without time zone,
    s1o character varying(50),
    s1p timestamp(3) without time zone,
    s1q character varying(50),
    s2a character varying(50),
    s2b character varying(50),
    s2c character varying(50),
    s2d_post character varying(50),
    s2d_fax character varying(50),
    s2d_courier character varying(50),
    s2d_other character varying(50),
    s2e timestamp(3) without time zone,
    s2f character varying(50),
    s3a character varying(8000),
    s3b character varying(8000),
    s3c character varying(8000),
    s3d_1 character varying(8000),
    s3d_2 character varying(8000),
    s3d_3 character varying(8000),
    s3d_4 character varying(8000),
    s3d_5 character varying(8000),
    s3d_6 character varying(8000),
    s3d_7 character varying(8000),
    s3d_8 character varying(8000),
    s3d_additional character varying(8000),
    s3e character varying(8000),
    s3e_date1 timestamp(3) without time zone,
    s3e_appealno1 character varying(50),
    s3e_date2 timestamp(3) without time zone,
    s3e_appealno2 character varying(50),
    s3e_date3 timestamp(3) without time zone,
    s3e_appealno3 character varying(50),
    s3f character varying(50),
    s4_signature character varying(50),
    s4_date timestamp(3) without time zone,
    s5a character varying(500),
    s5b character varying(500),
    s5c_addr1 character varying(50),
    s5c_addr2 character varying(50),
    s5c_addr3 character varying(50),
    s5c_addr4 character varying(50),
    s5c_postcode character varying(50),
    s5d character varying(50),
    s5e character varying(50),
    s5f character varying(50),
    s5g character varying(50),
    s5h character varying(50),
    s5i character varying(50),
    s5j character varying(50),
    securitytoken character varying(50),
    s5b_other character varying(50),
    rep_sign character varying(50),
    date_added timestamp(0) without time zone,
    s4_declaration character varying(50),
    s2i timestamp(3) without time zone,
    s1f_email character varying(250),
    s2hoan character varying(50),
    s2j timestamp(3) without time zone,
    s2k character varying(50),
    s3g character varying(3000)
);

ALTER TABLE public.iaft5 ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.iaft5_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.iaft6 (
    id integer NOT NULL,
    hearing_type character varying(50),
    qa_sponsor character varying(50),
    qa_rep character varying(50),
    qa_witness character varying(50),
    qb_lsc character varying(50),
    qb_lar character varying(50),
    family_member character varying(50),
    qc_name1 character varying(70),
    qc_relationship1 character varying(50),
    qc_prn1 character varying(50),
    qc_name2 character varying(70),
    qc_relationship2 character varying(50),
    qc_prn2 character varying(50),
    qc_name3 character varying(70),
    qc_relationship3 character varying(50),
    qc_prn3 character varying(50),
    qc_name4 character varying(70),
    qc_relationship4 character varying(50),
    qc_prn4 character varying(50),
    s1a character varying(35),
    s1b character varying(35),
    s1c character varying(50),
    s1d timestamp(3) without time zone,
    s1e character varying(50),
    s1f_addr1 character varying(50),
    s1f_addr2 character varying(50),
    s1f_addr3 character varying(50),
    s1f_addr4 character varying(50),
    s1f_postcode character varying(50),
    s1g character varying(50),
    s1h character varying(50),
    s1i_yourself character varying(50),
    s1i_witness character varying(50),
    s1i_representative character varying(50),
    s1j character varying(50),
    s1j_who character varying(70),
    s1j_language character varying(50),
    s1j_dialect character varying(50),
    s1k character varying(1000),
    s1l character varying(50),
    s1m character varying(50),
    s1n timestamp(3) without time zone,
    s1o character varying(50),
    s1p timestamp(3) without time zone,
    s1q character varying(50),
    s2a character varying(50),
    s2b character varying(50),
    s2c character varying(50),
    s2d_post character varying(50),
    s2d_fax character varying(50),
    s2d_courier character varying(50),
    s2d_other character varying(50),
    s2e timestamp(3) without time zone,
    s2f timestamp(0) without time zone,
    s3a character varying(8000),
    s3b character varying(8000),
    s3c character varying(8000),
    s3d_1 character varying(8000),
    s3d_2 character varying(8000),
    s3d_3 character varying(8000),
    s3d_4 character varying(8000),
    s3d_5 character varying(8000),
    s3d_6 character varying(8000),
    s3d_7 character varying(8000),
    s3d_8 character varying(8000),
    s3d_additional character varying(8000),
    s3e character varying(8000),
    s3e_date1 timestamp(3) without time zone,
    s3e_appealno1 character varying(50),
    s3e_date2 timestamp(3) without time zone,
    s3e_appealno2 character varying(50),
    s3e_date3 timestamp(3) without time zone,
    s3e_appealno3 character varying(50),
    s3f character varying(50),
    s4_signature character varying(50),
    s4_date timestamp(3) without time zone,
    s5a character varying(500),
    s5b character varying(500),
    s5c_addr1 character varying(50),
    s5c_addr2 character varying(50),
    s5c_addr3 character varying(50),
    s5c_addr4 character varying(50),
    s5c_postcode character varying(50),
    s5d character varying(50),
    s5e character varying(50),
    s5f character varying(50),
    s5g character varying(50),
    s5h character varying(50),
    s5i character varying(50),
    s5j character varying(50),
    securitytoken character varying(50),
    s5b_other character varying(50),
    rep_sign character varying(50),
    s6a character varying(35),
    s6b character varying(35),
    s6c character varying(50),
    s6d_addr1 character varying(50),
    s6d_addr2 character varying(50),
    s6d_addr3 character varying(50),
    s6d_addr4 character varying(50),
    s6d_postcode character varying(50),
    s6e character varying(50),
    s6f character varying(50),
    s6_auth character varying(50),
    date_added timestamp(3) without time zone,
    have_rep character varying(50),
    have_sponsor character varying(50),
    other_rep character varying(100),
    s4_declaration character varying(50),
    s2i timestamp(3) without time zone,
    s1f_email character varying(250)
);

ALTER TABLE public.iaft6 ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.iaft6_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.iaft7 (
    id integer NOT NULL,
    hearing_type character varying(50),
    qa_sponsor character varying(50),
    qa_rep character varying(50),
    qa_witness character varying(50),
    qb_lsc character varying(50),
    qb_lar character varying(50),
    family_member character varying(50),
    qc_name1 character varying(70),
    qc_relationship1 character varying(50),
    qc_prn1 character varying(50),
    qc_name2 character varying(70),
    qc_relationship2 character varying(50),
    qc_prn2 character varying(50),
    qc_name3 character varying(70),
    qc_relationship3 character varying(50),
    qc_prn3 character varying(50),
    qc_name4 character varying(70),
    qc_relationship4 character varying(50),
    qc_prn4 character varying(50),
    s1a character varying(50),
    s1b character varying(50),
    s1c character varying(50),
    s1d timestamp(3) without time zone,
    s1e character varying(50),
    s1f_addr1 character varying(50),
    s1f_addr2 character varying(50),
    s1f_addr3 character varying(50),
    s1f_addr4 character varying(50),
    s1f_postcode character varying(50),
    s1g character varying(50),
    s1h character varying(50),
    s1i_yourself character varying(50),
    s1i_witness character varying(50),
    s1i_representative character varying(50),
    s1j character varying(50),
    s1j_who character varying(70),
    s1j_language character varying(50),
    s1j_dialect character varying(50),
    s1k character varying(1000),
    s1l character varying(50),
    s1m character varying(50),
    s1n timestamp(3) without time zone,
    s1o character varying(50),
    s1p timestamp(3) without time zone,
    s1q character varying(50),
    s2a character varying(50),
    s2b character varying(50),
    s2c character varying(50),
    s2d_post character varying(50),
    s2d_fax character varying(50),
    s2d_courier character varying(50),
    s2d_other character varying(50),
    s2e timestamp(3) without time zone,
    s2f timestamp(3) without time zone,
    s3a character varying(8000),
    s3b character varying(8000),
    s3c character varying(8000),
    s3d_1 character varying(8000),
    s3d_2 character varying(8000),
    s3d_3 character varying(8000),
    s3d_4 character varying(8000),
    s3d_5 character varying(8000),
    s3d_6 character varying(8000),
    s3d_7 character varying(8000),
    s3d_8 character varying(8000),
    s3d_additional character varying(8000),
    s3e character varying(8000),
    s3e_date1 timestamp(3) without time zone,
    s3e_appealno1 character varying(50),
    s3e_date2 timestamp(3) without time zone,
    s3e_appealno2 character varying(50),
    s3e_date3 timestamp(3) without time zone,
    s3e_appealno3 character varying(50),
    s3f character varying(50),
    s4_signature character varying(50),
    s4_date timestamp(3) without time zone,
    s5a character varying(500),
    s5b character varying(500),
    s5c_addr1 character varying(50),
    s5c_addr2 character varying(50),
    s5c_addr3 character varying(50),
    s5c_addr4 character varying(50),
    s5c_postcode character varying(50),
    s5d character varying(50),
    s5e character varying(50),
    s5f character varying(50),
    s5g character varying(50),
    s5h character varying(50),
    s5i character varying(50),
    s5j character varying(50),
    securitytoken character varying(50),
    s5b_other character varying(50),
    rep_sign character varying(50),
    date_added timestamp(0) without time zone,
    s4_declaration character varying(50),
    s2i timestamp(3) without time zone,
    s1f_email character varying(250),
    s2hoan character varying(50),
    s2j timestamp(3) without time zone,
    s2k character varying(50),
    s3g character varying(3000)
);


ALTER TABLE public.iaft7 ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.iaft7_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.transaction_details (
    id integer NOT NULL,
    transactionstatus character varying(50) DEFAULT 'Not Known'::character varying,
    orderid character varying(50),
    type character varying(50),
    referencenumber character varying(50),
    sub_count integer,
    aggr_urn character varying(50),
    dateofpayment timestamp(0) without time zone
);

ALTER TABLE public.transaction_details ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.transaction_details_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.urn (
    id character varying(50)
);

COPY public.fees (id, startdate, fees_paper, fees_oral) FROM stdin;
4	2011-12-18 00:00:00	80	140
\.

COPY public.iaft1 (id, hearing_type, qa_sponsor, qa_rep, qa_witness, qb_lsc, qb_lar, family_member, qc_name1, qc_relationship1, qc_prn1, qc_name2, qc_relationship2, qc_prn2, qc_name3, qc_relationship3, qc_prn3, qc_name4, qc_relationship4, qc_prn4, s1a, s1b, s1c, s1d, s1e, s1f_addr1, s1f_addr2, s1f_addr3, s1f_addr4, s1f_postcode, s1g, s1h, s1i_yourself, s1i_witness, s1i_representative, s1j, s1j_who, s1j_language, s1j_dialect, s1k, s1l, s1m, s1n, s1o, s1p, s1q, s2a, s2b, s2c, s2d_post, s2d_fax, s2d_courier, s2d_other, s2e, s2f, s3a, s3b, s3c, s3d_1, s3d_2, s3d_3, s3d_4, s3d_5, s3d_6, s3d_7, s3d_8, s3d_additional, s3e, s3e_date1, s3e_appealno1, s3e_date2, s3e_appealno2, s3e_date3, s3e_appealno3, s3f, s4_signature, s4_date, s5a, s5b, s5c_addr1, s5c_addr2, s5c_addr3, s5c_addr4, s5c_postcode, s5d, s5e, s5f, s5g, s5h, s5i, s5j, securitytoken, s5b_other, rep_sign, date_added, s4_declaration, s2i, s1f_email) FROM stdin;
\.

--
-- TOC entry 4315 (class 0 OID 16421)
-- Dependencies: 213
-- Data for Name: IAFT2; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.iaft2 (id, hearing_type, qa_sponsor, qa_rep, qa_witness, qb_lsc, qb_lar, family_member, qc_name1, qc_relationship1, qc_prn1, qc_name2, qc_relationship2, qc_prn2, qc_name3, qc_relationship3, qc_prn3, qc_name4, qc_relationship4, qc_prn4, s1a, s1b, s1c, s1d, s1e, s1f_addr1, s1f_addr2, s1f_addr3, s1f_addr4, s1f_postcode, s1g, s1h, s1i_yourself, s1i_witness, s1i_representative, s1j, s1j_who, s1j_language, s1j_dialect, s1k, s1l, s1m, s1n, s1o, s1p, s1q, s2a, s2b, s2c, s2d_post, s2d_fax, s2d_courier, s2d_other, s2e, s2f, s3a, s3b, s3c, s3d_1, s3d_2, s3d_3, s3d_4, s3d_5, s3d_6, s3d_7, s3d_8, s3d_additional, s3e, s3e_date1, s3e_appealno1, s3e_date2, s3e_appealno2, s3e_date3, s3e_appealno3, s3f, s4_signature, s4_date, s5a, s5b, s5c_addr1, s5c_addr2, s5c_addr3, s5c_addr4, s5c_postcode, s5d, s5e, s5f, s5g, s5h, s5i, s5j, securitytoken, s5b_other, rep_sign, s6a, s6b, s6c, s6d_addr1, s6d_addr2, s6d_addr3, s6d_addr4, s6d_postcode, s6e, s6f, s6_auth, date_added, have_rep, have_sponsor, other_rep, s4_declaration, s2i, s1f_email) FROM stdin;
\.

--
-- TOC entry 4316 (class 0 OID 16713)
-- Dependencies: 214
-- Data for Name: IAFT3; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.iaft3 (id, hearing_type, qa_sponsor, qa_rep, qa_witness, qb_lsc, qb_lar, family_member, qc_name1, qc_relationship1, qc_prn1, qc_name2, qc_relationship2, qc_prn2, qc_name3, qc_relationship3, qc_prn3, qc_name4, qc_relationship4, qc_prn4, s1a, s1b, s1c, s1d, s1e, s1f_addr1, s1f_addr2, s1f_addr3, s1f_addr4, s1f_postcode, s1g, s1h, s1i_yourself, s1i_witness, s1i_representative, s1j, s1j_who, s1j_language, s1j_dialect, s1k, s1l, s1m, s1n, s1o, s1p, s1q, s2a, s2b, s2c, s2d_post, s2d_fax, s2d_courier, s2d_other, s2e, s2f, s3a, s3b, s3c, s3d_1, s3d_2, s3d_3, s3d_4, s3d_5, s3d_6, s3d_7, s3d_8, s3d_additional, s3e, s3e_date1, s3e_appealno1, s3e_date2, s3e_appealno2, s3e_date3, s3e_appealno3, s3f, s4_signature, s4_date, s5a, s5b, s5c_addr1, s5c_addr2, s5c_addr3, s5c_addr4, s5c_postcode, s5d, s5e, s5f, s5g, s5h, s5i, s5j, securitytoken, s5b_other, rep_sign, date_added, s4_declaration, s2i, s1f_email) FROM stdin;
\.


--
-- TOC entry 4317 (class 0 OID 16718)
-- Dependencies: 215
-- Data for Name: IAFT5; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.iaft5 (id, hearing_type, qa_sponsor, qa_rep, qa_witness, qb_lsc, qb_lar, family_member, qc_name1, qc_relationship1, qc_prn1, qc_name2, qc_relationship2, qc_prn2, qc_name3, qc_relationship3, qc_prn3, qc_name4, qc_relationship4, qc_prn4, s1a, s1b, s1c, s1d, s1e, s1f_addr1, s1f_addr2, s1f_addr3, s1f_addr4, s1f_postcode, s1g, s1h, s1i_yourself, s1i_witness, s1i_representative, s1j, s1j_who, s1j_language, s1j_dialect, s1k, s1l, s1m, s1n, s1o, s1p, s1q, s2a, s2b, s2c, s2d_post, s2d_fax, s2d_courier, s2d_other, s2e, s2f, s3a, s3b, s3c, s3d_1, s3d_2, s3d_3, s3d_4, s3d_5, s3d_6, s3d_7, s3d_8, s3d_additional, s3e, s3e_date1, s3e_appealno1, s3e_date2, s3e_appealno2, s3e_date3, s3e_appealno3, s3f, s4_signature, s4_date, s5a, s5b, s5c_addr1, s5c_addr2, s5c_addr3, s5c_addr4, s5c_postcode, s5d, s5e, s5f, s5g, s5h, s5i, s5j, securitytoken, s5b_other, rep_sign, date_added, s4_declaration, s2i, s1f_email, s2hoan, s2j, s2k, s3g) FROM stdin;
\.


--
-- TOC entry 4318 (class 0 OID 17471)
-- Dependencies: 216
-- Data for Name: IAFT6; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.iaft6 (id, hearing_type, qa_sponsor, qa_rep, qa_witness, qb_lsc, qb_lar, family_member, qc_name1, qc_relationship1, qc_prn1, qc_name2, qc_relationship2, qc_prn2, qc_name3, qc_relationship3, qc_prn3, qc_name4, qc_relationship4, qc_prn4, s1a, s1b, s1c, s1d, s1e, s1f_addr1, s1f_addr2, s1f_addr3, s1f_addr4, s1f_postcode, s1g, s1h, s1i_yourself, s1i_witness, s1i_representative, s1j, s1j_who, s1j_language, s1j_dialect, s1k, s1l, s1m, s1n, s1o, s1p, s1q, s2a, s2b, s2c, s2d_post, s2d_fax, s2d_courier, s2d_other, s2e, s2f, s3a, s3b, s3c, s3d_1, s3d_2, s3d_3, s3d_4, s3d_5, s3d_6, s3d_7, s3d_8, s3d_additional, s3e, s3e_date1, s3e_appealno1, s3e_date2, s3e_appealno2, s3e_date3, s3e_appealno3, s3f, s4_signature, s4_date, s5a, s5b, s5c_addr1, s5c_addr2, s5c_addr3, s5c_addr4, s5c_postcode, s5d, s5e, s5f, s5g, s5h, s5i, s5j, securitytoken, s5b_other, rep_sign, s6a, s6b, s6c, s6d_addr1, s6d_addr2, s6d_addr3, s6d_addr4, s6d_postcode, s6e, s6f, s6_auth, date_added, have_rep, have_sponsor, other_rep, s4_declaration, s2i, s1f_email) FROM stdin;
\.


--
-- TOC entry 4319 (class 0 OID 17476)
-- Dependencies: 217
-- Data for Name: IAFT7; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.iaft7 (id, hearing_type, qa_sponsor, qa_rep, qa_witness, qb_lsc, qb_lar, family_member, qc_name1, qc_relationship1, qc_prn1, qc_name2, qc_relationship2, qc_prn2, qc_name3, qc_relationship3, qc_prn3, qc_name4, qc_relationship4, qc_prn4, s1a, s1b, s1c, s1d, s1e, s1f_addr1, s1f_addr2, s1f_addr3, s1f_addr4, s1f_postcode, s1g, s1h, s1i_yourself, s1i_witness, s1i_representative, s1j, s1j_who, s1j_language, s1j_dialect, s1k, s1l, s1m, s1n, s1o, s1p, s1q, s2a, s2b, s2c, s2d_post, s2d_fax, s2d_courier, s2d_other, s2e, s2f, s3a, s3b, s3c, s3d_1, s3d_2, s3d_3, s3d_4, s3d_5, s3d_6, s3d_7, s3d_8, s3d_additional, s3e, s3e_date1, s3e_appealno1, s3e_date2, s3e_appealno2, s3e_date3, s3e_appealno3, s3f, s4_signature, s4_date, s5a, s5b, s5c_addr1, s5c_addr2, s5c_addr3, s5c_addr4, s5c_postcode, s5d, s5e, s5f, s5g, s5h, s5i, s5j, securitytoken, s5b_other, rep_sign, date_added, s4_declaration, s2i, s1f_email, s2hoan, s2j, s2k, s3g) FROM stdin;
\.


--
-- TOC entry 4321 (class 0 OID 17486)
-- Dependencies: 219
-- Data for Name: URN; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.urn (id) FROM stdin;
10232596
\.


--
-- TOC entry 4313 (class 0 OID 16409)
-- Dependencies: 211
-- Data for Name: formsdata; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.formsdata (securitytoken, submissionurn, paymenturn, aggregatedurn, formname, amount, formtitle, transactionstatus, count, id, status) FROM stdin;
\.


--
-- TOC entry 4320 (class 0 OID 17481)
-- Dependencies: 218
-- Data for Name: transaction_details; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.transaction_details (id, transactionstatus, orderid, type, referencenumber, sub_count, aggr_urn, dateofpayment) FROM stdin;
\.


SELECT pg_catalog.setval('public.fees_id_seq', (SELECT COALESCE(MAX(id), 1) FROM public.fees), true);

SELECT pg_catalog.setval('public.formsdata_id_seq', (SELECT COALESCE(MAX(id), 1) FROM public.formsdata), true);

SELECT pg_catalog.setval('public.iaft1_id_seq', (SELECT COALESCE(MAX(id), 1) FROM public.iaft1), true);

SELECT pg_catalog.setval('public.iaft2_id_seq', (SELECT COALESCE(MAX(id), 1) FROM public.iaft2), true);

SELECT pg_catalog.setval('public.iaft3_id_seq', (SELECT COALESCE(MAX(id), 1) FROM public.iaft3), true);

SELECT pg_catalog.setval('public.iaft5_id_seq', (SELECT COALESCE(MAX(id), 1) FROM public.iaft5), true);

SELECT pg_catalog.setval('public.iaft6_id_seq', (SELECT COALESCE(MAX(id), 1) FROM public.iaft6), true);

SELECT pg_catalog.setval('public.iaft7_id_seq', (SELECT COALESCE(MAX(id), 1) FROM public.iaft7), true);

SELECT pg_catalog.setval('public.transaction_details_id_seq', (SELECT COALESCE(MAX(id), 1) FROM public.transaction_details), false);



ALTER TABLE ONLY public.fees
    ADD CONSTRAINT fees_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.formsdata
    ADD CONSTRAINT formsdata_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.iaft1
    ADD CONSTRAINT iaft1_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.iaft2
    ADD CONSTRAINT iaft2_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.iaft3
    ADD CONSTRAINT iaft3_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.iaft5
    ADD CONSTRAINT iaft5_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.iaft6
    ADD CONSTRAINT iaft6_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.iaft7
    ADD CONSTRAINT iaft7_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.transaction_details
    ADD CONSTRAINT transaction_details_pkey PRIMARY KEY (id);

REVOKE USAGE ON SCHEMA public FROM PUBLIC;
GRANT ALL ON SCHEMA public TO PUBLIC;
