kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: onboarding-optimisation-dev-admin
  namespace: onboarding-optimisation-dev
subjects:
  - kind: Group
    name: "github:justice-ai-unit"
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
