kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: reuse-library-dev-admin
  namespace: reuse-library-dev
subjects:
  - kind: Group
    name: "github:reuse-library-gh-admins"
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
