{
 "title": "Track-a-query Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Pods general",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum({namespace=\"track-a-query-production\", phase='Running'} + 0)",
     "legendFormat": "Pods number"
    },
    {
     "expr": "sum(rate(kube_pod_container_status_restarts_total{namespace=\"track-a-query-production\"} [60m]))",
     "legendFormat": "Restarts count (60m)"
    }
   ]
  },
  {
   "title": "Restarts(2m) by container",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kube_pod_container_status_restarts_total{namespace=\"track-a-query-production\", container=\"jobs\"}[2m]))",
     "legendFormat": "Jobs container"
    },
    {
     "expr": "sum(rate(kube_pod_container_status_restarts_total{namespace=\"track-a-query-production\", container=\"webapp\"}[2m]))",
     "legendFormat": "Webapp container"
    },
    {
     "expr": "sum(rate(kube_pod_container_status_restarts_total{namespace=\"track-a-query-production\", container=\"uploads\"}[2m]))",
     "legendFormat": "Upload container"
    }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "CPU Usage compared with limit",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg by (container)(rate(container_cpu_usage_seconds_total{namespace=\"track-a-query-production\"}[5m]))",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "avg(kube_pod_container_resource_limits_cpu_cores{namespace=\"track-a-query-production\"})",
     "legendFormat": "Hard limit"
    },
    {
     "expr": "avg(kube_pod_container_resource_requests_cpu_cores{namespace=\"track-a-query-production\"})",
     "legendFormat": "Requested"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg by (container)(rate(container_cpu_usage_seconds_total{namespace=\"track-a-query-production\"}[5m]))",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Average Request Duration",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "avg(rate(nginx_ingress_controller_request_duration_seconds_sum{exported_namespace = \"track-a-query-production\", ingress = \"track-a-query-ingress\"}[5m]) / rate(nginx_ingress_controller_request_duration_seconds_count{exported_namespace = \"track-a-query-production\", ingress = \"track-a-query-ingress\"}[5m]) > 0)",
     "legendFormat": "Average Request Duration"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "avg by (container)(container_memory_usage_bytes{namespace=\"track-a-query-production\"})",
     "legendFormat": "{{container}}"
    },
    {
     "expr": "avg(kube_pod_container_resource_requests_memory_bytes{namespace=\"track-a-query-production\"})",
     "legendFormat": "Requestec"
    },
    {
     "expr": "avg(kube_pod_container_resource_limits_memory_bytes{namespace=\"track-a-query-production\"})",
     "legendFormat": "Hard limit"
    }
   ]
  },
  {
   "title": "Ingress Controller Requests",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_requests{exported_namespace = \"track-a-query-production\", ingress = \"track-a-query-ingress\"}[5m])) by(status)",
     "legendFormat": "{{status}}"
    }
   ]
  }
 ]
}