{
 "title": "Application Alerts",
 "description": "Charts and tables showing the configured application alerts in the HMPPS \"generic-alerts\" helm chart.",
 "tags": [
  "kubernetes",
  "alertmanager"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_namespace_created{}, namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "KubeQuotaExceeded",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum by (resource) (\n  kube_resourcequota{namespace=\"$namespace\", type=\"used\"}\n  / \n  ignoring(instance, job, type) (kube_resourcequota{namespace=\"$namespace\", type=\"hard\"}) > 0\n)\n* 100",
     "legendFormat": "{{ resource }} quota"
    },
    { "expr": "vector(90)", "legendFormat": "threshold" }
   ]
  },
  {
   "title": "Pod / Container / Deployment Alerts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "KubePodCrashLooping",
     "type": "graph",
     "description": "This chart shows the count of pod/container restart events observed.  This will show \"CrashLooping\" error events.",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "short", "label": "Count" }
     ],
     "targets": [
      {
       "expr": "sum by (pod) (increase(kube_pod_container_status_restarts_total{namespace=\"$namespace\"}[10m])) > 0",
       "legendFormat": "{{ pod }}"
      }
     ]
    },
    {
     "title": "KubePodNotReady",
     "type": "graph",
     "description": "This chart shows the count of pods in an \"non-ready\" state.",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "yaxes": [
      { "format": "short", "label": "Count" }
     ],
     "targets": [
      {
       "expr": "sum by (pod) (\n  kube_pod_status_phase{namespace=\"$namespace\", phase=~\"Pending|Unknown\"}\n) > 0",
       "legendFormat": "{{ pod }}"
      }
     ]
    },
    {
     "title": "KubeContainerWaiting",
     "type": "graph",
     "description": "This shows containers/pods in a waiting state.",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 10 },
     "yaxes": [
      { "format": "short", "label": "Count" }
     ],
     "targets": [
      {
       "expr": "sum by (pod, container) (kube_pod_container_status_waiting_reason{namespace=~\"$namespace\"}) > 0",
       "legendFormat": "{{ pod }} ({{ container }})"
      }
     ]
    },
    {
     "title": "KubeDeploymentGenerationMismatch",
     "type": "table",
     "description": "Any deployments listed in this table have a \"deployment generation mismatch\" - this indicates that a deployment has failed, but a rollback has not been rolled back.",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 18 },
     "targets": [
      {
       "expr": "kube_deployment_status_observed_generation{namespace=\"$namespace\"}\n!=\nkube_deployment_metadata_generation{namespace=\"$namespace\"}"
      }
     ]
    },
    {
     "title": "KubeDeploymentReplicasMismatch",
     "type": "table",
     "description": "Any deployments listed in this table does not have the expected number of replicas.",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 24 },
     "targets": [
      {
       "expr": "kube_deployment_spec_replicas{namespace=\"$namespace\"}\n!=\nkube_deployment_status_replicas_available{namespace=\"$namespace\"}"
      }
     ]
    },
    {
     "title": "KubeContainerOOMKilled",
     "type": "table",
     "description": "Any pods/containers listed here have been OOMKilled in the relevant timeframe.",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 30 },
     "targets": [
      {
       "expr": "(\n  kube_pod_container_status_restarts_total{namespace=\"$namespace\"}\n  - \n  kube_pod_container_status_restarts_total{namespace=\"$namespace\"} offset 10m >= 1\n)\nand \nignoring (reason) min_over_time(kube_pod_container_status_last_terminated_reason{namespace=\"$namespace\", reason=\"OOMKilled\"}[10m]) == 1"
      }
     ]
    }
   ]
  },
  {
   "title": "Horizontal Pod Autoscaler Alerts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "KubeHpaReplicasMismatch",
     "type": "table",
     "description": "Any HPA listed in this table has not matched the desired number of replicas within the selected timeframe.",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 10 },
     "targets": [
      {
       "expr": "(\n  kube_hpa_status_desired_replicas{namespace=\"$namespace\"}\n  !=\n  kube_hpa_status_current_replicas{}\n)\nand\n(\n  kube_hpa_status_current_replicas{}\n  >\n  kube_hpa_spec_min_replicas{}\n)\nand\n(\n  kube_hpa_status_current_replicas{}\n  <\n  kube_hpa_spec_max_replicas{}\n)\nand\nchanges(kube_hpa_status_current_replicas{}[15m]) == 0"
      }
     ]
    },
    {
     "title": "KubeHpaMaxedOut",
     "type": "table",
     "description": "Any HPA listed in this table has been running at its maximum number of replicas within the selected timeframe.",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 16 },
     "targets": [
      {
       "expr": "kube_hpa_status_current_replicas{namespace=\"$namespace\"}\n==\nkube_hpa_spec_max_replicas{}"
      }
     ]
    }
   ]
  },
  {
   "title": "CronJob / Job Alerts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "KubeCronJobRunning",
     "type": "table",
     "description": "Any cronjobs listed in this table have taken more than 1 hour to complete.",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 12 },
     "targets": [
      {
       "expr": "time() - kube_cronjob_next_schedule_time{namespace=\"$namespace\"} > 3600"
      }
     ]
    },
    {
     "title": "KubeJobCompletion",
     "type": "table",
     "description": "Any cronjobs listed in this table have not yet completed.",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 18 },
     "targets": [
      {
       "expr": "kube_job_spec_completions{namespace=\"$namespace\"}\n- \nkube_job_status_succeeded{namespace=\"$namespace\"} \n> 0"
      }
     ]
    }
   ]
  }
 ]
}