{
 "title": "AWS OpenSearch",
 "description": "Visualize Amazon OpenSearch metrics",
 "tags": [
  "AWS",
  "AWSElasticSearch",
  "OpenSearch",
  "CloudWatch"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "cloudwatch" },
   { "name": "region", "label": "Region", "query": "regions()" },
   {
    "name": "domainName",
    "label": "DomainName",
    "query": "dimension_values($region, AWS/ES, ClusterStatus.green, DomainName)\t"
   },
   {
    "name": "clientId",
    "label": "ClientId",
    "query": "dimension_values($region, AWS/ES, ClusterStatus.green, ClientId)"
   }
  ]
 },
 "panels": [
  { "title": "Overall Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Cluster Status",
   "type": "timeseries",
   "description": "Indicates shard allocation status.",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Green",
     "dimensions": { "ClientId": "$clientId", "DomainName": "$domainName" },
     "metricName": "ClusterStatus.green",
     "namespace": "AWS/ES",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Maximum"
    },
    {
     "alias": "Yellow",
     "dimensions": { "ClientId": "$clientId", "DomainName": "$domainName" },
     "metricName": "ClusterStatus.yellow",
     "namespace": "AWS/ES",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Maximum"
    },
    {
     "alias": "Red",
     "dimensions": { "ClientId": "$clientId", "DomainName": "$domainName" },
     "metricName": "ClusterStatus.red",
     "namespace": "AWS/ES",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Maximum"
    }
   ]
  },
  {
   "title": "Cluster Writes Status",
   "type": "timeseries",
   "description": "Indicates whether the cluster is accepting or blocking write requests. If your cluster is blocking write requests, check storage space, JVM memory pressure and CPU utilization.",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Green",
     "expression": "(m3*(-1))+1",
     "metricEditorMode": 1,
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Average"
    },
    {
     "alias": "Red",
     "expression": "m3*2",
     "metricEditorMode": 1,
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Master instance connection status",
   "type": "timeseries",
   "description": "Indicates where data nodes can reach the master node. Failures are usually the result of a network connectivity problem.",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Green",
     "expression": "m3",
     "metricEditorMode": 1,
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Average"
    },
    {
     "alias": "Red",
     "expression": "(m3*(-2))+2",
     "metricEditorMode": 1,
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Snapshot failure status",
   "type": "timeseries",
   "description": "Failure indicate that no automated snapshot has succeeded in the past 36 hours.",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Green",
     "expression": "(m3*(-1))+1",
     "metricEditorMode": 1,
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Average"
    },
    {
     "alias": "Red",
     "expression": "m3*2",
     "metricEditorMode": 1,
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Total nodes",
   "type": "timeseries",
   "description": "The total number of nodes for your cluster. This metric can increase (often doubling) during configuration changes and service software updates.",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dimensions": { "ClientId": "$clientId", "DomainName": "$domainName" },
     "metricName": "Nodes",
     "namespace": "AWS/ES",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Minimum"
    }
   ]
  },
  {
   "title": "Searchable documents",
   "type": "stat",
   "description": "The total number of searchable documents across all indices in the cluster.",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": { "ClientId": "$clientId", "DomainName": "$domainName" },
     "metricName": "SearchableDocuments",
     "namespace": "AWS/ES",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  { "title": "Service Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Rate",
   "type": "timeseries",
   "description": "The number of indexing and search operations per minute. \n\nA single call to the _bulk API that adds two documents and updates two counts as four operations plus four additional operations per replica. Document deletions do not towards this metric.\n\nA single call to the _search API that returns results from five shards counts as five operations.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dimensions": { "ClientId": "$clientId", "DomainName": "$domainName" },
     "metricName": "IndexingRate",
     "namespace": "AWS/ES",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Average"
    },
    {
     "dimensions": { "ClientId": "$clientId", "DomainName": "$domainName" },
     "metricName": "SearchRate",
     "namespace": "AWS/ES",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "description": "The average time that it takes a shard to complete a search or index operation.",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "dimensions": { "ClientId": "$clientId", "DomainName": "$domainName" },
     "metricName": "IndexingLatency",
     "namespace": "AWS/ES",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Average"
    },
    {
     "dimensions": { "ClientId": "$clientId", "DomainName": "$domainName" },
     "metricName": "SearchLatency",
     "namespace": "AWS/ES",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "timeseries",
   "description": "The number of requests to a domain, aggregated by HTTP response code (2xx, 3xx, 4xx, 5xx).",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "2XX",
     "dimensions": { "ClientId": "$clientId", "DomainName": "$domainName" },
     "label": "2XX",
     "metricName": "2xx",
     "namespace": "AWS/ES",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Sum"
    },
    {
     "alias": "3XX",
     "dimensions": { "ClientId": "$clientId", "DomainName": "$domainName" },
     "label": "3XX",
     "metricName": "3xx",
     "namespace": "AWS/ES",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Sum"
    },
    {
     "alias": "4XX",
     "dimensions": { "ClientId": "$clientId", "DomainName": "$domainName" },
     "label": "4XX",
     "metricName": "4xx",
     "namespace": "AWS/ES",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Sum"
    },
    {
     "alias": "5XX",
     "dimensions": { "ClientId": "$clientId", "DomainName": "$domainName" },
     "label": "5XX",
     "metricName": "5xx",
     "namespace": "AWS/ES",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Sum"
    }
   ]
  },
  { "title": "Cluster Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "CPU Utilization ",
   "type": "timeseries",
   "description": "Maximum CPU utilization percentage for all data nodes.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "CPUUtilization",
     "dimensions": { "ClientId": "$clientId", "DomainName": "$domainName" },
     "label": "CPUUtilization",
     "metricName": "CPUUtilization",
     "namespace": "AWS/ES",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Maximum"
    }
   ]
  },
  {
   "title": "IOPS",
   "type": "timeseries",
   "description": "Disk read and write operations per second",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dimensions": { "ClientId": "$clientId", "DomainName": "$domainName" },
     "metricName": "WriteIOPS",
     "namespace": "AWS/ES",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Maximum"
    },
    {
     "dimensions": { "ClientId": "$clientId", "DomainName": "$domainName" },
     "metricName": "ReadIOPS",
     "namespace": "AWS/ES",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Maximum"
    }
   ]
  },
  {
   "title": "Total free storage space",
   "type": "timeseries",
   "description": "The total amount of free storage space, accross all data nodes.",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "dimensions": { "ClientId": "$clientId", "DomainName": "$domainName" },
     "metricName": "FreeStorageSpace",
     "namespace": "AWS/ES",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "JVMMemoryPressure",
   "type": "timeseries",
   "description": "Maximum JVM memory pressure percentage for all data nodes.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "JVMMemoryPressure",
     "dimensions": { "ClientId": "$clientId", "DomainName": "$domainName" },
     "label": "JVMMemoryPressure",
     "metricName": "JVMMemoryPressure",
     "namespace": "AWS/ES",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Maximum"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "timeseries",
   "description": "Disk read and write throughput",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "dimensions": { "ClientId": "$clientId", "DomainName": "$domainName" },
     "metricName": "WriteThroughput",
     "namespace": "AWS/ES",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Maximum"
    },
    {
     "dimensions": { "ClientId": "$clientId", "DomainName": "$domainName" },
     "metricName": "ReadThroughput",
     "namespace": "AWS/ES",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Maximum"
    }
   ]
  },
  {
   "title": "Minimum free storage space",
   "type": "timeseries",
   "description": "The amount of free storage space on the data node with the smallest amount of free storage space in the cluster.",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "alias": "FreeStorageSpace",
     "dimensions": { "ClientId": "$clientId", "DomainName": "$domainName" },
     "metricName": "FreeStorageSpace",
     "namespace": "AWS/ES",
     "period": "1m",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Minimum"
    }
   ]
  },
  {
   "title": "Data Instances",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Utilization ",
     "type": "timeseries",
     "description": "Maximum CPU utilization percentage for all data nodes.",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "alias": "WarmCPUUtilization",
       "dimensions": { "ClientId": "$clientId", "DomainName": "$domainName", "NodeId": "*" },
       "metricName": "CPUUtilization",
       "namespace": "AWS/ES",
       "queryMode": "Metrics",
       "region": "$region",
       "statistic": "Maximum"
      }
     ]
    },
    {
     "title": "JVM Memory Pressure",
     "type": "timeseries",
     "description": "Maximum JVM memory pressure percentage for all data nodes.",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "alias": "WarmJVMMemoryPressure",
       "dimensions": { "ClientId": "$clientId", "DomainName": "$domainName", "NodeId": "*" },
       "metricName": "JVMMemoryPressure",
       "namespace": "AWS/ES",
       "queryMode": "Metrics",
       "region": "$region",
       "statistic": "Maximum"
      }
     ]
    },
    {
     "title": "System Memory Utilization",
     "type": "timeseries",
     "description": "Maximum memory usage percentage for all data nodes.",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "alias": "SysMemoryUtilization",
       "dimensions": { "ClientId": "$clientId", "DomainName": "$domainName", "NodeId": "*" },
       "metricName": "SysMemoryUtilization",
       "namespace": "AWS/ES",
       "period": "1m",
       "queryMode": "Metrics",
       "region": "$region",
       "statistic": "Maximum"
      }
     ]
    },
    {
     "title": "Young Collection Time",
     "type": "timeseries",
     "description": "The amount of time, in milliseconds that the cluster has spent performing \"Young generation\" garbage collection.",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "alias": "JVMGCYoungCollectionTime",
       "dimensions": { "ClientId": "$clientId", "DomainName": "$domainName" },
       "label": "JVMGCYoungCollectionTime",
       "metricName": "JVMGCYoungCollectionTime",
       "namespace": "AWS/ES",
       "queryMode": "Metrics",
       "region": "$region",
       "statistic": "Maximum"
      }
     ]
    },
    {
     "title": "Young Collection",
     "type": "timeseries",
     "description": "The number of times that \"Young generation\" garbage collection has run. A large number if runs is a normal part of cluster operations. ",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "alias": "JVMGCYoungCollectionCount",
       "dimensions": { "ClientId": "$clientId", "DomainName": "$domainName" },
       "label": "JVMGCYoungCollectionCount",
       "metricName": "JVMGCYoungCollectionCount",
       "namespace": "AWS/ES",
       "queryMode": "Metrics",
       "region": "$region",
       "statistic": "Maximum"
      }
     ]
    },
    {
     "title": "Old Collection Time",
     "type": "timeseries",
     "description": "The amount of time, in milliseconds that the cluster has spent performing \"Old generation\" garbage collection.",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "alias": "JVMGCOldCollectionTime",
       "dimensions": { "ClientId": "$clientId", "DomainName": "$domainName" },
       "label": "JVMGCOldCollectionTime",
       "metricName": "JVMGCOldCollectionTime",
       "namespace": "AWS/ES",
       "queryMode": "Metrics",
       "region": "$region",
       "statistic": "Maximum"
      }
     ]
    },
    {
     "title": "Old Collection",
     "type": "timeseries",
     "description": "The number of times that \"Old generation\" garbage collection has run. A large number if runs is a normal part of cluster operations. ",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "alias": "JVMGCYoungCollectionCount",
       "dimensions": { "ClientId": "$clientId", "DomainName": "$domainName" },
       "metricName": "JVMGCOldCollectionCount",
       "namespace": "AWS/ES",
       "queryMode": "Metrics",
       "region": "$region",
       "statistic": "Maximum"
      }
     ]
    }
   ]
  },
  {
   "title": "Warm Instances",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "collapsed": true,
   "panels": [
    {
     "title": "Maximum CPU Utilization ",
     "type": "timeseries",
     "description": "Maximum CPU utilization percentage for all data nodes.",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 74 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "alias": "WarmCPUUtilization",
       "dimensions": { "ClientId": "$clientId", "DomainName": "$domainName" },
       "metricName": "WarmCPUUtilization",
       "namespace": "AWS/ES",
       "queryMode": "Metrics",
       "region": "$region",
       "statistic": "Maximum"
      }
     ]
    },
    {
     "title": "Maximum JVMMemoryPressure",
     "type": "timeseries",
     "description": "Maximum JVM memory pressure percentage for all data nodes.",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 74 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "alias": "WarmJVMMemoryPressure",
       "dimensions": { "ClientId": "$clientId", "DomainName": "$domainName" },
       "metricName": "WarmJVMMemoryPressure",
       "namespace": "AWS/ES",
       "queryMode": "Metrics",
       "region": "$region",
       "statistic": "Maximum"
      }
     ]
    },
    {
     "title": "Minimum free storage space",
     "type": "timeseries",
     "description": "The amount of free storage space on the data node with the smallest amount of free storage space in the cluster.",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 74 },
     "fieldConfig": { "defaults": { "unit": "decmbytes" } },
     "targets": [
      {
       "alias": "WarmFreeStorageSpace",
       "dimensions": { "ClientId": "$clientId", "DomainName": "$domainName" },
       "metricName": "WarmFreeStorageSpace",
       "namespace": "AWS/ES",
       "period": "1m",
       "queryMode": "Metrics",
       "region": "$region",
       "statistic": "Minimum"
      }
     ]
    },
    {
     "title": "Maximum Memory Utilization",
     "type": "timeseries",
     "description": "Maximum memory usage percentage for all data nodes.",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 74 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "alias": "WarmSysMemoryUtilization",
       "dimensions": { "ClientId": "$clientId", "DomainName": "$domainName" },
       "metricName": "WarmSysMemoryUtilization",
       "namespace": "AWS/ES",
       "period": "1m",
       "queryMode": "Metrics",
       "region": "$region",
       "statistic": "Maximum"
      }
     ]
    }
   ]
  },
  {
   "title": "Dedicated Master Instances",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "collapsed": true,
   "panels": [
    {
     "title": "Maximum CPU Utilization",
     "type": "timeseries",
     "description": "CPU utilization percentage for the master node.",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 75 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "alias": "MasterCPUUtilization",
       "dimensions": { "ClientId": "$clientId", "DomainName": "$domainName", "NodeId": "*" },
       "metricName": "MasterCPUUtilization",
       "namespace": "AWS/ES",
       "queryMode": "Metrics",
       "region": "$region",
       "statistic": "Maximum"
      }
     ]
    },
    {
     "title": "Maximum JVMMemoryPressure",
     "type": "timeseries",
     "description": "JVM memory pressure percentage for the master node.",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 75 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "alias": "MasterJVMMemoryPressure",
       "dimensions": { "ClientId": "$clientId", "DomainName": "$domainName", "NodeId": "*" },
       "metricName": "MasterJVMMemoryPressure",
       "namespace": "AWS/ES",
       "queryMode": "Metrics",
       "region": "$region",
       "statistic": "Maximum"
      }
     ]
    },
    {
     "title": "Minimum free storage space",
     "type": "timeseries",
     "description": "The amount of free storage space on the data node with the smallest amount of free storage space in the cluster.",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 75 },
     "fieldConfig": { "defaults": { "unit": "decmbytes" } },
     "targets": [
      {
       "alias": "MasterFreeStorageSpace",
       "dimensions": { "ClientId": "$clientId", "DomainName": "$domainName", "NodeId": "*" },
       "metricName": "MasterFreeStorageSpace",
       "namespace": "AWS/ES",
       "period": "1m",
       "queryMode": "Metrics",
       "region": "$region",
       "statistic": "Minimum"
      }
     ]
    },
    {
     "title": "Maximum Memory Utilization",
     "type": "timeseries",
     "description": "Maximum memory usage percentage for all data nodes.",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 75 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "alias": "MasterSysMemoryUtilization",
       "dimensions": { "ClientId": "$clientId", "DomainName": "$domainName", "NodeId": "*" },
       "metricName": "MasterSysMemoryUtilization",
       "namespace": "AWS/ES",
       "period": "1m",
       "queryMode": "Metrics",
       "region": "$region",
       "statistic": "Maximum"
      }
     ]
    }
   ]
  },
  {
   "title": "Thread Pools",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "collapsed": true,
   "panels": [
    {
     "title": "Write Thread Pool",
     "type": "timeseries",
     "description": "Metrics for the write thread pool: number of threads, tasks in the queue and rejected tasks. If the queue size is consistently high or rejected count is high, consider scaling your cluster.",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 48 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "alias": "ThreadCount",
       "dimensions": { "ClientId": "$clientId", "DomainName": "$domainName" },
       "metricName": "ThreadpoolWriteThreads",
       "namespace": "AWS/ES",
       "queryMode": "Metrics",
       "region": "$region",
       "statistic": "Maximum"
      },
      {
       "alias": "Queue Depth",
       "dimensions": { "ClientId": "$clientId", "DomainName": "$domainName" },
       "metricName": "ThreadpoolWriteQueue",
       "namespace": "AWS/ES",
       "queryMode": "Metrics",
       "region": "$region",
       "statistic": "Maximum"
      },
      {
       "alias": "Rejected Count",
       "dimensions": { "ClientId": "$clientId", "DomainName": "$domainName" },
       "metricName": "ThreadpoolWriteRejected",
       "namespace": "AWS/ES",
       "queryMode": "Metrics",
       "region": "$region",
       "statistic": "Maximum"
      }
     ]
    },
    {
     "title": "Search Thread Pool",
     "type": "timeseries",
     "description": "Metrics for search thread pool: number of threads tasks in the queue and rejected tasks. If the queue size is consistently high or rejected count is high, consider scaling your cluster.",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 48 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "alias": "ThreadCount",
       "dimensions": { "ClientId": "$clientId", "DomainName": "$domainName" },
       "label": "ThreadCount",
       "metricName": "ThreadpoolSearchThreads",
       "namespace": "AWS/ES",
       "queryMode": "Metrics",
       "region": "$region",
       "statistic": "Maximum"
      },
      {
       "alias": "Queue Depth",
       "dimensions": { "ClientId": "$clientId", "DomainName": "$domainName" },
       "label": "Queue Depth",
       "metricName": "ThreadpoolSearchQueue",
       "namespace": "AWS/ES",
       "queryMode": "Metrics",
       "region": "$region",
       "statistic": "Maximum"
      },
      {
       "alias": "Rejected Count",
       "dimensions": { "ClientId": "$clientId", "DomainName": "$domainName" },
       "label": "Rejected Count",
       "metricName": "ThreadpoolSearchRejected",
       "namespace": "AWS/ES",
       "queryMode": "Metrics",
       "region": "$region",
       "statistic": "Maximum"
      }
     ]
    },
    {
     "title": "Merge Thread Pool",
     "type": "timeseries",
     "description": "Metrics for the force merge thread pool: number of threads tasks in the queue and rejected tasks. If the queue size is consistently high or rejected count is high, consider scaling your cluster.",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 48 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "alias": "ThreadCount",
       "dimensions": { "ClientId": "$clientId", "DomainName": "$domainName" },
       "metricName": "ThreadpoolForce_mergeThreads",
       "namespace": "AWS/ES",
       "queryMode": "Metrics",
       "region": "$region",
       "statistic": "Maximum"
      },
      {
       "alias": "Queue Depth",
       "dimensions": { "ClientId": "$clientId", "DomainName": "$domainName" },
       "metricName": "ThreadpoolForce_mergeQueue",
       "namespace": "AWS/ES",
       "queryMode": "Metrics",
       "region": "$region",
       "statistic": "Maximum"
      },
      {
       "alias": "Rejected Count",
       "dimensions": { "ClientId": "$clientId", "DomainName": "$domainName" },
       "metricName": "ThreadpoolForce_mergeRejected",
       "namespace": "AWS/ES",
       "queryMode": "Metrics",
       "region": "$region",
       "statistic": "Maximum"
      }
     ]
    }
   ]
  }
 ]
}