{
 "title": "Golden Signals",
 "description": "High level application HTTP request and resource usage information.",
 "tags": [
  "kubernetes",
  "nginx-ingress"
 ],
 "time": { "from": "2025-05-07T09:06:31.594Z", "to": "2025-05-07T09:40:00.468Z" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(nginx_ingress_controller_requests{}, exported_namespace)"
    }
   },
   {
    "name": "service",
    "query": {
     "query": "label_values(nginx_ingress_controller_requests{exported_namespace=\"$namespace\"}, exported_service)"
    }
   },
   { "name": "DS_PROMETHEUS", "query": "prometheus" },
   { "name": "DS_THANOS", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Requests",
   "type": "timeseries",
   "description": "The number of HTTP requests by status",
   "gridPos": { "h": 10, "w": 20, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(\n  increase(nginx_ingress_controller_requests{ingress=~\"$service(-v1-2)\", exported_namespace=\"$namespace\"}[$__rate_interval])\n) by (status) != 0",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Requests Served",
   "type": "stat",
   "description": "The total number of requests served in the selected time period.",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(nginx_ingress_controller_requests{ingress=~\"$service(-v1-2)\", exported_namespace=\"$namespace\"}[${__range_s}s]))"
    }
   ]
  },
  {
   "title": "Mean Response Time (p100)",
   "type": "stat",
   "description": "The mean response time (p100 - all requests) over the selected timeframe.",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(\n  1,\n  max(\n    irate(nginx_ingress_controller_request_duration_seconds_bucket{ingress=~\"$service(-v1-2)\", exported_namespace=\"$namespace\"}[${__range_s}s])\n  ) by (le)\n) > 0"
    }
   ]
  },
  {
   "title": "Mean Response Time (p95)",
   "type": "stat",
   "description": "The mean response time (p95 - the 95th percentile of requests) over the selected timeframe.",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.95,\n  max(\n    irate(nginx_ingress_controller_request_duration_seconds_bucket{ingress=~\"$service(-v1-2)\", exported_namespace=\"$namespace\"}[${__range_s}s])\n  ) by (le)\n) > 0"
    }
   ]
  },
  {
   "title": "Mean Response Time (p50)",
   "type": "stat",
   "description": "The mean response time (p50 - the 50th percentile requests) over the selected timeframe.",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.5,\n  max(\n    irate(nginx_ingress_controller_request_duration_seconds_bucket{ingress=~\"$service(-v1-2)\", exported_namespace=\"$namespace\"}[${__range_s}s])\n  ) by (le)\n) > 0"
    }
   ]
  },
  {
   "title": "Availability",
   "type": "timeseries",
   "description": "The percentage of HTTP responses that are non-error codes vs error codes.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(irate(nginx_ingress_controller_requests{ingress=~\"$service(-v1-2)\", exported_namespace=\"$namespace\", status!~\"5.*|499\"}[$__rate_interval]))\n/ \nsum(irate(nginx_ingress_controller_requests{ingress=~\"$service(-v1-2)\", exported_namespace=\"$namespace\"}[$__rate_interval]))\n* 100",
     "legendFormat": "Request Success Rate"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "description": "Recorded request duration from the ingress controllers in percentiles.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.5,\n  max(\n    irate(nginx_ingress_controller_request_duration_seconds_bucket{ingress=~\"$service(-v1-2)\", exported_namespace=\"$namespace\"}[$__rate_interval])\n  ) by (le)\n)",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(\n  0.95,\n  max(\n    irate(nginx_ingress_controller_request_duration_seconds_bucket{ingress=~\"$service(-v1-2)\", exported_namespace=\"$namespace\"}[$__rate_interval])\n  ) by (le)\n)",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(\n  1,\n  max(\n    irate(nginx_ingress_controller_request_duration_seconds_bucket{ingress=~\"$service(-v1-2)\", exported_namespace=\"$namespace\"}[$__rate_interval])\n  ) by (le)\n)",
     "legendFormat": "p100"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "timeseries",
   "description": "The percentage of all HTTP requests that result in a 5xx status.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(irate(nginx_ingress_controller_requests{ingress=~\"$service(-v1-2)\", exported_namespace=\"$namespace\", status=\"500\"}[$__rate_interval])) \n/ \nsum(irate(nginx_ingress_controller_requests{ingress=~\"$service(-v1-2)\", exported_namespace=\"$namespace\"}[$__rate_interval]))\n* 100",
     "legendFormat": "500"
    },
    {
     "expr": "sum(irate(nginx_ingress_controller_requests{ingress=~\"$service(-v1-2)\", exported_namespace=\"$namespace\", status=\"501\"}[$__rate_interval])) \n/ \nsum(irate(nginx_ingress_controller_requests{ingress=~\"$service(-v1-2)\", exported_namespace=\"$namespace\"}[$__rate_interval]))\n* 100",
     "legendFormat": "501"
    },
    {
     "expr": "sum(irate(nginx_ingress_controller_requests{ingress=~\"$service(-v1-2)\", exported_namespace=\"$namespace\", status=\"502\"}[$__rate_interval])) \n/ \nsum(irate(nginx_ingress_controller_requests{ingress=~\"$service(-v1-2)\", exported_namespace=\"$namespace\"}[$__rate_interval]))\n* 100",
     "legendFormat": "502"
    },
    {
     "expr": "sum(irate(nginx_ingress_controller_requests{ingress=~\"$service(-v1-2)\", exported_namespace=\"$namespace\", status=\"503\"}[$__rate_interval])) \n/ \nsum(irate(nginx_ingress_controller_requests{ingress=~\"$service(-v1-2)\", exported_namespace=\"$namespace\"}[$__rate_interval]))\n* 100",
     "legendFormat": "503"
    },
    {
     "expr": "sum(irate(nginx_ingress_controller_requests{ingress=~\"$service(-v1-2)\", exported_namespace=\"$namespace\", status=\"504\"}[$__rate_interval])) \n/ \nsum(irate(nginx_ingress_controller_requests{ingress=~\"$service(-v1-2)\", exported_namespace=\"$namespace\"}[$__rate_interval]))\n* 100",
     "legendFormat": "504"
    }
   ]
  },
  {
   "title": "Blocked Requests",
   "type": "timeseries",
   "description": "This chart shows the number of blocked requests at the ingress level.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(\n  increase(nginx_ingress_controller_requests{ingress=~\"$service(-v1-2)\", exported_namespace=\"$namespace\", status=\"429\"}[$__rate_interval])\n)\nor\nvector(0)",
     "legendFormat": "Rate Limited Reqs"
    },
    {
     "expr": "sum(\n  increase(nginx_ingress_controller_requests{ingress=~\"$service(-v1-2)\", exported_namespace=\"$namespace\", status=\"406\"}[$__rate_interval])\n)\nor\nvector(0)",
     "legendFormat": "Mod Security Blocked Reqs"
    }
   ]
  },
  {
   "title": "Requested CPU Usage",
   "type": "timeseries",
   "description": "CPU usage in relation to the requested cpu for the container.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg(irate(container_cpu_usage_seconds_total{pod=~\"$service-.+\", pod!~\"$service(-api|-ui).+\", namespace=\"$namespace\", container!=\"POD\", container=~\".+\"}[1m])) by (container)\n/ \navg(kube_pod_container_resource_requests{resource=\"cpu\", pod=~\"$service-.+\", pod!~\"$service(-api|-ui).+\",namespace=\"$namespace\"}) by (container)",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Actual CPU Usage",
   "type": "timeseries",
   "description": "Average recorded CPU usage for each type container within the pods.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(\n  irate(container_cpu_usage_seconds_total{pod=~\"$service-.+\", pod!~\"$service(-api|-ui).+\", namespace=\"$namespace\", container=~\".+\"}[1m])\n) by (container)",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Network I/O",
   "type": "timeseries",
   "description": "The amount of data being sent to and from the pods.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(irate(container_network_receive_bytes_total{namespace=\"$namespace\", pod=~\"$service-.+\", pod!~\"$service(-api|-ui).+\"}[2m]))",
     "legendFormat": "Receive"
    },
    {
     "expr": "sum(irate(container_network_transmit_bytes_total{namespace=\"$namespace\", pod=~\"$service-.+\", pod!~\"$service(-api|-ui).+\"}[2m]))",
     "legendFormat": "Transmit"
    }
   ]
  },
  {
   "title": "Requested Memory Usage",
   "type": "timeseries",
   "description": "Memory usage in relation to the requested memory for the container.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg(irate(container_memory_usage_bytes{pod=~\"$service-.+\", pod!~\"$service(-api|-ui).+\", namespace=\"$namespace\", container=~\".+\"}[1m])) by (container)\n/ \navg(kube_pod_container_resource_requests{resource=\"memory\", pod=~\"$service-.+\", pod!~\"$service(-api|-ui).+\", namespace=\"$namespace\"}) by (container)\n* 100",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Actual Memory Usage",
   "type": "timeseries",
   "description": "Average recorded memory usage for a single type of container within the pods.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "avg(\n  irate(container_memory_usage_bytes{pod=~\"$service-.+\", pod!~\"$service(-api|-ui).+\", namespace=\"$namespace\", container!=\"POD\", container=~\".+\"}[1m])\n) by (container)",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Pod Replicas",
   "type": "timeseries",
   "description": "The number of pod replicas for the service.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count(\n  label_replace(kube_pod_info{pod=~\"$service-.+\", pod!~\"$service(-api|-ui).+\", namespace=\"$namespace\"}, \"pod\", \"$1\", \"created_by_name\", \"(.*)-\\\\w+\")\n) by (pod)",
     "legendFormat": "{{ created_by_name }}"
    }
   ]
  },
  {
   "title": "Pod Restarts",
   "type": "timeseries",
   "description": "This chart shows the count of pod/container restart events observed.  This will show \"CrashLooping\" error events.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (pod) (increase(kube_pod_container_status_restarts_total{namespace=\"$namespace\", pod=~\"$service-.*\", pod!~\"$service(-api|-ui).+\"}[10m])) > 0",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Non-Ready Pods",
   "type": "timeseries",
   "description": "This chart shows the count of pods in an \"non-ready\" state.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (pod) (\n  kube_pod_status_phase{namespace=\"$namespace\", pod=~\"$service-.*\", pod!~\"$service(-api|-ui).+\", phase=~\"Pending|Unknown\"}\n) > 0",
     "legendFormat": "{{ pod }}"
    }
   ]
  }
 ]
}