{
 "title": "Thanos overview",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Thanos Compactor -- compaction backlog",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(thanos_compact_todo_compactions)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Thanos Compactor -- downsample backlog",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(thanos_compact_todo_downsample_blocks)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Thanos Compactor -- compaction block backlog",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(thanos_compact_todo_compaction_blocks)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Thanos Compactor -- number of concurrent cleanup loops of partially uploaded blocks and marked blocks that were executed successfully",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(thanos_compact_block_cleanup_loops_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Thanos Compactor -- number of blocks deleted in compactor",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(thanos_compact_blocks_cleaned_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Thanos Compactor -- failures encountered while deleting blocks in compactor",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(thanos_compact_block_cleanup_failures_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Thanos Compactor -- number of blocks marked in compactor",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(thanos_compact_blocks_marked_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Thanos Compactor -- number of blocks marked for deletion by compactor",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(thanos_compact_garbage_collected_blocks_total)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}