---
apiVersion: v1
kind: LimitRange
metadata:
  name: limitrange
  namespace: hmpps-github-actions-runners-security
spec:
  limits:
    - default:
        cpu: 200m
        memory: 2Gi
      defaultRequest:
        cpu: 200m
        memory: 2Gi
      type: Container
