apiVersion: v1
kind: Namespace
metadata:
  name: "stevec-dev"
  labels:
    cloud-platform.justice.gov.uk/is-production: "false"
    cloud-platform.justice.gov.uk/environment-name: "development"
    pod-security.kubernetes.io/enforce: restricted
  annotations:
    cloud-platform.justice.gov.uk/business-unit: "HMPPS"
    cloud-platform.justice.gov.uk/slack-channel: "hmpps-prisons-sre"
    cloud-platform.justice.gov.uk/application: "Steve C (SRE) Playground"
    cloud-platform.justice.gov.uk/owner: "HMPPS SRE: steve.calcott@justice.gov.uk"
    cloud-platform.justice.gov.uk/source-code: "https://github.com/ministryofjustice/stevec-sre-playground"
    cloud-platform.justice.gov.uk/team-name: "hmpps-sre"
    cloud-platform.justice.gov.uk/review-after: "2026-09-17"
