{
 "title": "LAA CCMS User API Dashboard prod",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "API Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Running Pods",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_info{namespace='laa-ccms-user-management-api-prod'})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Message Processing Stats per Hour",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 18, "x": 6, "y": 1 },
   "targets": [
    {
     "expr": "sum by (status) (\n  increase(\n    sqs_messages_processed_total{\n      application=\"ccms-user-api-app\",\n      namespace=\"laa-ccms-user-management-api-prod\"\n    }[1h]\n  )\n)",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Unauthorised Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by(namespace) (increase(http_server_requests_seconds_count{namespace=\"laa-ccms-user-management-api-prod\", status=\"401\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests Per Team",
   "type": "timeseries",
   "description": "Number of requests made by each team",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "targets": [
    {
     "expr": "sum by(team) (increase(requests_by_team_total{namespace='laa-ccms-user-management-api-prod'}[$__rate_interval])) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Per Pod reqeusts",
   "type": "timeseries",
   "description": "The number of requests made to pod , irrespective of the return status code",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "targets": [
    {
     "expr": "sum by(instance) (increase(http_server_requests_seconds_count{namespace='laa-ccms-user-management-api-prod'}[$__rate_interval])) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Response Time",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(uri) (rate(http_server_requests_seconds_sum{namespace=\"laa-ccms-user-management-api-prod\", uri!~\".*actuator.*|.*swagger.*|.*v3.*|.*providers.*\"}[1m])) / sum by(uri) (rate(http_server_requests_seconds_count{namespace=\"laa-ccms-user-management-api-prod\", uri!~\".*actuator.*|.*swagger.*|.*v3.*|.*providers.*\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Max Response Times",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max by(uri) (http_server_requests_seconds_max{namespace='laa-ccms-user-management-api-prod', uri!~'.*actuator.*|.*swagger.*|.*v3.*'}) ",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "JVM Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Eden Space Stats (MB)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{namespace='laa-ccms-user-management-api-prod',area='heap',id='Eden Space'}/1000000",
     "legendFormat": "Used Eden Space"
    },
    {
     "expr": "jvm_memory_max_bytes{namespace='laa-ccms-user-management-api-prod',area='heap',id='Eden Space'}/1000000",
     "legendFormat": "Max Eden Space"
    },
    {
     "expr": "100 * ( jvm_memory_used_bytes{namespace='laa-ccms-user-management-api-prod',area='heap',id='Eden Space'}) / (jvm_memory_max_bytes{namespace='laa-ccms-user-management-api-prod',area='heap',id='Eden Space'})",
     "legendFormat": "Eden Space %"
    }
   ]
  },
  {
   "title": "Survivor Space Stats (MB)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{namespace='laa-ccms-user-management-api-prod',area='heap',id='Survivor Space'}/1000000",
     "legendFormat": "Used Survivor Space"
    },
    {
     "expr": "jvm_memory_max_bytes{namespace='laa-ccms-user-management-api-prod',area='heap',id='Survivor Space'}/1000000",
     "legendFormat": "Max Survivor Space"
    },
    {
     "expr": "100 * ( jvm_memory_used_bytes{namespace='laa-ccms-user-management-api-prod',area='heap',id='Survivor Space'}) / (jvm_memory_max_bytes{namespace='laa-ccms-user-management-api-prod',area='heap',id='Survivor Space'})",
     "legendFormat": "Survivor Space %"
    }
   ]
  },
  {
   "title": "Tenured Gen Space Stats (MB)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{namespace='laa-ccms-user-management-api-prod',area='heap',id='Tenured Gen'}/1000000",
     "legendFormat": "Used Tenured Gen Space"
    },
    {
     "expr": "jvm_memory_max_bytes{namespace='laa-ccms-user-management-api-prod',area='heap',id='Tenured Gen'}/1000000",
     "legendFormat": "Max Tenured Gen Space"
    },
    {
     "expr": "100 * ( jvm_memory_used_bytes{namespace='laa-ccms-user-management-api-prod',area='heap',id='Tenured Gen'}) / (jvm_memory_max_bytes{namespace='laa-ccms-user-management-api-prod',area='heap',id='Tenured Gen'})",
     "legendFormat": "Tenured Gen Space %"
    }
   ]
  },
  {
   "title": "DB Connection Stats",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "hikaricp_connections_max{namespace=\"laa-ccms-user-management-api-prod\"}",
     "legendFormat": "Max Connections"
    },
    {
     "expr": "hikaricp_connections_min{namespace=\"laa-ccms-user-management-api-prod\"}\n",
     "legendFormat": "Min Connections"
    },
    {
     "expr": "hikaricp_connections_active{namespace=\"laa-ccms-user-management-api-prod\"}",
     "legendFormat": "Active Connections"
    },
    {
     "expr": "hikaricp_connections_idle{namespace=\"laa-ccms-user-management-api-prod\"}",
     "legendFormat": "Idle Connections"
    },
    {
     "expr": "hikaricp_connections_pending{namespace=\"laa-ccms-user-management-api-prod\"}",
     "legendFormat": "Pending Connections"
    }
   ]
  }
 ]
}