apiVersion: v1
kind: Namespace
metadata:
  name: "london-task-force-dev"
  labels:
    cloud-platform.justice.gov.uk/is-production: "false"
    cloud-platform.justice.gov.uk/environment-name: "development"
    pod-security.kubernetes.io/enforce: restricted
  annotations:
    cloud-platform.justice.gov.uk/business-unit: "HQ"
    cloud-platform.justice.gov.uk/slack-channel: "ltf-dev-team"
    cloud-platform.justice.gov.uk/application: "london-task-force"
    cloud-platform.justice.gov.uk/owner: "London Task Force: eunan.hardy@justice.gov.uk"
    cloud-platform.justice.gov.uk/source-code: "https://github.com/ministryofjustice/performance-information-intelligence-system-demo"
    cloud-platform.justice.gov.uk/team-name: "ltf-dev-team"
    cloud-platform.justice.gov.uk/review-after: ""
