kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: support-for-additional-needs-prototype-admin
  namespace: support-for-additional-needs-prototype
subjects:
  - kind: Group
    name: "github:hmpps-farsight-reduce-re-offend-prototype"
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
