apiVersion: v1
kind: Namespace
metadata:
  name: "opg-investigations-risk-webapp-dev"
  labels:
    cloud-platform.justice.gov.uk/is-production: "false"
    cloud-platform.justice.gov.uk/environment-name: "development"
    pod-security.kubernetes.io/enforce: restricted
  annotations:
    cloud-platform.justice.gov.uk/business-unit: "HQ"
    cloud-platform.justice.gov.uk/slack-channel: "opg-deds"
    cloud-platform.justice.gov.uk/application: "OPG Investigations Risk Webapp"
    cloud-platform.justice.gov.uk/owner: "Data Engineering, Data Science and AI: justicedataplatform@justice.gov.uk"
    cloud-platform.justice.gov.uk/source-code: "https://github.com/ministryofjustice/opg-investigations-risk-webapp"
    cloud-platform.justice.gov.uk/team-name: "opg-investigations-risk-webapp-admins"
    cloud-platform.justice.gov.uk/review-after: ""
