kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: opg-investigations-risk-webapp-dev-admin
  namespace: opg-investigations-risk-webapp-dev
subjects:
  - kind: Group
    name: "github:opg-investigations-risk-webapp-admins"
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
