kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: mandatory-drug-testing-prod-admin
  namespace: mandatory-drug-testing-prod
subjects:
  - kind: Group
    name: "github:hmpps-move-and-improve-squad-3-live"
    apiGroup: rbac.authorization.k8s.io
  - kind: Group
    name: "github:hmpps-sre"
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
