{
 "title": "Prisoner Content Hub",
 "tags": [ "prisoner-content-hub" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(kube_deployment_metadata_generation, namespace)"
   }
  ]
 },
 "panels": [
  {
   "title": "Average Requests/s",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Requests" }
   ],
   "targets": [
    {
     "expr": "avg(sum by (ingress) (rate(nginx_ingress_controller_requests{exported_namespace='$namespace'}[5m]))) by (ingress)",
     "legendFormat": "{{ingress}}"
    }
   ]
  },
  {
   "title": "Replication Count",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "max(kube_deployment_status_replicas{namespace='$namespace'}) by (deployment)",
     "legendFormat": "{{deployment}}-actual"
    },
    {
     "expr": "max(kube_deployment_spec_replicas{namespace='$namespace'}) by (deployment)",
     "legendFormat": "{{deployment}}-desired"
    }
   ]
  },
  {
   "title": "Average Request Time (s)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(rate(nginx_ingress_controller_request_duration_seconds_sum{exported_namespace='$namespace'}[5m]) / rate(nginx_ingress_controller_request_duration_seconds_count{exported_namespace='$namespace'}[5m]) > 0) by (ingress)\n",
     "legendFormat": "{{ingress}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short", "label": "CPU Time (s)" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace='$namespace',container!=\"POD\",container!=\"\"}[5m])) by (container)",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Average Bytes Sent",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short", "label": "Bytes" }
   ],
   "targets": [
    {
     "expr": "avg(sum by (ingress) (rate(nginx_ingress_controller_bytes_sent_sum{exported_namespace='$namespace'}[5m]))) by (ingress)",
     "legendFormat": "{{ingress}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short", "label": "Memory Usage (MB)" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_memory_usage_bytes{namespace='$namespace',container!=\"POD\",container!=\"\"}[5m]) / 1024 / 1024) by (container)",
     "legendFormat": "{{container}}"
    }
   ]
  }
 ]
}
{
 "title": "Prisoner Content Hub OpenSearch",
 "tags": [ "prisoner-content-hub" ],
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Cluster status",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "aws_es_cluster_status_green_average{domain_name=\"cloud-platform-38800316\"}",
     "legendFormat": "{{domain_name}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Memory Usage" }
   ],
   "targets": [
    {
     "expr": "aws_es_jvmmemory_pressure_average{domain_name=\"cloud-platform-38800316\"}",
     "legendFormat": "{{domain_name}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short", "label": "CPU Usage" }
   ],
   "targets": [
    {
     "expr": "aws_es_cpuutilization_average{domain_name=\"cloud-platform-38800316\"}",
     "legendFormat": "{{domain_name}}"
    }
   ]
  },
  {
   "title": "Free storage space",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "decmbytes", "label": "Free storage space (MB)" }
   ],
   "targets": [
    {
     "expr": "aws_es_free_storage_space_average{domain_name=\"cloud-platform-38800316\"}",
     "legendFormat": "{{domain_name}}"
    }
   ]
  }
 ]
}
{
 "title": "Prisoner Content Hub Production RDS",
 "tags": [ "prisoner-content-hub" ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "RDS Average Storage Space",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "decbytes", "label": "Storage Space" }
   ],
   "targets": [
    {
     "expr": "aws_rds_free_storage_space_average{dbinstance_identifier=\"cloud-platform-08a8cf9e6f678214\"}",
     "legendFormat": "{{dbinstance_identifier}}"
    }
   ]
  },
  {
   "title": "RDS Average CPU utilization",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "percent", "label": "CPU utilization" }
   ],
   "targets": [
    {
     "expr": "aws_rds_cpuutilization_average{dbinstance_identifier=\"cloud-platform-08a8cf9e6f678214\"}",
     "legendFormat": "{{dbinstance_identifier}}"
    }
   ]
  },
  {
   "title": "RDS Read IOPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "aws_rds_read_iops_sum{dbinstance_identifier=\"cloud-platform-08a8cf9e6f678214\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RDS Write IOPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "aws_rds_write_iops_sum{dbinstance_identifier=\"cloud-platform-08a8cf9e6f678214\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RDS Database Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "aws_rds_database_connections_sum{dbinstance_identifier=\"cloud-platform-08a8cf9e6f678214\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}