apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: laa-civil-manage-dev-service-monitor
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: laa-civil-manage
  endpoints:
    - port: http
      interval: 15s