apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  namespace: laa-civil-manage-dev
  labels:
    role: alert-rules
  name: prometheus-custom-rules-laa-civil-manage-dev
spec:
  groups:
  - name: application-rules
    rules:
    
    - alert: NoPodsRunning
      expr: sum(kube_pod_status_phase{namespace="laa-civil-manage-dev", phase="Running"}) == 0 or absent(kube_pod_status_phase{namespace="laa-civil-manage-dev", phase="Running"})
      for: 5m
      labels:
        severity: laa-civil-manage-dev
      annotations:
        message: "CRITICAL: There are zero running pods in the laa-civil-manage-dev namespace."

    - alert: PodCrashLooping
      expr: kube_pod_container_status_waiting_reason{namespace="laa-civil-manage-dev", reason="CrashLoopBackOff"} > 0
      for: 10m
      labels:
        severity: laa-civil-manage-dev
      annotations:
        message: "Warning: a pod in namespace {{ $labels.namespace }} has been in CrashLoopBackOff for over 10 minutes."

    - alert: HighHttp5xxErrorRate
      expr: sum(rate(http_request_duration_seconds_count{namespace="laa-civil-manage-dev", status_code=~"5.."}[5m])) / sum(rate(http_request_duration_seconds_count{namespace="laa-civil-manage-dev"}[5m])) > 0.05
      for: 5m
      labels:
        severity: laa-civil-manage-dev
      annotations:
        message: "CRITICAL: The 5xx error rate in {{ $labels.namespace }} has exceeded 5% for the last 5 minutes."