kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: sop-derived-organogram-dev-admin
  namespace: sop-derived-organogram-dev
subjects:
  - kind: Group
    name: "github:sop-derived-organogram"
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
