apiVersion: v1
kind: Namespace
metadata:
  name: pfl-analytics-staging
  labels:
    cloud-platform.justice.gov.uk/is-production: "false"
    cloud-platform.justice.gov.uk/environment-name: "staging"
    pod-security.kubernetes.io/enforce: restricted
  annotations:
    cloud-platform.justice.gov.uk/business-unit: "HQ"
    cloud-platform.justice.gov.uk/slack-channel: "cdpt-care-arrangement-plan"
    cloud-platform.justice.gov.uk/application: "PFL Analytics"
    cloud-platform.justice.gov.uk/owner: "Central Digital Product Team: central-digital-product-team@justice.gov.uk"
    cloud-platform.justice.gov.uk/source-code: "https://github.com/ministryofjustice/pfl-analytics"
    cloud-platform.justice.gov.uk/team-name: "central-digital-product-team"
    cloud-platform.justice.gov.uk/review-after: "2027-03-20"

# This file is managed by Terraform. Manual changes will be overwritten. Please edit the Terraform configuration instead.