kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: yjb-platform-dev-admin
  namespace: yjb-platform-dev
subjects:
  - kind: Group
    name: "github:yjb-dev-team"
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
