---
apiVersion: v1
kind: LimitRange
metadata:
  name: limitrange
  namespace: hmpps-github-actions-runners
spec:
  limits:
    - default:
        cpu: 2000m
        memory: 16Gi
      defaultRequest:
        cpu: 2000m
        memory: 16Gi
      type: Container
