---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: hmpps-parom-service-api-cert
  namespace: hmpps-parom-service-prod
spec:
  secretName: hmpps-parom-service-api-cert
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames:
    - parom-service-api-prod.hmpps.service.justice.gov.uk
    - '*.parom-service-api-prod.hmpps.service.justice.gov.uk'

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: hmpps-parom-service-ui-cert
  namespace: hmpps-parom-service-prod
spec:
  secretName: hmpps-parom-service-ui-cert
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames:
    - parom-service-ui-prod.hmpps.service.justice.gov.uk
    - '*.parom-service-ui-prod.hmpps.service.justice.gov.uk'
