{
 "title": "Datahub report system performance",
 "time": { "from": "now-4d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "report_id",
    "query": {
     "query": "label_values(single_query_metric_count{namespace=\"hmpps-datahub-query-metrics-prod\"},report_id)"
    }
   },
   {
    "name": "variant",
    "label": "Variant",
    "query": {
     "query": "label_values(single_query_metric_count{namespace=\"hmpps-datahub-query-metrics-prod\"},variant_id)"
    }
   },
   {
    "name": "report_variant_id",
    "label": "Report-Variant id",
    "query": {
     "query": "query_result(sum by (unique_output_port_id) (  increase(    single_query_metric_count{      namespace=\"hmpps-datahub-query-metrics-prod\"    }[24h]  )) > 0)"
    }
   },
   {
    "name": "domain_prefix",
    "label": "Domain prefix",
    "query": {
     "query": "query_result(sum by (unique_output_port_id) (  increase(    single_query_metric_count{      namespace=\"hmpps-datahub-query-metrics-prod\"    }[24h]  )) > 0)"
    }
   },
   {
    "name": "query_engine",
    "query": {
     "query": "label_values(single_query_metric_count{namespace=\"hmpps-datahub-query-metrics-prod\"},query_engine)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Report performance last 24h - variants",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Report Performance Trend - $report_variant_id",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 1 },
     "repeat": "report_variant_id",
     "fieldConfig": { "defaults": { "unit": "suffix: s" } },
     "targets": [
      {
       "expr": "sum by (unique_output_port_id) (increase(single_query_metric_sum{namespace=\"hmpps-datahub-query-metrics-prod\",unique_output_port_id=\"$report_variant_id\"}[24h])) / sum by (unique_output_port_id) (increase(single_query_metric_count{namespace=\"hmpps-datahub-query-metrics-prod\",unique_output_port_id=\"$report_variant_id\"}[24h]))",
       "legendFormat": "{{variant_id}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Report performance per query_engine",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 }
  },
  {
   "title": "Report Performance Trend - $query_engine",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 2 },
   "repeat": "query_engine",
   "fieldConfig": { "defaults": { "unit": "suffix: s" } },
   "targets": [
    {
     "expr": "sum(\n  increase(\n    single_query_metric_sum{\n      namespace=\"hmpps-datahub-query-metrics-prod\",\n      query_engine=\"$query_engine\"\n    }[24h]\n  )\n)\n/\nsum(\n  increase(\n    single_query_metric_count{\n      namespace=\"hmpps-datahub-query-metrics-prod\",\n      query_engine=\"$query_engine\"\n    }[24h]\n  )\n)",
     "legendFormat": "{{variant_id}}"
    }
   ]
  },
  {
   "title": "Report performance per domain",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "Report Performance Trend - $domain_prefix",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 211 },
     "repeat": "domain_prefix",
     "fieldConfig": { "defaults": { "unit": "suffix: s" } },
     "targets": [
      {
       "expr": "sum(\n  increase(\n    single_query_metric_sum{\n      namespace=\"hmpps-datahub-query-metrics-prod\",\n      unique_output_port_id=~\"${domain_prefix}_.*\"\n    }[24h]\n  )\n)\n/\nsum(\n  increase(\n    single_query_metric_count{\n      namespace=\"hmpps-datahub-query-metrics-prod\",\n      unique_output_port_id=~\"${domain_prefix}_.*\"\n    }[24h]\n  )\n)",
       "legendFormat": "{{variant_id}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Report performance - variants",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "Report Performance Trend - $report_variant_id",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 222 },
     "repeat": "report_variant_id",
     "fieldConfig": { "defaults": { "unit": "suffix: s" } },
     "targets": [
      {
       "expr": "avg_over_time(\n  (\n    single_query_metric_sum{\n      namespace=\"hmpps-datahub-query-metrics-prod\",\n      unique_output_port_id=\"$report_variant_id\"\n    }\n    /\n    single_query_metric_count{\n      namespace=\"hmpps-datahub-query-metrics-prod\",\n      unique_output_port_id=\"$report_variant_id\"\n    }\n  )[24h:]\n)",
       "legendFormat": "{{variant_id}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Report regression ratio - variants (24h vs last 30d, >1 = worse)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "Regression Ratio - $report_variant_id",
     "type": "stat",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 223 },
     "repeat": "report_variant_id",
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(\n  (\n    sum by (unique_output_port_id) (\n      increase(single_query_metric_sum{\n        namespace=\"hmpps-datahub-query-metrics-prod\",\n        unique_output_port_id=\"$report_variant_id\"\n      }[24h])\n    )\n    /\n    sum by (unique_output_port_id) (\n      increase(single_query_metric_count{\n        namespace=\"hmpps-datahub-query-metrics-prod\",\n        unique_output_port_id=\"$report_variant_id\"\n      }[24h])\n    )\n  )\n  /\n  (\n    sum by (unique_output_port_id) (\n      increase(single_query_metric_sum{\n        namespace=\"hmpps-datahub-query-metrics-prod\",\n        unique_output_port_id=\"$report_variant_id\"\n      }[30d])\n    )\n    /\n    sum by (unique_output_port_id) (\n      increase(single_query_metric_count{\n        namespace=\"hmpps-datahub-query-metrics-prod\",\n        unique_output_port_id=\"$report_variant_id\"\n      }[30d])\n    )\n  )\n)\nand\n(\n  sum by (unique_output_port_id) (\n    increase(single_query_metric_count{\n      namespace=\"hmpps-datahub-query-metrics-prod\",\n      unique_output_port_id=\"$report_variant_id\"\n    }[24h])\n  ) > 0\n)"
      }
     ]
    }
   ]
  },
  {
   "title": "Success percentage - variants",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "Panel Title - $report_variant_id",
     "type": "stat",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 224 },
     "repeat": "report_variant_id",
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(\n  sum(\n    increase(\n      single_query_metric_count{\n        namespace=\"hmpps-datahub-query-metrics-prod\",\n        unique_output_port_id=\"$report_variant_id\",\n        state=\"SUCCEEDED\"\n      }[$__range]\n    )\n  )\n  /\n  clamp_min(\n    sum(\n      increase(\n        single_query_metric_count{\n          namespace=\"hmpps-datahub-query-metrics-prod\",\n          unique_output_port_id=\"$report_variant_id\"\n        }[$__range]\n      )\n    ),\n    1\n  )\n)\nand\n(\n  sum(\n    increase(\n      single_query_metric_count{\n        namespace=\"hmpps-datahub-query-metrics-prod\",\n        unique_output_port_id=\"$report_variant_id\"\n      }[$__range]\n    )\n  ) > 0\n)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}