---
apiVersion: v1
kind: Namespace
metadata:
  name: hmpps-sre-observability-prod
  labels:
    cloud-platform.justice.gov.uk/is-production: "true"
    cloud-platform.justice.gov.uk/environment-name: "production"
    pod-security.kubernetes.io/enforce: restricted
  annotations:
    cloud-platform.justice.gov.uk/business-unit: "HMPPS"
    cloud-platform.justice.gov.uk/slack-channel: "hmpps-digital-sre"
    cloud-platform.justice.gov.uk/slack-alert-channel: "hmpps-sre-alerts-prod"
    cloud-platform.justice.gov.uk/application: "HMPPS SRE Observability Apps"
    cloud-platform.justice.gov.uk/owner: "HMPPS SRE: HMPPSSRE@JusticeUK.onmicrosoft.com"
    cloud-platform.justice.gov.uk/source-code: "https://github.com/ministryofjustice/health-kick/"
    cloud-platform.justice.gov.uk/team-name: "hmpps-sre"
