---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: monitoring-tls
  namespace: data-platform-monitoring-production
spec:
  secretName: monitoring-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames:
    - monitoring.data-platform.service.justice.gov.uk
