{
 "title": "contact-moj production",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Currently Active",
   "type": "table",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "max(kube_deployment_status_replicas_available{namespace=\"contact-moj-production\"}) by (deployment)"
    },
    {
     "expr": "max(kube_deployment_spec_replicas{namespace=\"contact-moj-production\"}) by (deployment)"
    }
   ]
  },
  {
   "title": "HTTP Status Codes",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(nginx_ingress_controller_requests{exported_namespace = \"contact-moj-production\"}[$__interval])) by (status)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Average Request Duration",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(rate(nginx_ingress_controller_request_duration_seconds_sum{exported_namespace = \"contact-moj-production\"}[$__interval]) / rate(nginx_ingress_controller_request_duration_seconds_count{exported_namespace = \"contact-moj-production\"}[$__interval]) > 0)",
     "legendFormat": "Requests"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "description": "Resource dashboard: https://grafana.live.cloud-platform.service.justice.gov.uk/d/a164a7f0339f99e89cea5cb47e9be617/kubernetes-compute-resources-workload?var-namespace=contact-moj-production",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (pod_name)(rate(container_cpu_usage_seconds_total{namespace='contact-moj-production'}[$__interval]))",
     "legendFormat": "Pod: {{pod_name}}"
    },
    {
     "expr": "avg(kube_pod_container_resource_requests_cpu_cores{namespace='contact-moj-production'})  ",
     "legendFormat": "Requested (soft limit)"
    },
    {
     "expr": "avg(kube_pod_container_resource_limits_cpu_cores{namespace='contact-moj-production'})",
     "legendFormat": "Limit (Hard Limit)"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "description": "Resource dashboard: https://grafana.live.cloud-platform.service.justice.gov.uk/d/a164a7f0339f99e89cea5cb47e9be617/kubernetes-compute-resources-workload?var-namespace=contact-moj-production",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by(pod_name)(container_memory_usage_bytes{namespace='contact-moj-production'})",
     "legendFormat": "Pod: {{pod_name}}"
    },
    {
     "expr": "avg(kube_pod_container_resource_requests_memory_bytes{namespace='contact-moj-production'})",
     "legendFormat": "Requested (soft limit)"
    },
    {
     "expr": "avg(kube_pod_container_resource_limits_memory_bytes{namespace='contact-moj-production'})",
     "legendFormat": "Limit (Hard Limit)"
    }
   ]
  }
 ]
}