apiVersion: v1
kind: Namespace
metadata:
  name: "srrc-preprod"
  labels:
    cloud-platform.justice.gov.uk/is-production: "false"
    cloud-platform.justice.gov.uk/environment-name: "staging"
    pod-security.kubernetes.io/enforce: restricted
  annotations:
    cloud-platform.justice.gov.uk/business-unit: "Central Digital"
    cloud-platform.justice.gov.uk/slack-channel: "srrc-tech"
    cloud-platform.justice.gov.uk/application: "Verify biometric scans api for SRRC"
    cloud-platform.justice.gov.uk/owner: "srrc-tech: scott.davey@justice.gov.uk"
    cloud-platform.justice.gov.uk/source-code: "https://github.com/ministryofjustice/srrc-verify-biometric-scans-api"
    cloud-platform.justice.gov.uk/team-name: "srrc-tech"
    cloud-platform.justice.gov.uk/review-after: ""
