apiVersion: v1
kind: Namespace
metadata:
  name: "srrc-dev"
  labels:
    cloud-platform.justice.gov.uk/is-production: "false"
    cloud-platform.justice.gov.uk/environment-name: "development"
    pod-security.kubernetes.io/enforce: restricted
  annotations:
    cloud-platform.justice.gov.uk/business-unit: "Central Digital"
    cloud-platform.justice.gov.uk/slack-channel: "srrc-tech"
    cloud-platform.justice.gov.uk/application: "Safer reception and release from custody"
    cloud-platform.justice.gov.uk/owner: "srrc-tech: srrc-tech@justice.gov.uk"
    cloud-platform.justice.gov.uk/source-code: "https://github.com/ministryofjustice/srrc"
    cloud-platform.justice.gov.uk/team-name: "srrc-tech"
    cloud-platform.justice.gov.uk/review-after: "2026-09-03"
