---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: hmpps-datahub-query-metrics-cert
  namespace: hmpps-datahub-query-metrics-dev
spec:
  secretName: hmpps-datahub-query-metrics-cert
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames:
    - datahub-query-metrics-dev.hmpps.service.justice.gov.uk
    - '*.datahub-query-metrics-dev.hmpps.service.justice.gov.uk'
