{
 "title": "HMPPS EMS Production",
 "tags": [
  "aws",
  "kubernetes",
  "hmpps-ems-prod"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "aws_region", "label": "AWS Region", "query": "regions()" },
   {
    "name": "aws_rds_db_id",
    "label": "AWS RDS Database Identifier",
    "query": "dimension_values($aws_region, AWS/RDS, CPUUtilization, DBInstanceIdentifier)"
   },
   {
    "name": "kube_ns",
    "label": "Kubernetes Namespace",
    "query": "label_values(kube_namespace_labels, namespace)"
   },
   {
    "name": "kube_deployment",
    "label": "Kubernetes Deployment",
    "query": "label_values(kube_deployment_labels, deployment)"
   },
   {
    "name": "kube_pod",
    "label": "Kubernetes Pod",
    "query": "label_values(kube_pod_labels, label_app)"
   },
   {
    "name": "kube_ingress",
    "label": "Kubernetes Ingress",
    "query": "label_values(nginx_ingress_controller_requests, exported_namespace)"
   }
  ]
 },
 "panels": [
  { "title": "AWS RDS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Utilisation",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "Average CPU Utilisation",
     "dimensions": { "DBInstanceIdentifier": "$aws_rds_db_id" },
     "metricName": "CPUUtilization",
     "namespace": "AWS/RDS",
     "region": "$aws_region",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Database Connections",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "Average Database Connections",
     "dimensions": { "DBInstanceIdentifier": "$aws_rds_db_id" },
     "metricName": "DatabaseConnections",
     "namespace": "AWS/RDS",
     "region": "$aws_region",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Freeable Memory | Free Storage Space",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "Average Freeable Memory",
     "dimensions": { "DBInstanceIdentifier": "$aws_rds_db_id" },
     "metricName": "FreeableMemory",
     "namespace": "AWS/RDS",
     "region": "$aws_region",
     "statistics": [ "Average" ]
    },
    {
     "alias": "Average Free Storage Space",
     "dimensions": { "DBInstanceIdentifier": "$aws_rds_db_id" },
     "metricName": "FreeStorageSpace",
     "namespace": "AWS/RDS",
     "region": "$aws_region",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Read IOPS | Write IOPS",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "Average Read IOPS",
     "dimensions": { "DBInstanceIdentifier": "$aws_rds_db_id" },
     "metricName": "ReadIOPS",
     "namespace": "AWS/RDS",
     "region": "$aws_region",
     "statistics": [ "Average" ]
    },
    {
     "alias": "Average Write IOPS",
     "dimensions": { "DBInstanceIdentifier": "$aws_rds_db_id" },
     "metricName": "WriteIOPS",
     "namespace": "AWS/RDS",
     "region": "$aws_region",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Read IOPS | Write IOPS",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "Average Read IOPS",
     "dimensions": { "DBInstanceIdentifier": "$aws_rds_db_id" },
     "metricName": "ReadIOPS",
     "namespace": "AWS/RDS",
     "region": "$aws_region",
     "statistics": [ "Average" ]
    },
    {
     "alias": "Average Write IOPS",
     "dimensions": { "DBInstanceIdentifier": "$aws_rds_db_id" },
     "metricName": "WriteIOPS",
     "namespace": "AWS/RDS",
     "region": "$aws_region",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Read Latency | Write Latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "alias": "Average Read Latency",
     "dimensions": { "DBInstanceIdentifier": "$aws_rds_db_id" },
     "metricName": "ReadLatency",
     "namespace": "AWS/RDS",
     "region": "$aws_region",
     "statistics": [ "Average" ]
    },
    {
     "alias": "Average Write Latency",
     "dimensions": { "DBInstanceIdentifier": "$aws_rds_db_id" },
     "metricName": "WriteLatency",
     "namespace": "AWS/RDS",
     "region": "$aws_region",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Read Throughput | Write Throughput",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "Average Read Throughput",
     "dimensions": { "DBInstanceIdentifier": "$aws_rds_db_id" },
     "metricName": "ReadThroughput",
     "namespace": "AWS/RDS",
     "region": "$aws_region",
     "statistics": [ "Average" ]
    },
    {
     "alias": "Average Write Throughput",
     "dimensions": { "DBInstanceIdentifier": "$aws_rds_db_id" },
     "metricName": "WriteThroughput",
     "namespace": "AWS/RDS",
     "region": "$aws_region",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Network Rx Throughput | Network Tx Throughput",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "Average Network Rx Throughput",
     "dimensions": { "DBInstanceIdentifier": "$aws_rds_db_id" },
     "metricName": "NetworkReceiveThroughput",
     "namespace": "AWS/RDS",
     "region": "$aws_region",
     "statistics": [ "Average" ]
    },
    {
     "alias": "Average Network Tx Throughput",
     "dimensions": { "DBInstanceIdentifier": "$aws_rds_db_id" },
     "metricName": "NetworkTransmitThroughput",
     "namespace": "AWS/RDS",
     "region": "$aws_region",
     "statistics": [ "Average" ]
    }
   ]
  },
  { "title": "Kubernetes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "title": "Ingress Requests",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_requests{exported_namespace = \"hmpps-ems-prod\", ingress = \"grafana-prod\"}[5m]))",
     "legendFormat": "req / s"
    }
   ]
  },
  {
   "title": "Ingress Request HTTP Codes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_requests{exported_namespace = \"hmpps-ems-prod\", ingress = \"grafana-prod\"}[5m])) by (status)"
    }
   ]
  },
  {
   "title": "Ingress Average Request Duration",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(rate(nginx_ingress_controller_request_duration_seconds_sum{exported_namespace = \"hmpps-ems-prod\", ingress = \"grafana-prod\"}[5m]) / rate(nginx_ingress_controller_request_duration_seconds_count{exported_namespace = \"hmpps-ems-prod\", ingress = \"grafana-prod\"}[5m]) > 0)"
    }
   ]
  },
  {
   "title": "Ingress Request Duration Quantiles",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 47 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(nginx_ingress_controller_request_duration_seconds_bucket{exported_namespace = \"hmpps-ems-prod\", ingress = \"grafana-prod\"}[5m])) by (le))",
     "legendFormat": "0.95"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(nginx_ingress_controller_request_duration_seconds_bucket{exported_namespace = \"hmpps-ems-prod\", ingress = \"grafana-prod\"}[5m])) by (le))",
     "legendFormat": "0.90"
    },
    {
     "expr": "histogram_quantile(0.70, sum(rate(nginx_ingress_controller_request_duration_seconds_bucket{exported_namespace = \"hmpps-ems-prod\", ingress = \"grafana-prod\"}[5m])) by (le))",
     "legendFormat": "0.70"
    }
   ]
  },
  {
   "title": "Deployment Replicas",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kube_deployment_spec_replicas{namespace=\"hmpps-ems-prod\",deployment=\"grafana-prod\"}",
     "legendFormat": "Requested Replicas"
    },
    {
     "expr": "kube_deployment_status_replicas_available{namespace=\"hmpps-ems-prod\",deployment=\"grafana-prod\"}",
     "legendFormat": "Available Replicas"
    }
   ]
  },
  {
   "title": "Container Readiness",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kube_pod_container_status_ready{namespace=\"hmpps-ems-prod\",container=\"grafana\"}",
     "legendFormat": "Grafana"
    },
    {
     "expr": "kube_pod_container_status_ready{namespace=\"hmpps-ems-prod\",container=\"renderer\"}",
     "legendFormat": "Renderer"
    }
   ]
  }
 ]
}