{
 "title": "LAA Status Dashboard",
 "tags": [ "laa-status-dashboard" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kube_deployment_metadata_generation, namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Service Dashboard",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Average requests/s",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "Requests" }
   ],
   "targets": [
    {
     "expr": "avg(sum by (ingress) (rate(nginx_ingress_controller_requests{exported_namespace='$namespace'}[5m]))) by (ingress)",
     "legendFormat": "{{ingress}}"
    }
   ]
  },
  {
   "title": "Response Codes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(sum by (ingress, status) (rate(nginx_ingress_controller_requests{exported_namespace='$namespace'}[1m]))) by (ingress, status)",
     "legendFormat": "{{status}} - {{ingress}}"
    }
   ]
  },
  {
   "title": "Average Request Time (s)",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(rate(nginx_ingress_controller_request_duration_seconds_sum{exported_namespace='$namespace'}[5m]) / rate(nginx_ingress_controller_request_duration_seconds_count{exported_namespace='$namespace'}[5m]) > 0) by (ingress)",
     "legendFormat": "{{ingress}}"
    }
   ]
  },
  {
   "title": "Replication Count",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "max(kube_deployment_status_replicas{namespace='$namespace'}) by (deployment)",
     "legendFormat": "{{deployment}}-actual"
    },
    {
     "expr": "max(kube_deployment_spec_replicas{namespace='$namespace'}) by (deployment)",
     "legendFormat": "{{deployment}}-desired"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short", "label": "Memory Usage (MB)" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_memory_usage_bytes{namespace='$namespace',container!=\"POD\",container!=\"\"}[5m]) / 1024 / 1024) by (container)",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "short", "label": "CPU Time (s)" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace='$namespace',container!=\"POD\",container!=\"\"}[5m])) by (container)",
     "legendFormat": "{{container}}"
    }
   ]
  }
 ]
}