apiVersion: v1
kind: Namespace
metadata:
  name: "design-pattern-analysis-prototype"
  labels:
    cloud-platform.justice.gov.uk/is-production: "false"
    cloud-platform.justice.gov.uk/environment-name: "prototype"
    pod-security.kubernetes.io/enforce: restricted
  annotations:
    cloud-platform.justice.gov.uk/business-unit: "HMPPS"
    cloud-platform.justice.gov.uk/slack-channel: "design-leadership-team"
    cloud-platform.justice.gov.uk/application: "Design pattern analysis"
    cloud-platform.justice.gov.uk/owner: "Design leadership: ben.fraser@justice.gov.uk"
    cloud-platform.justice.gov.uk/source-code: "https://github.com/ministryofjustice/design-pattern-analysis-prototype"
    cloud-platform.justice.gov.uk/team-name: "ministryofjustice"
    cloud-platform.justice.gov.uk/review-after: ""
