kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: mandatory-drug-testing-preprod-admin
  namespace: mandatory-drug-testing-preprod
subjects:
  - kind: Group
    name: "github:hmpps-move-and-improve-live"
    apiGroup: rbac.authorization.k8s.io
############## COPY - DO NOT REPLACE ##############
  - kind: Group
    name: "github:hmpps-sre"
    apiGroup: rbac.authorization.k8s.io
# hmpps-sre group is required for support functions
###################################################
  - kind: Group
    name: "github:hmpps-haar-client-admin"
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
