apiVersion: v1
kind: Namespace
metadata:
  name: "data-platform-app-justice-data-agent-beta-dev"
  labels:
    cloud-platform.justice.gov.uk/is-production: "false"
    cloud-platform.justice.gov.uk/environment-name: "development"
    pod-security.kubernetes.io/enforce: restricted
  annotations:
    cloud-platform.justice.gov.uk/business-unit: "HQ"
    cloud-platform.justice.gov.uk/slack-channel: "public-justice-data-agent"
    cloud-platform.justice.gov.uk/application: "Justice data agent prototype"
    cloud-platform.justice.gov.uk/owner: "Justice Data Agent: justice-data-agent@justice.gov.uk"
    cloud-platform.justice.gov.uk/source-code: "https://github.com/ministryofjustice/justice-data-agent-beta"
    cloud-platform.justice.gov.uk/team-name: "prisons-data-science"
    cloud-platform.justice.gov.uk/review-after: ""
