{
 "title": "LAA DRC Integration Service UAT",
 "tags": [ "laa-dces-drc-integration" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kube_deployment_metadata_generation, namespace)"
    }
   }
  ]
 },
 "panels": [
  { "title": "DCES DRC Integration Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Object Heap Memory Used",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "(jvm_memory_used_bytes{area=\"heap\", id=\"Tenured Gen\", namespace=\"$namespace\"}/jvm_memory_max_bytes{area=\"heap\", id=\"Tenured Gen\", namespace=\"$namespace\"})*100",
     "legendFormat": "Tenured Gen Object Heap Usage for Pod: {{pod}}"
    },
    {
     "expr": "(jvm_memory_used_bytes{area=\"heap\", id=\"Survivor Space\", namespace=\"$namespace\"}/jvm_memory_max_bytes{area=\"heap\", id=\"Survivor Space\", namespace=\"$namespace\"})*100",
     "legendFormat": "Survivor Space Object Heap Usage for Pod: {{pod}}"
    },
    {
     "expr": "(jvm_memory_used_bytes{area=\"heap\", id=\"Eden Space\", namespace=\"$namespace\"}/jvm_memory_max_bytes{area=\"heap\", id=\"Eden Space\", namespace=\"$namespace\"})*100",
     "legendFormat": "Eden Space Object Heap Usage for Pod: {{pod}}"
    }
   ]
  },
  {
   "title": "JVM and System CPU Usage for Pods",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "process_cpu_usage{namespace=\"$namespace\"} * 100",
     "legendFormat": "JVM Process CPU Usage for Pod: {{pod}}"
    },
    {
     "expr": "system_cpu_usage{namespace=\"$namespace\"} * 100",
     "legendFormat": "System CPU Usage for Pod: {{pod}}"
    }
   ]
  },
  {
   "title": "Increases in logs in past 10 minutes (error and info level)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "sum(increase(logback_events_total{level=\"error\", namespace=\"$namespace\"}[10m]))",
     "legendFormat": "Increase in error level logs in the past 10 minutes"
    },
    {
     "expr": "sum(increase(logback_events_total{level=\"info\", namespace=\"$namespace\"}[10m]))",
     "legendFormat": "Increase in info level logs in the past 10 minutes"
    }
   ]
  },
  {
   "title": "Total calls to Maat-API",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "sum by (method) (increase(webclient_requests_seconds_count{method=\"POST\", namespace=\"$namespace\",status=\"200 OK\", uri=~\".*/debt-collection-enforcement/log-contribution-response\"}[$__rate_interval]))",
     "legendFormat": "Contribution"
    },
    {
     "expr": "sum by (method) (increase(webclient_requests_seconds_count{method=\"POST\", namespace=\"$namespace\", status=\"200 OK\" ,uri=~\".*/debt-collection-enforcement/log-fdc-response\"}[$__rate_interval]))",
     "legendFormat": "FDC"
    }
   ]
  }
 ]
}