apiVersion: v1
kind: Namespace
metadata:
  name: github-workflow-logging-dev
  labels:
    cloud-platform.justice.gov.uk/is-production: "false"
    cloud-platform.justice.gov.uk/environment-name: "development"
  annotations:
    cloud-platform.justice.gov.uk/business-unit: "Platforms"
    cloud-platform.justice.gov.uk/application: "github-workflow-logging"
    cloud-platform.justice.gov.uk/owner: "developer-experience: developer-experience@justice.gov.uk"
    cloud-platform.justice.gov.uk/source-code: "https://github.com/ministryofjustice/ministry-of-justice-github-analysis"
    cloud-platform.justice.gov.uk/slack-channel: "#devx-nudge-group"
    cloud-platform.justice.gov.uk/team-name: "octo-developer-experience"
    cloud-platform.justice.gov.uk/review-date: "2027-03-25"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: octo-developer-experience-members
  namespace: github-workflow-logging
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
  - kind: Group
    name: "github:ministryofjustice/octo-developer-experience"
    apiGroup: rbac.authorization.k8s.io
