kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: laa-data-claims-data-factory-uat-admin
  namespace: laa-data-claims-data-factory-uat
subjects:
  - kind: Group
    name: "github:laa-data-claims-data-factory"
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
