{
 "title": "cis-pp Dashboard",
 "tags": [ "cis-pp" ],
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   { "name": "namespace", "query": "cis-pp" }
  ]
 },
 "panels": [
  { "title": "Pods & Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Currently Active Pods",
   "type": "table",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "max(kube_deployment_status_replicas_available{namespace=\"${namespace}\"}) by (deployment)"
    },
    {
     "expr": "max(kube_deployment_spec_replicas{namespace=\"${namespace}\"}) by (deployment)"
    }
   ]
  },
  {
   "title": "HTTP Status Codes",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (status) (rate(nginx_ingress_controller_requests{exported_namespace = \"${namespace}\"}[$__interval]))",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Average Request Duration",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(rate(nginx_ingress_controller_request_duration_seconds_sum{exported_namespace = \"${namespace}\"}[$__interval]) / rate(nginx_ingress_controller_request_duration_seconds_count{exported_namespace = \"${namespace}\"}[$__interval]) > 0)",
     "legendFormat": "Requests"
    }
   ]
  },
  { "title": "Resource Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (pod)(rate(container_cpu_usage_seconds_total{namespace='${namespace}'}[$__interval]))",
     "legendFormat": "Pod: {{pod}}"
    },
    {
     "expr": "avg(kube_pod_container_resource_requests_cpu_cores{namespace='${namespace}'})  ",
     "legendFormat": "Requested (soft limit)"
    },
    {
     "expr": "avg(kube_pod_container_resource_limits_cpu_cores{namespace='${namespace}'})",
     "legendFormat": "Limit (Hard Limit)"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(pod)(container_memory_usage_bytes{namespace='${namespace}'})",
     "legendFormat": "Pod: {{pod}}"
    },
    {
     "expr": "avg(kube_pod_container_resource_requests_memory_bytes{namespace='${namespace}'})",
     "legendFormat": "Requested (soft limit)"
    },
    {
     "expr": "avg(kube_pod_container_resource_limits_memory_bytes{namespace='${namespace}'})",
     "legendFormat": "Limit (Hard Limit)"
    }
   ]
  }
 ]
}