apiVersion: v1
kind: LimitRange
metadata:
  name: limitrange
  namespace: hmpps-probation-mi-ui-test
spec:
  limits:
  - default:
      cpu: 1000m
      memory: 2Gi
    defaultRequest:
      cpu: 10m
      memory: 1Gi
    type: Container

