kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: hmpps-people-on-probation-dev-admin
  namespace: hmpps-people-on-probation-dev
subjects:
  - kind: Group
    name: "github:hmpps-people-on-probation-platform-devs"
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
