{
 "title": "Check if your client qualifies for legal aid - UAT - Ingress",
 "description": "Check if your client qualifies for legal aid - UAT - Ingress",
 "tags": [
  "system",
  "kubernetes",
  "ingress"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(nginx_ingress_controller_requests, exported_namespace)"
    }
   },
   {
    "name": "ingress",
    "query": {
     "query": "label_values(nginx_ingress_controller_requests{exported_namespace = \"$namespace\"}, ingress)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Requests",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_request_duration_seconds_count{exported_namespace = \"$namespace\", path !~\"/socket.io/.*\", ingress = \"$ingress\"}[5m]))",
     "legendFormat": "req / s"
    }
   ]
  },
  {
   "title": "Average Request Duration",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(rate(nginx_ingress_controller_request_duration_seconds_sum{exported_namespace = \"$namespace\", path !~\"/socket.io/.*\", ingress = \"$ingress\"}[5m]) / rate(nginx_ingress_controller_request_duration_seconds_count{exported_namespace = \"$namespace\", path !~\"/socket.io/.*\", ingress = \"$ingress\"}[5m]) > 0)",
     "legendFormat": "avg"
    }
   ]
  },
  {
   "title": "Request HTTP Codes",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_requests{exported_namespace = \"$namespace\", path !~\"/socket.io/.*\", ingress = \"$ingress\"}[5m])) by (status)"
    }
   ]
  },
  {
   "title": "Pod counts by status",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (phase) (kube_pod_status_phase{namespace=\"$namespace\",pod=~\"$ingress.*\"}) "
    }
   ]
  },
  {
   "title": "Request Duration Quantiles",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(nginx_ingress_controller_request_duration_seconds_bucket{exported_namespace = \"$namespace\", path !~\"/socket.io/.*\", ingress = \"$ingress\"}[5m])) by (le))",
     "legendFormat": "0.95"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(nginx_ingress_controller_request_duration_seconds_bucket{exported_namespace = \"$namespace\", path !~\"/socket.io/.*\",ingress = \"$ingress\"}[5m])) by (le))",
     "legendFormat": "0.90"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(nginx_ingress_controller_request_duration_seconds_bucket{exported_namespace = \"$namespace\", path !~\"/socket.io/.*\", ingress = \"$ingress\"}[5m])) by (le))",
     "legendFormat": "0.75"
    }
   ]
  }
 ]
}