{
 "title": "Peoplefinder production",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  { "title": "Deployment Replicas", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Currently Active",
   "type": "table",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "max(kube_deployment_status_replicas_available{namespace=\"peoplefinder-production\"}) by (deployment)"
    },
    {
     "expr": "max(kube_deployment_spec_replicas{namespace=\"peoplefinder-production\"}) by (deployment)"
    }
   ]
  },
  {
   "title": "Request HTTP Codes",
   "type": "graph",
   "gridPos": { "h": 6, "w": 14, "x": 10, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_requests{exported_namespace = \"peoplefinder-production\", ingress = \"peoplefinder-ingress\"}[5m])) by(status)"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (pod_name)(rate(container_cpu_usage_seconds_total{namespace='peoplefinder-production'}[5m]))",
     "legendFormat": "POD: {{ pod_name}}"
    },
    {
     "expr": "avg(kube_pod_container_resource_requests_cpu_cores{namespace='peoplefinder-production'})  ",
     "legendFormat": "Requested (soft limit)"
    },
    {
     "expr": "avg(kube_pod_container_resource_limits_cpu_cores{namespace='peoplefinder-production'})",
     "legendFormat": "Limit (Hard Limit)"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by(pod_name)(container_memory_usage_bytes{namespace='peoplefinder-production'})",
     "legendFormat": "POD: {{ pod_name}}"
    },
    {
     "expr": "avg(kube_pod_container_resource_requests_memory_bytes{namespace='peoplefinder-production'})",
     "legendFormat": "Requested (soft limit)"
    },
    {
     "expr": "avg(kube_pod_container_resource_limits_memory_bytes{namespace='peoplefinder-production'})",
     "legendFormat": "Limit (Hard Limit)"
    }
   ]
  },
  {
   "title": "Average Request Duration",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(rate(nginx_ingress_controller_request_duration_seconds_sum{exported_namespace = \"peoplefinder-production\", ingress = \"peoplefinder-ingress\"}[5m]) / rate(nginx_ingress_controller_request_duration_seconds_count{exported_namespace = \"peoplefinder-production\", ingress = \"peoplefinder-ingress\"}[5m]) > 0)",
     "legendFormat": "Recv"
    }
   ]
  },
  {
   "title": "Network",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "deckbytes" }
   ],
   "targets": [
    {
     "expr": "sort_desc(avg(sum by (pod_name) (rate(container_network_receive_bytes_total{namespace='peoplefinder-production'}[5m]))))",
     "legendFormat": "Recv"
    },
    {
     "expr": "sort_desc(avg(sum by (pod_name) (rate(container_network_transmit_bytes_total{namespace='peoplefinder-production'}[5m]))))",
     "legendFormat": "Sent"
    }
   ]
  }
 ]
}