kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: hmpps-prisoner-finance-prototype-admin
  namespace: hmpps-prisoner-finance-prototype
subjects:
  - kind: Group
    name: "github:hmpps-prisoner-finance-design"
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
