kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: justice-person-platform-prod-admin
  namespace: justice-person-platform-prod
subjects:
  - kind: Group
    name: "github:justice-id"
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
