{
 "title": "SOC production",
 "tags": [ "cdpt" ],
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   { "name": "CacheClusterId", "query": "cp-54ed695970f9c73a-001" },
   {
    "name": "DBInstanceIdentifier",
    "query": "cloud-platform-0ea615e584938140"
   },
   { "name": "namespace", "query": "soc-production" }
  ]
 },
 "panels": [
  { "title": "Pods & Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Active Pods",
   "type": "table",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "max(kube_deployment_status_replicas_available{namespace=\"${namespace}\"}) by (deployment)"
    },
    {
     "expr": "max(kube_deployment_spec_replicas{namespace=\"${namespace}\"}) by (deployment)"
    }
   ]
  },
  {
   "title": "SOC Entry HTTP Status Codes",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (code) (rate(http_requests_received_total{pod=~'socentry-dotnet6app.*'}[$__interval]))",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "SOC Reporting HTTP Status Codes",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (code) (rate(http_requests_received_total{pod=~'socreporting-dotnet6app.*'}[$__interval]))",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "SOC Entry Average Request Duration",
   "type": "timeseries",
   "gridPos": { "x": 8, "y": 7, "h": 6, "w": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(rate(http_request_duration_seconds_sum{pod=~'socentry-dotnet6app.*'}[$__interval])) / avg(rate(http_request_duration_seconds_count{pod=~'socentry-dotnet6app.*'}[$__interval]))",
     "legendFormat": "Requests"
    }
   ]
  },
  {
   "title": "SOC Reporting Average Request Duration",
   "type": "timeseries",
   "gridPos": { "x": 16, "y": 7, "h": 6, "w": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(rate(http_request_duration_seconds_sum{pod=~'socreporting-dotnet6app.*'}[$__interval])) / avg(rate(http_request_duration_seconds_count{pod=~'socreporting-dotnet6app.*'}[$__interval]))",
     "legendFormat": "Requests"
    }
   ]
  },
  { "title": "Resource Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "SOC Entry CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (pod)(rate(container_cpu_usage_seconds_total{namespace='${namespace}', pod=~'socentry-dotnet6app.*'}[$__interval]))",
     "legendFormat": "Pod: {{pod}}"
    },
    {
     "expr": "avg(kube_pod_container_resource_requests_cpu_cores{namespace='${namespace}', pod=~'socentry-dotnet6app.*'})  ",
     "legendFormat": "Requested (soft limit)"
    },
    {
     "expr": "avg(kube_pod_container_resource_limits_cpu_cores{namespace='${namespace}', pod=~'socentry-dotnet6app.*'})",
     "legendFormat": "Limit (Hard Limit)"
    }
   ]
  },
  {
   "title": "SOC Reporting CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (pod)(rate(container_cpu_usage_seconds_total{namespace='${namespace}', pod=~'socreporting-dotnet6app.*'}[$__interval]))",
     "legendFormat": "Pod: {{pod}}"
    },
    {
     "expr": "avg(kube_pod_container_resource_requests_cpu_cores{namespace='${namespace}', pod=~'socreporting-dotnet6app.*'})",
     "legendFormat": "Requested (soft limit)"
    },
    {
     "expr": "avg(kube_pod_container_resource_limits_cpu_cores{namespace='${namespace}', pod=~'socreporting-dotnet6app.*'})",
     "legendFormat": "Limit (Hard Limit)"
    }
   ]
  },
  {
   "title": "SOC Entry Memory Usage",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 24, "h": 10, "w": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(pod)(container_memory_usage_bytes{namespace='${namespace}', pod=~'socentry-dotnet6app.*'})",
     "legendFormat": "Pod: {{pod}}"
    },
    {
     "expr": "avg(kube_pod_container_resource_requests_memory_bytes{namespace='${namespace}', pod=~'socentry-dotnet6app.*'})",
     "legendFormat": "Requested (soft limit)"
    },
    {
     "expr": "avg(kube_pod_container_resource_limits_memory_bytes{namespace='${namespace}', pod=~'socentry-dotnet6app.*'})",
     "legendFormat": "Limit (Hard Limit)"
    }
   ]
  },
  {
   "title": "SOC Reporting Memory Usage",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 24, "h": 10, "w": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(pod)(container_memory_usage_bytes{namespace='${namespace}', pod=~'socreporting-dotnet6app.*'})",
     "legendFormat": "Pod: {{pod}}"
    },
    {
     "expr": "avg(kube_pod_container_resource_requests_memory_bytes{namespace='${namespace}', pod=~'socreporting-dotnet6app.*'})",
     "legendFormat": "Requested (soft limit)"
    },
    {
     "expr": "avg(kube_pod_container_resource_limits_memory_bytes{namespace='${namespace}', pod=~'socreporting-dotnet6app.*'})",
     "legendFormat": "Limit (Hard Limit)"
    }
   ]
  },
  { "title": "AWS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "RDS DatabaseConnections/DiskQueueDepth",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 35, "h": 7, "w": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "application": { "filter": "" },
     "dimensions": { "DBInstanceIdentifier": "$DBInstanceIdentifier" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "DatabaseConnections",
     "namespace": "AWS/RDS",
     "options": {
      "showDisabledItems": false
     },
     "region": "default",
     "statistic": "Average"
    },
    {
     "application": { "filter": "" },
     "dimensions": { "DBInstanceIdentifier": "$DBInstanceIdentifier" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "DiskQueueDepth",
     "namespace": "AWS/RDS",
     "options": {
      "showDisabledItems": false
     },
     "region": "default",
     "statistic": "Average"
    }
   ]
  }
 ]
}