apiVersion: v1
kind: Namespace
metadata:
  name: octo-strategic-docs-prod
  labels:
    cloud-platform.justice.gov.uk/is-production: "true"
    cloud-platform.justice.gov.uk/environment-name: "production"
    pod-security.kubernetes.io/enforce: restricted
  annotations:
    cloud-platform.justice.gov.uk/business-unit: "HQ"
    cloud-platform.justice.gov.uk/slack-channel: "octo-data-architecture"
    cloud-platform.justice.gov.uk/application: "OCTO Strategic Documentation"
    cloud-platform.justice.gov.uk/owner: "OCTO Data Architecture: DataArchitectureJustice@justice.gov.uk"
    cloud-platform.justice.gov.uk/source-code: "https://github.com/ministryofjustice/octo-strategic-docs"
    cloud-platform.justice.gov.uk/team-name: "octo-data-architecture"
    cloud-platform.justice.gov.uk/review-after: "2027-07-23"
