kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: octo-strategic-docs-prod-admin
  namespace: octo-strategic-docs-prod
subjects:
  - kind: Group
    name: "github:octo-data-architecture-leads"
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
