---
apiVersion: v1
kind: LimitRange
metadata:
  name: limitrange
  namespace: annual-leave-apprenticeship-project
spec:
  limits:
    - default:
        cpu: 2000m
        memory: 1024Mi
      defaultRequest:
        cpu: 10m
        memory: 512Mi
      type: Container
