{
 "title": "Kubernetes - nodes",
 "tags": [
  "system",
  "kubernetes"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  { "title": "Masters", "type": "text", "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Masters - Memory available by node",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(node_memory_MemAvailable_bytes) by (instance) * on (instance) group_right(label_kubernetes_io_role) label_replace(kube_node_labels{label_kubernetes_io_role=\"master\"}, \"instance\", \"$1.$2.$3.$4:9100\", \"node\", \"^ip-([0-9]+)-([0-9]+)-([0-9]+)-([0-9]+)\\\\..+$\")",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Masters - CPU by node",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "100 - (avg by (instance) (irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)  * on (instance) group_right(label_kubernetes_io_role) label_replace(kube_node_labels{label_kubernetes_io_role=\"master\"}, \"instance\", \"$1.$2.$3.$4:9100\", \"node\", \"^ip-([0-9]+)-([0-9]+)-([0-9]+)-([0-9]+)\\\\..+$\")"
    }
   ]
  },
  {
   "title": "Masters - Network RX",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_bytes_total[5m])) by (instance) * on (instance) group_right(label_kubernetes_io_role) label_replace(kube_node_labels{label_kubernetes_io_role=\"master\"}, \"instance\", \"$1.$2.$3.$4:9100\", \"node\", \"^ip-([0-9]+)-([0-9]+)-([0-9]+)-([0-9]+)\\\\..+$\")",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Masters - Network TX",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_network_transmit_bytes_total[5m])) by (instance) * on (instance) group_right(label_kubernetes_io_role) label_replace(kube_node_labels{label_kubernetes_io_role=\"master\"}, \"instance\", \"$1.$2.$3.$4:9100\", \"node\", \"^ip-([0-9]+)-([0-9]+)-([0-9]+)-([0-9]+)\\\\..+$\")",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Workers", "type": "text", "gridPos": { "h": 3, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Workers - Memory available by node",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(node_memory_MemAvailable_bytes) by (instance) * on (instance) group_right(label_kubernetes_io_role) label_replace(kube_node_labels{label_kubernetes_io_role=\"node\"}, \"instance\", \"$1.$2.$3.$4:9100\", \"node\", \"^ip-([0-9]+)-([0-9]+)-([0-9]+)-([0-9]+)\\\\..+$\")"
    }
   ]
  },
  {
   "title": "Workers - CPU by node",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "100 - (avg by (instance) (irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)  * on (instance) group_right(label_kubernetes_io_role) label_replace(kube_node_labels{label_kubernetes_io_role=\"node\"}, \"instance\", \"$1.$2.$3.$4:9100\", \"node\", \"^ip-([0-9]+)-([0-9]+)-([0-9]+)-([0-9]+)\\\\..+$\")",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Workers - Network RX",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_bytes_total[5m])) by (instance) * on (instance) group_right(label_kubernetes_io_role) label_replace(kube_node_labels{label_kubernetes_io_role=\"node\"}, \"instance\", \"$1.$2.$3.$4:9100\", \"node\", \"^ip-([0-9]+)-([0-9]+)-([0-9]+)-([0-9]+)\\\\..+$\")",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Workers - Network TX",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_network_transmit_bytes_total[5m])) by (instance) * on (instance) group_right(label_kubernetes_io_role) label_replace(kube_node_labels{label_kubernetes_io_role=\"node\"}, \"instance\", \"$1.$2.$3.$4:9100\", \"node\", \"^ip-([0-9]+)-([0-9]+)-([0-9]+)-([0-9]+)\\\\..+$\")",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}