{
 "title": "Resource Provisioning",
 "tags": [
  "system",
  "kubernetes",
  "resources"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "namespace", "label": "Namespace", "query": "label_values(namespace)" }
  ]
 },
 "panels": [
  {
   "title": "CPU Over",
   "type": "table",
   "description": "Over provisioned containers in regards to CPU",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "topk(10,\n  avg(\n    sum(kube_pod_container_resource_requests_cpu_cores) by (namespace, pod, container) -\n    sum(\n      label_replace(\n        label_replace(\n          rate(container_cpu_usage_seconds_total{namespace =~ \"^${namespace}$\"}[5m]),\n          \"pod\", \"$1\", \"pod_name\", \"(.*)\"\n        ),\n        \"container\", \"$1\", \"container_name\", \"(.*)\"\n      )\n    ) by (namespace, pod, container)\n  )\n  by (namespace, pod, container)\n) * 1000"
    }
   ]
  },
  {
   "title": "CPU Under",
   "type": "table",
   "description": "Under provisioned containers in regards to CPU",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "topk(10,\n  avg(\n    sum(\n      label_replace(\n        label_replace(\n          rate(container_cpu_usage_seconds_total{namespace =~ \"^${namespace}$\"}[5m]),\n          \"pod\", \"$1\", \"pod_name\", \"(.*)\"\n        ),\n        \"container\", \"$1\", \"container_name\", \"(.*)\"\n      )\n    ) by (namespace, pod, container) -\n    sum(kube_pod_container_resource_requests_cpu_cores) by (namespace, pod, container)\n  )\n  by (namespace, pod, container)\n) * 1000"
    }
   ]
  },
  {
   "title": "Memory Over",
   "type": "table",
   "description": "Over provisioned containers in regards to Memory",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "topk(10,\n  avg(\n    sum(kube_pod_container_resource_requests_memory_bytes{namespace =~ \"^${namespace}$\"}) by (namespace, pod, container) -\n    sum(\n      label_replace(\n        label_replace(\n          container_memory_usage_bytes,\n          \"pod\", \"$1\", \"pod_name\", \"(.*)\"\n        ),\n        \"container\", \"$1\", \"container_name\", \"(.*)\"\n      )\n    ) by (namespace, pod, container)\n  )\n  by (namespace, pod, container)\n)"
    }
   ]
  },
  {
   "title": "Memory Under",
   "type": "table",
   "description": "Under provisioned containers in regards to Memory",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "expr": "topk(10,\n  avg(\n    sum(\n      label_replace(\n        label_replace(\n          container_memory_usage_bytes{namespace =~ \"^${namespace}$\"},\n          \"pod\", \"$1\", \"pod_name\", \"(.*)\"\n        ),\n        \"container\", \"$1\", \"container_name\", \"(.*)\"\n      )\n    ) by (namespace, pod, container) -\n    sum(kube_pod_container_resource_requests_memory_bytes) by (namespace, pod, container)\n  )\n  by (namespace, pod, container)\n)"
    }
   ]
  }
 ]
}