apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: laa-claim-for-payment-frontend
spec:
  selector:
    matchLabels:
      app: laa-claim-for-payment-frontend
  endpoints:
    - port: http
      interval: 15s