{
 "title": "HMPPS Manage Intelligence Dashboard Production",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.5,\n  max(\n    irate(nginx_ingress_controller_request_duration_seconds_bucket{ingress=~\"manage-intelligence-v1-2\", exported_namespace=\"hmpps-manage-intelligence-prod\"}[$__rate_interval])\n  ) by (le)\n)",
     "legendFormat": "0.5"
    },
    {
     "expr": "histogram_quantile(\n  0.95,\n  max(\n    irate(nginx_ingress_controller_request_duration_seconds_bucket{ingress=~\"manage-intelligence-v1-2\", exported_namespace=\"hmpps-manage-intelligence-prod\"}[$__rate_interval])\n  ) by (le)\n)",
     "legendFormat": "0.95"
    },
    {
     "expr": "histogram_quantile(\n  1,\n  max(\n    irate(nginx_ingress_controller_request_duration_seconds_bucket{ingress=~\"manage-intelligence-v1-2\", exported_namespace=\"hmpps-manage-intelligence-prod\"}[$__rate_interval])\n  ) by (le)\n)",
     "legendFormat": "1.0"
    }
   ]
  },
  {
   "title": "Ingress Requests",
   "type": "graph",
   "description": "IMS Front End Ingress Requests",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(\n  increase(nginx_ingress_controller_requests{ingress=~\"manage-intelligence|manage-intelligence-.+\", exported_namespace=\"hmpps-manage-intelligence-prod\"}[1m])\n) by (status) != 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SQS - Approximate Number of Messages Visable (Average)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "dimensions": {
      "QueueName": "dps-ims-production-releases-prod-attachment_metadata_extractor_queue"
     },
     "label": "attachment_metadata_extractor_queue\n",
     "metricName": "ApproximateNumberOfMessagesVisible",
     "namespace": "AWS/SQS",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    },
    {
     "dimensions": {
      "QueueName": "dps-ims-production-releases-prod-attachment_metadata_transformer_queue"
     },
     "label": "attachment_metadata_transformer_queue",
     "metricName": "ApproximateNumberOfMessagesVisible",
     "namespace": "AWS/SQS",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    },
    {
     "dimensions": {
      "QueueName": "dps-ims-production-releases-prod-ims_csv_queue"
     },
     "label": "ims_csv_queue",
     "metricName": "ApproximateNumberOfMessagesVisible",
     "namespace": "AWS/SQS",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    },
    {
     "dimensions": {
      "QueueName": "dps-ims-production-releases-prod-ims_extractor_queue"
     },
     "label": "ims_extractor_queue",
     "metricName": "ApproximateNumberOfMessagesVisible",
     "namespace": "AWS/SQS",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    },
    {
     "dimensions": {
      "QueueName": "dps-ims-production-releases-prod-ims_index_batch_queue_prod"
     },
     "label": "ims_index_batch_queue_prod",
     "metricName": "ApproximateNumberOfMessagesVisible",
     "namespace": "AWS/SQS",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    },
    {
     "dimensions": {
      "QueueName": "dps-ims-production-releases-prod-ims_index_update_queue_prod"
     },
     "label": "ims_index_update_queue_prod",
     "metricName": "ApproximateNumberOfMessagesVisible",
     "namespace": "AWS/SQS",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    },
    {
     "dimensions": {
      "QueueName": "dps-ims-production-releases-prod-ims_pdf_queue"
     },
     "label": "ims_pdf_queue",
     "metricName": "ApproximateNumberOfMessagesVisible",
     "namespace": "AWS/SQS",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    },
    {
     "dimensions": {
      "QueueName": "dps-ims-production-releases-prod-ims-reprocess_queue"
     },
     "label": "ims_reprocess_queue",
     "metricName": "ApproximateNumberOfMessagesVisible",
     "namespace": "AWS/SQS",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    },
    {
     "dimensions": {
      "QueueName": "dps-ims-production-releases-prod-ims_transformer_queue"
     },
     "label": "ims_transformer_queue",
     "metricName": "ApproximateNumberOfMessagesVisible",
     "namespace": "AWS/SQS",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    },
    {
     "dimensions": {
      "QueueName": "dps-ims-production-releases-prod-metadata_status_queue"
     },
     "label": "metadata_status_queue",
     "metricName": "ApproximateNumberOfMessagesVisible",
     "namespace": "AWS/SQS",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "SQS - DLQ - Approximate Number of Messages Visable (Average)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "dimensions": {
      "QueueName": "dps-ims-production-releases-prod-attachment_metadata_extractor_dl_queue"
     },
     "label": "attachment_metadata_extractor_dlq",
     "metricName": "ApproximateNumberOfMessagesVisible",
     "namespace": "AWS/SQS",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    },
    {
     "dimensions": {
      "QueueName": "dps-ims-production-releases-prod-attachment_metadata_transformer_dl_queue"
     },
     "label": "attachment_metadata_transformer_dlq",
     "metricName": "ApproximateNumberOfMessagesVisible",
     "namespace": "AWS/SQS",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    },
    {
     "dimensions": {
      "QueueName": "dps-ims-production-releases-prod-ims_csv_dl_queue"
     },
     "label": "ims_csv_dlq",
     "metricName": "ApproximateNumberOfMessagesVisible",
     "namespace": "AWS/SQS",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    },
    {
     "dimensions": {
      "QueueName": "dps-ims-production-releases-prod-ims_extractor_dl_queue_prod"
     },
     "label": "ims_extractor_dlq",
     "metricName": "ApproximateNumberOfMessagesVisible",
     "namespace": "AWS/SQS",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    },
    {
     "dimensions": {
      "QueueName": "dps-ims-production-releases-prod-ims_index_batch_dl_queue_prod"
     },
     "label": "ims_index_batch_dlq",
     "metricName": "ApproximateNumberOfMessagesVisible",
     "namespace": "AWS/SQS",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    },
    {
     "dimensions": {
      "QueueName": "dps-ims-production-releases-prod-ims_index_update_dl_queue_prod"
     },
     "label": "ims_index_update_dlq",
     "metricName": "ApproximateNumberOfMessagesVisible",
     "namespace": "AWS/SQS",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    },
    {
     "dimensions": {
      "QueueName": "dps-ims-production-releases-prod-ims_pdf_dl_queue"
     },
     "label": "ims_pdf_dlq",
     "metricName": "ApproximateNumberOfMessagesVisible",
     "namespace": "AWS/SQS",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    },
    {
     "dimensions": {
      "QueueName": "dps-ims-production-releases-prod-ims_reprocess_dl_queue"
     },
     "label": "ims_reprocess_dlq",
     "metricName": "ApproximateNumberOfMessagesVisible",
     "namespace": "AWS/SQS",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    },
    {
     "dimensions": {
      "QueueName": "dps-ims-production-releases-prod-ims_transformer_dl_queue_prod"
     },
     "label": "ims_transformer_dlq",
     "metricName": "ApproximateNumberOfMessagesVisible",
     "namespace": "AWS/SQS",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    },
    {
     "dimensions": {
      "QueueName": "dps-ims-production-releases-prod-metadata_status_dl_queue"
     },
     "label": "metadata_status_dlq",
     "metricName": "ApproximateNumberOfMessagesVisible",
     "namespace": "AWS/SQS",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Pod Restarts",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "kube_pod_container_status_restarts_total{namespace=\"hmpps-manage-intelligence-prod\", pod!~\"port-forward.*|.*cronjob.*\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "OpenSearch Maximum JVMMemoryPressure",
   "type": "graph",
   "description": "Maximum JVM memory pressure percentage for all data nodes.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "JVMMemoryPressure",
     "dimensions": { "ClientId": "$clientId", "DomainName": "$domainName" },
     "expr": "aws_es_jvmmemory_pressure_maximum{domain_name=\"cloud-platform-cc15074f\"}",
     "legendFormat": "{{ if node_id }} {{ node_id }} {{ else }} {{ end }}",
     "metricName": "JVMMemoryPressure",
     "namespace": "AWS/ES",
     "region": "$region",
     "statistic": "Maximum"
    }
   ]
  },
  {
   "title": "RDS Aurora ACU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "targets": [
    {
     "dimensions": {
      "DBClusterIdentifier": "cloud-platform-b881bb424eb43e8b"
     },
     "label": "RDS - ServerlessDatabaseCapacity",
     "metricName": "ServerlessDatabaseCapacity",
     "namespace": "AWS/RDS",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Maximum"
    },
    {
     "dimensions": {
      "DBClusterIdentifier": "cloud-platform-9f3aab4d10779bf4"
     },
     "label": "RDS Legacy - ServerlessDatabaseCapacity",
     "metricName": "ServerlessDatabaseCapacity",
     "namespace": "AWS/RDS",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Maximum"
    }
   ]
  },
  {
   "title": "Horizontal Pod Autoscaling",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "kube_deployment_status_replicas{namespace=\"hmpps-manage-intelligence-prod\", deployment=\"manage-intelligence\"}",
     "legendFormat": "{{deployment}}"
    },
    {
     "expr": "kube_deployment_status_replicas{namespace=\"hmpps-manage-intelligence-prod\", deployment=\"manage-intelligence-api\"}",
     "legendFormat": "{{deployment}}"
    }
   ]
  }
 ]
}