module "event_daso_queue" {
  
  source = "github.com/ministryofjustice/cloud-platform-terraform-sqs?ref=5.1.2"

  # Queue configuration
  sqs_name                  = "events_daso_queue"
  encrypt_sqs_kms           = "true"
  message_retention_seconds = 1209600

  redrive_policy = <<EOF
  {
    "deadLetterTargetArn": "${module.event_daso_dead_letter_queue.sqs_arn}","maxReceiveCount": 3
  }
  EOF

  # Tags
  business_unit          = var.business_unit
  application            = var.application
  is_production          = var.is_production
  team_name              = var.team_name
  namespace              = var.namespace
  environment_name       = var.environment
  infrastructure_support = var.infrastructure_support
}

module "event_daso_dead_letter_queue" {
  source = "github.com/ministryofjustice/cloud-platform-terraform-sqs?ref=5.1.2"

  # Queue configuration
  sqs_name        = "event_daso_queue_dl"
  encrypt_sqs_kms = "true"

  # Tags
  business_unit          = var.business_unit
  application            = var.application
  is_production          = var.is_production
  team_name              = var.team_name
  namespace              = var.namespace
  environment_name       = var.environment
  infrastructure_support = var.infrastructure_support
}

resource "aws_sqs_queue_policy" "event_daso_queue_policy" {
  queue_url = module.event_daso_queue.sqs_id

  policy = <<EOF
  {
    "Version": "2012-10-17",
    "Id": "${module.event_daso_queue.sqs_arn}/SQSDefaultPolicy",
    "Statement":
      [
        {
          "Effect": "Allow",
          "Principal": {"AWS": "*"},
          "Resource": "${module.event_daso_queue.sqs_arn}",
          "Action": "SQS:SendMessage",
          "Condition":
            {
              "ArnEquals":
                {
                  "aws:SourceArn": "${module.hmpps-integration-events.topic_arn}"
                }
            }
        }
      ]
  }
   EOF
  depends_on = [
    module.hmpps-integration-events
  ]
}


data "aws_secretsmanager_secret" "daso_filter_list" {
  # NB secret name is generated by secret module and could be change. Current version 3.0.0 does not output the name of the secret.
  name = "live-hmpps-integration-api-dev-11e1a9d06fbf9df7"
}

data "aws_secretsmanager_secret_version" "daso_filter_list" {
  secret_id = data.aws_secretsmanager_secret.daso_filter_list.id
}

data "github_repository_file" "daso_subscription_filter_policy" {
  repository          = "${var.github_owner}/${var.github_repo_name}"
  file                = "src/main/resources/event-filter-policies/${var.environment}/daso-subscription-filter.json"
}

resource "aws_sns_topic_subscription" "event_daso_subscription" {
  topic_arn     = module.hmpps-integration-events.topic_arn
  protocol      = "sqs"
  endpoint      = module.event_daso_queue.sqs_arn
  filter_policy = coalesce(var.default_subscription_filter_policy, data.github_repository_file.daso_subscription_filter_policy.content)
  depends_on = [
    module.hmpps-integration-events
  ]
}

resource "kubernetes_secret" "event_daso_queue" {
  metadata {
    name      = "event-daso-queue"
    namespace = var.namespace
  }

  data = {
    sqs_id                        = module.event_daso_queue.sqs_id
    sqs_arn                       = module.event_daso_queue.sqs_arn
    sqs_name                      = module.event_daso_queue.sqs_name
    daso_filter_policy_secret_id = data.aws_secretsmanager_secret_version.daso_filter_list.secret_id
  }
}

resource "kubernetes_secret" "event_daso_dead_letter_queue" {
  metadata {
    name      = "event-daso-dl-queue"
    namespace = var.namespace
  }

  data = {
    sqs_id   = module.event_daso_dead_letter_queue.sqs_id
    sqs_arn  = module.event_daso_dead_letter_queue.sqs_arn
    sqs_name = module.event_daso_dead_letter_queue.sqs_name
  }
}
