# generated by https://github.com/ministryofjustice/money-to-prisoners-deploy
data "aws_ssm_parameter" "application_insights_key" {
  name = "/application_insights/key-prod"
}

resource "kubernetes_secret" "application-insights" {
  metadata {
    name      = "application-insights"
    namespace = var.namespace
  }
  data = {
    APPINSIGHTS_INSTRUMENTATIONKEY        = data.aws_ssm_parameter.application_insights_key.value
    APPLICATIONINSIGHTS_CONNECTION_STRING = "InstrumentationKey=${data.aws_ssm_parameter.application_insights_key.value}"
  }
}
