# generated by https://github.com/ministryofjustice/money-to-prisoners-deploy
module "ecr" {
  source = "github.com/ministryofjustice/cloud-platform-terraform-ecr-credentials?ref=7.0.0"

  providers = {
    aws = aws.london
  }

  business_unit          = var.business_unit
  team_name              = var.team_name
  application            = var.application
  is_production          = var.is_production
  namespace              = var.namespace
  environment_name       = var.environment
  infrastructure_support = var.infrastructure_support

  repo_name = var.application

  github_repositories = [
    "money-to-prisoners-deploy",
    "money-to-prisoners-common",
    "money-to-prisoners-api",
    "money-to-prisoners-cashbook",
    "money-to-prisoners-bank-admin",
    "money-to-prisoners-noms-ops",
    "money-to-prisoners-transaction-uploader",
    "money-to-prisoners-send-money",
    "money-to-prisoners-start-page",
    "money-to-prisoners-emails",
  ]

  oidc_providers = ["circleci", "github"]

  lifecycle_policy = jsonencode(local.expire_untagged_lifecycle_policy)
}

locals {
  expire_untagged_lifecycle_policy = {
    rules = [
      {
        rulePriority = 1
        description  = "Expire untagged images"
        selection = {
          tagStatus   = "untagged"
          countType   = "sinceImagePushed"
          countNumber = 1
          countUnit   = "days"
        }
        action = {
          type = "expire"
        }
      }
    ]
  }
}

data "aws_iam_policy_document" "ecr-cleanup" {
  # Allows deletion of images
  statement {
    actions = [
      "ecr:BatchDeleteImage",
    ]
    resources = [
      module.ecr.repo_arn,
    ]
  }
}

resource "kubernetes_secret" "ecr" {
  metadata {
    name      = "ecr"
    namespace = var.namespace
  }

  data = {
    repo_arn        = module.ecr.repo_arn
    repo_url        = module.ecr.repo_url
    irsa_policy_arn = module.ecr.irsa_policy_arn
  }
}
