# generated by https://github.com/ministryofjustice/money-to-prisoners-deploy
resource "aws_route53_zone" "app_domain" {
  name = "prisoner-money.service.justice.gov.uk."

  tags = {
    business-unit          = var.business-unit
    team_name              = var.team_name
    application            = var.application
    is-production          = var.is-production
    namespace              = var.namespace
    environment-name       = var.environment-name
    owner                  = var.team_name
    infrastructure-support = var.infrastructure-support
  }
}

resource "kubernetes_secret" "app_domain" {
  metadata {
    name      = "route53-app-domain"
    namespace = var.namespace
  }

  data = {
    zone_id      = aws_route53_zone.app_domain.zone_id
    name_servers = join("\n", aws_route53_zone.app_domain.name_servers)
  }
}

resource "aws_route53_record" "app_domain_txt_root" {
  name    = "prisoner-money.service.justice.gov.uk."
  zone_id = aws_route53_zone.app_domain.zone_id
  type    = "TXT"
  ttl     = "300"
  records = [
    "google-site-verification=IUBR5QDuFJbCicN27PV70pqWQHtiRMCBHzYKgF_dWw0"
  ]
}

resource "aws_route53_zone" "send_money" {
  name = "send-money-to-prisoner.service.gov.uk."

  tags = {
    business-unit          = var.business-unit
    team_name              = var.team_name
    application            = var.application
    is-production          = var.is-production
    namespace              = var.namespace
    environment-name       = var.environment-name
    owner                  = var.team_name
    infrastructure-support = var.infrastructure-support
  }
}

resource "kubernetes_secret" "send_money" {
  metadata {
    name      = "route53-send-money"
    namespace = var.namespace
  }

  data = {
    zone_id      = aws_route53_zone.send_money.zone_id
    name_servers = join("\n", aws_route53_zone.send_money.name_servers)
  }
}

resource "aws_route53_record" "send_money_txt_root" {
  name    = "send-money-to-prisoner.service.gov.uk."
  zone_id = aws_route53_zone.send_money.zone_id
  type    = "TXT"
  ttl     = "300"
  records = [
    "google-site-verification=T2qg1AVVzK0DAQSY2SmnS-rRN-hsJFUMeBLiMoyrahY"
  ]
}

resource "aws_route53_zone" "start_page" {
  name = "sendmoneytoaprisoner.justice.gov.uk."

  tags = {
    business-unit          = var.business-unit
    team_name              = var.team_name
    application            = var.application
    is-production          = var.is-production
    namespace              = var.namespace
    environment-name       = var.environment-name
    owner                  = var.team_name
    infrastructure-support = var.infrastructure-support
  }
}

resource "kubernetes_secret" "start_page" {
  metadata {
    name      = "route53-start-page"
    namespace = var.namespace
  }

  data = {
    zone_id      = aws_route53_zone.start_page.zone_id
    name_servers = join("\n", aws_route53_zone.start_page.name_servers)
  }
}

resource "aws_route53_record" "start_page_txt_root" {
  name    = "sendmoneytoaprisoner.justice.gov.uk."
  zone_id = aws_route53_zone.start_page.zone_id
  type    = "TXT"
  ttl     = "300"
  records = [
    "google-site-verification=weAYdFuWe6PfocCiQ66wBE18XZP0vqC1_FRx5BLtr5o"
  ]
}

resource "aws_route53_zone" "start_page_alias" {
  name = "sendmoneytoaprisoner.service.justice.gov.uk."

  tags = {
    business-unit          = var.business-unit
    team_name              = var.team_name
    application            = var.application
    is-production          = var.is-production
    namespace              = var.namespace
    environment-name       = var.environment-name
    owner                  = var.team_name
    infrastructure-support = var.infrastructure-support
  }
}

resource "kubernetes_secret" "start_page_alias" {
  metadata {
    name      = "route53-start-page-alias"
    namespace = var.namespace
  }

  data = {
    zone_id      = aws_route53_zone.start_page_alias.zone_id
    name_servers = join("\n", aws_route53_zone.start_page_alias.name_servers)
  }
}
