# generated by https://github.com/ministryofjustice/money-to-prisoners-deploy
variable "vpc_name" {}
variable "eks_cluster_name" {}

variable "business_unit" {
  default = "HMPPS"
}

variable "team_name" {
  default = "prisoner-money"
}

variable "infrastructure_support" {
  default = "money-to-prisoners@digital.justice.gov.uk"
}

variable "application" {
  default = "money-to-prisoners"
}

variable "environment" {
  default = "prod"
}

variable "is_production" {
  default = "true"
}

variable "namespace" {
  default = "money-to-prisoners-prod"
}
variable "github_owner" {
  description = "The GitHub organization or individual user account containing the app's code repo. Used by the Github Terraform provider. See: https://user-guide.cloud-platform.service.justice.gov.uk/documentation/getting-started/ecr-setup.html#accessing-the-credentials"
  type        = string
  default     = "ministryofjustice"
}

variable "github_token" {
  type        = string
  description = "Required by the GitHub Terraform provider"
  default     = ""
}

