---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: hmpps-court-appearance-scheduler-api-dev-cert
  namespace: hmpps-court-appearance-scheduler-dev
spec:
  secretName: hmpps-court-appearance-scheduler-api-cert
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames:
    - court-appearance-scheduler-api-dev.hmpps.service.justice.gov.uk
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: hmpps-court-appearance-scheduler-ui-dev-cert
  namespace: hmpps-court-appearance-scheduler-dev
spec:
  secretName: hmpps-court-appearance-scheduler-ui-cert
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames:
    - court-appearance-scheduler-dev.hmpps.service.justice.gov.uk
