{
 "title": "manage-soc-cases-preprod / manage-soc-cases / Golden Signals",
 "tags": [ "manage-soc-cases" ],
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Requests",
   "type": "graph",
   "description": "The number of HTTP requests per second received via the ingress.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Rate Per Second" }
   ],
   "targets": [
    {
     "expr": "sum(\n  irate(nginx_ingress_controller_requests{ingress=\"manage-soc-cases\", exported_namespace=\"manage-soc-cases-preprod\"}[1m])\n)",
     "legendFormat": "Requests"
    },
    {
     "expr": "sum(\n  irate(nginx_ingress_controller_requests{ingress=\"manage-soc-cases\", exported_namespace=\"manage-soc-cases-preprod\"}[1m])\n) by (status)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Availability",
   "type": "graph",
   "description": "The percentage of HTTP responses that are non-error codes vs error codes.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "percent", "label": "Percentage" }
   ],
   "targets": [
    {
     "expr": "sum(irate(nginx_ingress_controller_requests{ingress=\"manage-soc-cases\", exported_namespace=\"manage-soc-cases-preprod\", status!~\"5.*|499\"}[1m]))\n/ \nsum(irate(nginx_ingress_controller_requests{ingress=\"manage-soc-cases\", exported_namespace=\"manage-soc-cases-preprod\"}[1m]))\n* 100",
     "legendFormat": "Request Success Rate"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "graph",
   "description": "Recorded request duration from the ingress controllers in percentiles.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "yaxes": [
    { "format": "s", "label": "Seconds" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.5,\n  max(\n    irate(nginx_ingress_controller_request_duration_seconds_bucket{ingress=\"manage-soc-cases\", exported_namespace=\"manage-soc-cases-preprod\"}[1m])\n  ) by (le)\n)",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(\n  0.95,\n  max(\n    irate(nginx_ingress_controller_request_duration_seconds_bucket{ingress=\"manage-soc-cases\", exported_namespace=\"manage-soc-cases-preprod\"}[1m])\n  ) by (le)\n)",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(\n  1,\n  max(\n    irate(nginx_ingress_controller_request_duration_seconds_bucket{ingress=\"manage-soc-cases\", exported_namespace=\"manage-soc-cases-preprod\"}[1m])\n  ) by (le)\n)",
     "legendFormat": "p100"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "graph",
   "description": "The percentage of all HTTP requests that result in a 5xx status.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "yaxes": [
    { "format": "percent", "label": "Percentage" }
   ],
   "targets": [
    {
     "expr": "sum(irate(nginx_ingress_controller_requests{ingress=\"manage-soc-cases\", exported_namespace=\"manage-soc-cases-preprod\", status=\"500\"}[1m])) \n/ \nsum(irate(nginx_ingress_controller_requests{ingress=\"manage-soc-cases\", exported_namespace=\"manage-soc-cases-preprod\"}[5m]))\n* 100",
     "legendFormat": "500"
    },
    {
     "expr": "sum(irate(nginx_ingress_controller_requests{ingress=\"manage-soc-cases\", exported_namespace=\"manage-soc-cases-preprod\", status=\"501\"}[1m])) \n/ \nsum(irate(nginx_ingress_controller_requests{ingress=\"manage-soc-cases\", exported_namespace=\"manage-soc-cases-preprod\"}[5m]))\n* 100",
     "legendFormat": "501"
    },
    {
     "expr": "sum(irate(nginx_ingress_controller_requests{ingress=\"manage-soc-cases\", exported_namespace=\"manage-soc-cases-preprod\", status=\"502\"}[1m])) \n/ \nsum(irate(nginx_ingress_controller_requests{ingress=\"manage-soc-cases\", exported_namespace=\"manage-soc-cases-preprod\"}[5m]))\n* 100",
     "legendFormat": "502"
    },
    {
     "expr": "sum(irate(nginx_ingress_controller_requests{ingress=\"manage-soc-cases\", exported_namespace=\"manage-soc-cases-preprod\", status=\"503\"}[1m])) \n/ \nsum(irate(nginx_ingress_controller_requests{ingress=\"manage-soc-cases\", exported_namespace=\"manage-soc-cases-preprod\"}[5m]))\n* 100",
     "legendFormat": "503"
    },
    {
     "expr": "sum(irate(nginx_ingress_controller_requests{ingress=\"manage-soc-cases\", exported_namespace=\"manage-soc-cases-preprod\", status=\"504\"}[1m])) \n/ \nsum(irate(nginx_ingress_controller_requests{ingress=\"manage-soc-cases\", exported_namespace=\"manage-soc-cases-preprod\"}[5m]))\n* 100",
     "legendFormat": "504"
    }
   ]
  },
  {
   "title": "Requested CPU Usage",
   "type": "graph",
   "description": "CPU usage in relation to the requested cpu for the container.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "percent", "label": "Percentage" }
   ],
   "targets": [
    {
     "expr": "avg(irate(container_cpu_usage_seconds_total{pod=~\"manage-soc-cases-.+\", namespace=\"manage-soc-cases-preprod\"}[1m])) by (container)\n/ \navg(label_replace(kube_pod_container_resource_requests_cpu_cores{pod=~\"manage-soc-cases-.+\", namespace=\"manage-soc-cases-preprod\"}, \"container_name\", \"$1\", \"container\", \"(.*)\")) by (container)",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Requested Memory Usage",
   "type": "graph",
   "description": "Memory usage in relation to the requested memory for the container.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 16 },
   "yaxes": [
    { "format": "percent", "label": "Percentage" }
   ],
   "targets": [
    {
     "expr": "avg(irate(container_memory_usage_bytes{pod=~\"manage-soc-cases-.+\", namespace=\"manage-soc-cases-preprod\"}[1m])) by (container)\n/ \navg(kube_pod_container_resource_requests_memory_bytes{pod=~\"manage-soc-cases-.+\", namespace=\"manage-soc-cases-preprod\"}) by (container)\n* 100",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "No. of Replicas",
   "type": "graph",
   "description": "The number of available pod replicas for the service.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 16 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "count(\n  label_replace(kube_pod_info{pod=~\"manage-soc-cases-.+\", namespace=\"manage-soc-cases-preprod\"}, \"pod\", \"$1\", \"created_by_name\", \"(.*)-\\\\w+\")\n) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Actual CPU Usage",
   "type": "graph",
   "description": "Average recorded CPU usage for each type container within the pods.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(\n  irate(container_cpu_usage_seconds_total{pod=~\"manage-soc-cases-.+\", namespace=\"manage-soc-cases-preprod\", container!=\"POD\", container=~\".+\"}[1m])\n) by (container)",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Actual Memory Usage",
   "type": "graph",
   "description": "Average recorded memory usage for a single type of container within the pods.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 24 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "avg(\n  irate(container_memory_usage_bytes{pod=~\"manage-soc-cases-.+\", namespace=\"manage-soc-cases-preprod\", container!=\"POD\", container=~\".+\"}[1m])\n) by (container)",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Network I/O",
   "type": "graph",
   "description": "The amount of data being sent to and from the pods.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 24 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_network_receive_bytes_total{namespace=\"manage-soc-cases-preprod\", pod=~\"manage-soc-cases-.+\"}[2m]))",
     "legendFormat": "Receive"
    },
    {
     "expr": "sum(irate(container_network_transmit_bytes_total{namespace=\"manage-soc-cases-preprod\", pod=~\"manage-soc-cases-.+\"}[2m]))",
     "legendFormat": "Transmit"
    }
   ]
  }
 ]
}
{
 "title": "manage-soc-cases-preprod / manage-soc-cases-api / Golden Signals",
 "tags": [ "manage-soc-cases-api" ],
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Requests",
   "type": "graph",
   "description": "The number of HTTP requests per second received via the ingress.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Rate Per Second" }
   ],
   "targets": [
    {
     "expr": "sum(\n  irate(nginx_ingress_controller_requests{ingress=\"manage-soc-cases-api\", exported_namespace=\"manage-soc-cases-preprod\"}[1m])\n)",
     "legendFormat": "Requests"
    },
    {
     "expr": "sum(\n  irate(nginx_ingress_controller_requests{ingress=\"manage-soc-cases-api\", exported_namespace=\"manage-soc-cases-preprod\"}[1m])\n) by (status)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Availability",
   "type": "graph",
   "description": "The percentage of HTTP responses that are non-error codes vs error codes.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "percent", "label": "Percentage" }
   ],
   "targets": [
    {
     "expr": "sum(irate(nginx_ingress_controller_requests{ingress=\"manage-soc-cases-api\", exported_namespace=\"manage-soc-cases-preprod\", status!~\"5.*|499\"}[1m]))\n/ \nsum(irate(nginx_ingress_controller_requests{ingress=\"manage-soc-cases-api\", exported_namespace=\"manage-soc-cases-preprod\"}[1m]))\n* 100",
     "legendFormat": "Request Success Rate"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "graph",
   "description": "Recorded request duration from the ingress controllers in percentiles.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "yaxes": [
    { "format": "s", "label": "Seconds" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.5,\n  max(\n    irate(nginx_ingress_controller_request_duration_seconds_bucket{ingress=\"manage-soc-cases-api\", exported_namespace=\"manage-soc-cases-preprod\"}[1m])\n  ) by (le)\n)",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(\n  0.95,\n  max(\n    irate(nginx_ingress_controller_request_duration_seconds_bucket{ingress=\"manage-soc-cases-api\", exported_namespace=\"manage-soc-cases-preprod\"}[1m])\n  ) by (le)\n)",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(\n  1,\n  max(\n    irate(nginx_ingress_controller_request_duration_seconds_bucket{ingress=\"manage-soc-cases-api\", exported_namespace=\"manage-soc-cases-preprod\"}[1m])\n  ) by (le)\n)",
     "legendFormat": "p100"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "graph",
   "description": "The percentage of all HTTP requests that result in a 5xx status.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "yaxes": [
    { "format": "percent", "label": "Percentage" }
   ],
   "targets": [
    {
     "expr": "sum(irate(nginx_ingress_controller_requests{ingress=\"manage-soc-cases-api\", exported_namespace=\"manage-soc-cases-preprod\", status=\"500\"}[1m])) \n/ \nsum(irate(nginx_ingress_controller_requests{ingress=\"manage-soc-cases-api\", exported_namespace=\"manage-soc-cases-preprod\"}[5m]))\n* 100",
     "legendFormat": "500"
    },
    {
     "expr": "sum(irate(nginx_ingress_controller_requests{ingress=\"manage-soc-cases-api\", exported_namespace=\"manage-soc-cases-preprod\", status=\"501\"}[1m])) \n/ \nsum(irate(nginx_ingress_controller_requests{ingress=\"manage-soc-cases-api\", exported_namespace=\"manage-soc-cases-preprod\"}[5m]))\n* 100",
     "legendFormat": "501"
    },
    {
     "expr": "sum(irate(nginx_ingress_controller_requests{ingress=\"manage-soc-cases-api\", exported_namespace=\"manage-soc-cases-preprod\", status=\"502\"}[1m])) \n/ \nsum(irate(nginx_ingress_controller_requests{ingress=\"manage-soc-cases-api\", exported_namespace=\"manage-soc-cases-preprod\"}[5m]))\n* 100",
     "legendFormat": "502"
    },
    {
     "expr": "sum(irate(nginx_ingress_controller_requests{ingress=\"manage-soc-cases-api\", exported_namespace=\"manage-soc-cases-preprod\", status=\"503\"}[1m])) \n/ \nsum(irate(nginx_ingress_controller_requests{ingress=\"manage-soc-cases-api\", exported_namespace=\"manage-soc-cases-preprod\"}[5m]))\n* 100",
     "legendFormat": "503"
    },
    {
     "expr": "sum(irate(nginx_ingress_controller_requests{ingress=\"manage-soc-cases-api\", exported_namespace=\"manage-soc-cases-preprod\", status=\"504\"}[1m])) \n/ \nsum(irate(nginx_ingress_controller_requests{ingress=\"manage-soc-cases-api\", exported_namespace=\"manage-soc-cases-preprod\"}[5m]))\n* 100",
     "legendFormat": "504"
    }
   ]
  },
  {
   "title": "Requested CPU Usage",
   "type": "graph",
   "description": "CPU usage in relation to the requested cpu for the container.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "percent", "label": "Percentage" }
   ],
   "targets": [
    {
     "expr": "avg(irate(container_cpu_usage_seconds_total{pod=~\"manage-soc-cases-api-.+\", namespace=\"manage-soc-cases-preprod\"}[1m])) by (container)\n/ \navg(label_replace(kube_pod_container_resource_requests_cpu_cores{pod=~\"manage-soc-cases-api-.+\", namespace=\"manage-soc-cases-preprod\"}, \"container_name\", \"$1\", \"container\", \"(.*)\")) by (container)",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Requested Memory Usage",
   "type": "graph",
   "description": "Memory usage in relation to the requested memory for the container.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 16 },
   "yaxes": [
    { "format": "percent", "label": "Percentage" }
   ],
   "targets": [
    {
     "expr": "avg(irate(container_memory_usage_bytes{pod=~\"manage-soc-cases-api-.+\", namespace=\"manage-soc-cases-preprod\"}[1m])) by (container)\n/ \navg(kube_pod_container_resource_requests_memory_bytes{pod=~\"manage-soc-cases-api-.+\", namespace=\"manage-soc-cases-preprod\"}) by (container)\n* 100",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "No. of Replicas",
   "type": "graph",
   "description": "The number of available pod replicas for the service.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 16 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "count(\n  label_replace(kube_pod_info{pod=~\"manage-soc-cases-api-.+\", namespace=\"manage-soc-cases-preprod\"}, \"pod\", \"$1\", \"created_by_name\", \"(.*)-\\\\w+\")\n) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Actual CPU Usage",
   "type": "graph",
   "description": "Average recorded CPU usage for each type container within the pods.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(\n  irate(container_cpu_usage_seconds_total{pod=~\"manage-soc-cases-api-.+\", namespace=\"manage-soc-cases-preprod\", container!=\"POD\", container=~\".+\"}[1m])\n) by (container)",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Actual Memory Usage",
   "type": "graph",
   "description": "Average recorded memory usage for a single type of container within the pods.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 24 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "avg(\n  irate(container_memory_usage_bytes{pod=~\"manage-soc-cases-api-.+\", namespace=\"manage-soc-cases-preprod\", container!=\"POD\", container=~\".+\"}[1m])\n) by (container)",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Network I/O",
   "type": "graph",
   "description": "The amount of data being sent to and from the pods.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 24 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_network_receive_bytes_total{namespace=\"manage-soc-cases-preprod\", pod=~\"manage-soc-cases-api-.+\"}[2m]))",
     "legendFormat": "Receive"
    },
    {
     "expr": "sum(irate(container_network_transmit_bytes_total{namespace=\"manage-soc-cases-preprod\", pod=~\"manage-soc-cases-api-.+\"}[2m]))",
     "legendFormat": "Transmit"
    }
   ]
  }
 ]
}