apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: dc-learning-sandbox-admin
  namespace: dc-learning-sandbox
subjects:
  - kind: Group
    name: "github:dc-learning-sandbox-team"
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: dc-learning-sandbox-calico-np-access
  namespace: dc-learning-sandbox
subjects:
  - kind: Group
    name: "github:dc-learning-sandbox-team"
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: calico-network-policy-access
  apiGroup: rbac.authorization.k8s.io
