apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: prison-users-api-dev.prison.service.justice.gov.uk
  namespace: hmpps-prison-users-dev
spec:
  secretName: prison-users-api-cert
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames:
    - prison-users-api-dev.prison.service.justice.gov.uk
