apiVersion: v1
kind: LimitRange
metadata:
  name: limitrange
  namespace: laa-get-payments-finance-data-dev
spec:
  limits:
  - default:
      cpu: 1
      memory: 3Gi
    defaultRequest:
      cpu: 50m
      memory: 1792Mi
    type: Container
