{
 "title": "DEX-MI Metabase Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Pods overview health",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 13, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum({namespace=\"dex-mi-production\", phase='Running'} + 0)"
    },
    {
     "expr": "sum(rate(kube_pod_container_status_restarts_total{namespace=\"dex-mi-production\"} [60m]))"
    }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg by (container)(rate(container_cpu_usage_seconds_total{namespace=\"dex-mi-production\"}[5m]))"
    }
   ]
  },
  {
   "title": "Memory Usage with limit",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "avg by (container)(container_memory_usage_bytes{namespace=\"dex-mi-production\"})",
     "legendFormat": "{{container}}"
    },
    {
     "expr": "avg(kube_pod_container_resource_requests_memory_bytes{namespace=\"dex-mi-production\"})",
     "legendFormat": "Request limit"
    },
    {
     "expr": "avg(kube_pod_container_resource_limits_memory_bytes{namespace=\"dex-mi-production\"})",
     "legendFormat": "Hard limit"
    }
   ]
  },
  {
   "title": "Ingress Controller Requests",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_requests{exported_namespace = \"dex-mi-production\", ingress = \"dex-mi-production-metabase-ingress\"}[5m])) by(status)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Average Request Duration",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(rate(nginx_ingress_controller_request_duration_seconds_sum{exported_namespace = \"dex-mi-production\", ingress = \"dex-mi-production-metabase-ingress\"}[5m]) / rate(nginx_ingress_controller_request_duration_seconds_count{exported_namespace = \"dex-mi-production\", ingress = \"dex-mi-production-metabase-ingress\"}[5m]) > 0)",
     "legendFormat": "Average Request Duration"
    }
   ]
  }
 ]
}