on:
  pull_request:
    types: [opened, edited, reopened, synchronize]

jobs:
  reject-malformed-yaml:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: ministryofjustice/github-actions/malformed-yaml@72fe7d2b80a33b5e3f23dffa31236bd45027450b # v18.1.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.number }}
