on:
  pull_request:
    types: [opened, edited, reopened, synchronize]
    paths:
      - 'policy/**'

name: OPA tests
jobs:
  opa-tests:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository code
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

    - name: Setup OPA
      uses: open-policy-agent/setup-opa@34a30e8a924d1b03ce2cf7abe97250bbb1f332b5 # v2.2.0
      with:
        version: latest

    - name: Run OPA Tests
      run: |
        echo "OPA Tests version:"
        opa version
        opa test policy/*.rego -v --v0-compatible
