on:
  pull_request:
    paths:
      - 'namespaces/live.cloud-platform.service.justice.gov.uk/**'

jobs:
  reject-multi-namespace-prs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: ministryofjustice/cloud-platform-multiple-namespace-github-action@20261dc0e118ed124aa5624e7cac3fe511635d74 # main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
