apiVersion: v1
kind: Namespace
metadata:
  name: "jackapp-dev"
  labels:
    cloud-platform.justice.gov.uk/is-production: "false"
    cloud-platform.justice.gov.uk/environment-name: "development"
    pod-security.kubernetes.io/enforce: restricted
  annotations:
    cloud-platform.justice.gov.uk/business-unit: "Platforms"
    cloud-platform.justice.gov.uk/slack-channel: "cloud-platform"
    cloud-platform.justice.gov.uk/application: "development-app"
    cloud-platform.justice.gov.uk/owner: "cloud-platform: cloud-platform@justice.gov.uk"
    cloud-platform.justice.gov.uk/source-code: "https://github.com/ministryofjustice/jack_development_application"
    cloud-platform.justice.gov.uk/team-name: "cloud-platform-secret"
    cloud-platform.justice.gov.uk/review-after: "2026-12-22"
